### ISSUE TITLE
Inconsistent table deletion in the db

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10039]
From slack: https://openmetadata.slack.com/archives/C02B6955S4S/p1673544277210129

We have a trace like

```
org.openmetadata.service.exception.UnhandledServerException: An exception with message [Entity type table not found] was thrown while processing request.
        at org.openmetadata.service.jdbi3.EntityRepository.ensureSingleRelationship(EntityRepository.java:1003)
        at org.openmetadata.service.jdbi3.EntityRepository.getFromEntityRef(EntityRepository.java:984)
        at org.openmetadata.service.jdbi3.EntityRepository.getContainer(EntityRepository.java:978)
        at org.openmetadata.service.jdbi3.TableRepository.setDefaultFields(TableRepository.java:139)
        at org.openmetadata.service.jdbi3.TableRepository.setFields(TableRepository.java:124)
        at org.openmetadata.service.jdbi3.TableRepository.setFields(TableRepository.java:92)
        at org.openmetadata.service.jdbi3.EntityRepository.setFieldsInternal(EntityRepository.java:445)
        at org.openmetadata.service.jdbi3.EntityRepository.listAfter(EntityRepository.java:344)
        at 
```

Looks like when deleting tables, not all the relationships are cleaned up. From the conversation:

```
I just applyed new filters in a metadata ingestion tha's checked the option "Mark Deleted Tables" so when I runned the ingestion again it marked some tables as deleted.

In fact I remember one more thing... I did it as I said to one database service and I deleted (trough the UI) other database service that has aleady ingested a lot of tables and recreate it with some filters too. i.e. everything was done through the UI.
```

The user was able to run a query to delete the inconsistencies

```
WITH qry AS (
  SELECT
    te.*
  FROM
    openmetadata_db.table_entity te
  LEFT JOIN
    openmetadata_db.database_schema_entity dse
    ON dse.fullyQualifiedName = LEFT(te.fullyQualifiedName, CHAR_LENGTH(te.fullyQualifiedName) - LOCATE('.', REVERSE(te.fullyQualifiedName)))
  WHERE 
    dse.id IS NULL
)
DELETE FROM openmetadata_db.table_entity WHERE id IN (SELECT id FROM qry);
```

**Comment by nuang-ee** [comment]
I stumbled into similar issue.
- User deleted databaseSchema with UI below:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/50770626/225234211-022719ad-0a4d-4b3a-952b-5bdc4f57d4b5.png">
- Then, related `TableEntity` are not deleted.
- In Activity view, it displays activity like:

```
<username> posted on databaseSchema <databaseSchemaName, with href>
Permanently Deleted **databaseSchema**: `databaseSchemaFullyQualifiedName`
```

which makes lots of error alert pop up when user's mouse hover on the href.

---

@pmbrull Thanks for sharing the query! It resolved the inconsistencies on my case too.

**Comment by nahuelverdugo** [comment]
Hi @nuang-ee, would you happen to have more information about the deleted database schema to know if we can reproduce the error somehow? For example, the number of tables, service type, etc.

**Comment by harshach** [comment]
now that JdbiUnitOfWork is in, I hope this doesn't happen **Prays to Heavens**!!
