### ISSUE TITLE
Custom Pydantic Exception

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10140]
https://openmetadata.slack.com/archives/C02B6955S4S/p1675806953969199

When having errors such as 
```
\metadata\ingestion\source\database\common_db_source.py", line 177, in yield_database_schema
 File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CreateDatabaseSchemaRequest
name -> __root__
  string does not match regex "^[\w\'\- .&]+$" (type=value_error.str.regex; pattern=^[\w\'\- .&]+$)
```
Getting a custom exception that tells us what is the name being rejected would help identifying the issues. We have a similar implementation here https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/api/parser.py#L394 that we can directly use in all sources

**Comment by pmbrull** [comment]
UPDATE: Looks like `DEBUG` logs already throw more information:
```
2023-02-08 14:53:37] DEBUG    {metadata.Ingestion:sql_column_handler:262} - Traceback (most recent call last):
  File "/Users/harsha/Code/OpenMetadata/env/lib/python3.10/site-packages/metadata/ingestion/source/database/sql_column_handler.py", line 236, in get_columns_and_constraints
    om_column = Column(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Column
name -> __root__
  string does not match regex "^(?u)[\w\'\-" .+#]+$" (type=value_error.str.regex; pattern=^(?u)[\w\'\-" .+#]+$)

[2023-02-08 14:53:37] WARNING  {metadata.Ingestion:sql_column_handler:263} - Unexpected exception processing column [{'name': 'LastName$', 'type': VARCHAR(length=255), 'default': None, 'comment': None, 'nullable': True}]: 1 validation error for Column
name -> __root__
  string does not match regex "^(?u)[\w\'\-" .+#]+$" (type=value_error.str.regex; pattern=^(?u)[\w\'\-" .+#]+$)
```
let's make this more visible by default

**Comment by pmbrull** [comment]
handled already by the new status
