### ISSUE TITLE
Unable to parse queries with hyphens in bigquery lineage ingestions

### ISSUE THREAD

**Issue by alanplarium** [open-metadata/OpenMetadata#10250]
**Affected module**
Bigquery lineage

**Describe the bug**
I get in the logs of the ingestion lineage that queries with project with hyphens are failed to be parsed

**To Reproduce**
Trying to parse this query

insert into `pro-ject-999.data_set1.table_number_one` select * from pro-ject-888.data_set2.table_number_two

If i try to sqllineage this query as: 
`sqllineage -f filewherequeryis.sql`
It will fail with same error

Screenshots or steps to reproduce

`[2023-02-21 08:20:49,878] {sql_lineage.py:338} DEBUG - Running lineage with query: insert into `proj-ect-999.data_set1.table_number_one` select * from pro-ject-888.data_set2.table_number_two
[2023-02-21 08:20:49,920] {parser.py:398} DEBUG - Lineage with SqlFluff failed for the [bigquery] query: [insert into `pro-ject-999.data_set1.table_number_one` select * from pro-ject-888.data_set2.table_number_two]
[2023-02-21 08:20:49,925] {sql_lineage.py:381} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/lineage/sql_lineage.py", line 341, in get_lineage_by_query
    raw_column_lineage = lineage_parser.column_lineage
  File "/home/airflow/.local/lib/python3.9/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/lineage/parser.py", line 114, in column_lineage
    return self.parser.get_column_lineage()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/runner.py", line 35, in wrapper
    self._eval()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/runner.py", line 207, in _eval
    self._stmt_holders = [self.run_lineage_analyzer(stmt) for stmt in self._stmt]
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/runner.py", line 207, in <listcomp>
    self._stmt_holders = [self.run_lineage_analyzer(stmt) for stmt in self._stmt]
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/runner.py", line 239, in run_lineage_analyzer
    return LineageAnalyzer().analyze(stmt)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/core/analyzer.py", line 60, in analyze
    self._extract_from_dml(stmt, AnalyzerContext())
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/core/analyzer.py", line 135, in _extract_from_dml
    next_handler.handle(sub_token, holder)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/core/handlers/base.py", line 37, in handle
    self._handle(token, holder)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/core/handlers/source.py", line 60, in _handle
    self._handle_table(token, holder)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/core/handlers/source.py", line 86, in _handle_table
    raise SQLLineageException(
  sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Operation[value: proj-ect] instead.`

**Expected behavior**

**Version:**
Installed as helm chart so the corresponding to 0.13.2
 - OpenMetadata version: 0.13.2 

**Additional context**
I set query duration log is 1 day with limit of 20.000 queries

**Comment by nahuelverdugo** [comment]
I have added these 2 tests in `openmetadata-sqllineage` library:
```python
@pytest.mark.parametrize("dialect", ["bigquery"])
def test_insert_hyphen_db_name(dialect: str):
    assert_table_lineage_equal(
        "insert into `pro-ject-999.data_set1.table_number_one` select * from pro-ject-888.data_set2.table_number_two",
        {"pro-ject-888.data_set2.table_number_two"},
        {"pro-ject-999.data_set1.table_number_one"},
        dialect=dialect,
        test_sqlparse=False
    )


@pytest.mark.parametrize("dialect", ["bigquery"])
def test_insert_hyphen_db_name_2(dialect: str):
    assert_table_lineage_equal(
        "insert into pro-ject-999.data_set1.table_number_one select * from pro-ject-888.data_set2.table_number_two",
        {"pro-ject-888.data_set2.table_number_two"},
        {"pro-ject-999.data_set1.table_number_one"},
        dialect=dialect,
        test_sqlparse=False
    )
```

And they are being parsed fine.

Also, with the `CLI`:

![image](https://user-images.githubusercontent.com/11074908/229522266-65152539-06da-4310-ac4d-575a8e14de12.png)

@alanplarium, if you keep seeing the error after `1.0` release, feel free to reopen this issue. 

Thank you!
