### ISSUE TITLE
Minio S3: botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by sapcode** [open-metadata/OpenMetadata#10279]
Affected module
The error occurs in the Ingestion Framework. The Airflow python code can access the bucket files because they are mentioned in the Logs, but it looks like that during pagination or opening of the file the exception is thrown: 
**botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.**

Describe the bug
Using the Datalake connector to read a PARQUET file from an S3 bucket an error happens. Here is the error part of the log:

[ingestion_debug.log](https://github.com/open-metadata/OpenMetadata/files/10803457/ingestion_debug.log)

**[2023-02-22 11:45:55,120] {metadata.py:562} ERROR - Unexpected exception to get S3 file [connector-prototype/transformed/20230221-200015.parquet] from bucket [artifacts]: The AWS Access Key Id you provided does not exist in our records.**
[2023-02-22 11:45:55,120] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.location.Location'> processor='yield_location' context='location' ack_sink=True nullable=True must_return=False cache_all=False clear_cache=False overwrite=True consumer=['storage_service']
[2023-02-22 11:45:55,120] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.ingestion.source.database.database_service.TableLocationLink'> processor='yield_table_location_link' context=None ack_sink=False nullable=True must_return=False cache_all=False clear_cache=False overwrite=True consumer=None
[2023-02-22 11:45:55,120] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.table.Table'> processor='yield_table' context='table' ack_sink=True nullable=False must_return=False cache_all=False clear_cache=False overwrite=True consumer=['database_service', 'database', 'database_schema']
[2023-02-22 11:45:55,217] {metadata.py:561} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 394, in _lsdir
    for i in it:
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
**botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.**

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/datalake/metadata.py", line 555, in get_s3_files
    return read_parquet_from_s3(client_kwargs, key, bucket_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/s3_utils.py", line 98, in read_parquet_from_s3
    dataset = pq.ParquetDataset(bucket_uri, filesystem=s3_fs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyarrow/parquet/__init__.py", line 1719, in __init__
    self._metadata_path) = _make_manifest(
  File "/home/airflow/.local/lib/python3.9/site-packages/pyarrow/parquet/__init__.py", line 2184, in _make_manifest
    if _is_path_like(path_or_paths) and fs.isdir(path_or_paths):
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 601, in isdir
    return bool(self._lsdir(path))
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 409, in _lsdir
    raise translate_boto_error(e)
**PermissionError: The AWS Access Key Id you provided does not exist in our records.**

To Reproduce
1) Install Openmetadata in minikube into an own namespace openmetdata 
2) Try to extract S3 Data from Minio

We have a minio Datalake connection setup
bucket: artifacts
region: eu-central-1
Some example parquet Files exists

Connection settings:
![image](https://user-images.githubusercontent.com/10140758/220613433-23b0e7b2-4ed3-4dcf-a954-3efd7f39824b.png)

Connect test seems to be ok:
![image](https://user-images.githubusercontent.com/10140758/220613461-32a4dc07-f949-492c-aa15-824405171f8d.png)

Expected behavior
The parquet files should be all read

Version:

OS: Ubuntu 22.04
Minikube: v1.29.0
Kubernetes: v1.26.1
Python version: 3.9 managed by helm chart installer
OpenMetadata version: openmetadata/server:0.13.2 managed by helm chart installer
OpenMetadata Ingestion package version: openmetadata/ingestion:0.13.2 managed by helm chart installer

Other Information:
This blogs describes the same issue related to session handling in boto3: https://stackoverflow.com/questions/43907689/boto3-error-the-aws-access-key-id-you-provided-does-not-exist-in-our-records

**Comment by sapcode** [comment]
Dear @pmbrull  and @harshach,
we have reconstructed the issue in the following lines:
/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/s3_utils.py
![image](https://user-images.githubusercontent.com/10140758/220881997-e89a106b-f313-4ee7-a321-ba52898f1108.png)

The problem is that you are not passing the Endpoint URL from the Ingestion GUI with the client_kwargs The Fix should look like this:
```
  fs = s3fs.S3FileSystem(
        anon=False,
        use_ssl=True,
        client_kwargs={
            "region_name": S3_REGION,
            "endpoint_url": S3_ENDPOINT,
            "aws_access_key_id": S3_ACCESS_KEY,
            "aws_secret_access_key": S3_SECRET_KEY,
            "verify": True,
        }
    )    
``` 
Please could you also make "use_ssl" available in the GUI or derive it automatically from the Endpoint URL via HTTP or HTTPS parsing.

**Comment by SuperNascher** [comment]
We have created a fix for this: https://github.com/alpinanalytics/OpenMetadata/commit/6931667946f4599d2ea9118b4ff6838a4beb06ab

I will later create a PR for this issue :-)

**Comment by sapcode** [comment]
@harshach + @pmbrull the same issue 1 + issue 2 happens also in the Data Profiler ingestion job so we will need both fixes there as well:

`
[2023-02-23 11:49:37,776] {metadata.py:561} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/datalake/metadata.py", line 555, in get_s3_files
    return read_parquet_from_s3(client_kwargs, key, bucket_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/s3_utils.py", line 91, in read_parquet_from_s3
    if client.awsAccessKeyId and client.awsSecretAccessKey:
AttributeError: 'NoneType' object has no attribute 'awsAccessKeyId'
[2023-02-23 11:49:37,776] {metadata.py:562} ERROR - Unexpected exception to get S3 file [connector-prototype/raw/20230221-200015.parquet] from bucket [artifacts]: 'NoneType' object has no attribute 'awsAccessKeyId'
[2023-02-23 11:49:37,777] {core.py:419} INFO - Computing profile metrics for S3.default.artifacts."connector-prototype/raw/20230221-200015.parquet"...
[2023-02-23 11:49:37,779] {workflow.py:469} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/api/workflow.py", line 456, in run_profiler_workflow
    profile: ProfilerResponse = self.profiler_obj.process(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/core.py", line 423, in process
    self.compute_metrics()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/core.py", line 407, in compute_metrics
    self.profile_entity()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/core.py", line 391, in profile_entity
    column_metrics = self._prepare_column_metrics()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/core.py", line 342, in _prepare_column_metrics
    for column in self.columns
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/core.py", line 153, in columns
    for column in self._columns or self.profiler_interface.get_columns()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/interfaces/datalake/datalake_profiler_interface.py", line 322, in get_columns
    return ColumnBaseModel.col_base_model_list(self.data_frame_list)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/column_base_model.py", line 36, in col_base_model_list
    for column in data_frame_list[0].columns
TypeError: 'NoneType' object is not subscriptable
`

**Comment by harshach** [comment]
@SuperNascher thanks for the PR. Does that handle 2 issues pointed out @sapcode

**Comment by pmbrull** [comment]
thanks for the catch! @SuperNascher we would definitely appreciate a PR with these changes 🎉 Thanks

**Comment by SuperNascher** [comment]
Yes :-)

The problem was that the "Datalake source" works on JSON files but not on parquet files because the endpoint (and the region) was not given to the S3FileStorage object.
