### ISSUE TITLE
Bug: TestConnection ErrorMessage- None is not allowed

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#10975]
When running a workflow, if the error message goes in as None ( edge case - might trigger if you are on recent main ) it fails the workflow.

**Comment by ayush-shah** [comment]
Here is the traceback that was faced by me:

        2023-04-10 14:15:27] DEBUG    {metadata.Metadata:ingest:41} - Traceback (most recent call last):
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/cli/ingest.py", line 38, in run_ingest
            workflow = Workflow.create(config_dict)
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/api/workflow.py", line 185, in create
            return cls(config)
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/api/workflow.py", line 125, in __init__
            self.source: Source = source_class.create(
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/source/database/trino/metadata.py", line 189, in create
            return cls(config, metadata_config)
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/source/database/common_db_source.py", line 108, in __init__
            self.test_connection()
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/source/database/database_service.py", line 482, in test_connection
            test_connection_fn(self.metadata, self.connection_obj, self.service_connection)
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/source/database/trino/connection.py", line 98, in test_connection
            test_connection_db_schema_sources(
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/connections/test_connections.py", line 376, in test_connection_db_schema_sources
            test_connection_steps(
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/connections/test_connections.py", line 247, in test_connection_steps
            steps = [
          File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/connections/test_connections.py", line 248, in <listcomp>
            TestConnectionStep(
          File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
        pydantic.error_wrappers.ValidationError: 1 validation error for TestConnectionStep
        error_message
          none is not an allowed value (type=type_error.none.not_allowed)
        
        [2023-04-10 14:15:27] INFO     {metadata.Utils:logger:174} - 
        Error initializing INGEST: 1 validation error for TestConnectionStep
        error_message
          none is not an allowed value (type=type_error.none.not_allowed)
        [2023-04-10 14:15:27] INFO     {metadata.Utils:logger:174} -
