### ISSUE TITLE
redshift-usage ingestion does not limit query length 

### ISSUE THREAD

**Issue by Densol92** [open-metadata/OpenMetadata#1114]
Hello, I've tried to setup "redshift-uage" with following config:
```{
  "source": {
    "type": "redshift-usage",
    "config": {
      "host_port": "***.redshift.amazonaws.com:5439",
      "username": "***",
      "password": "***",
      "database": "***",
      "where_clause": "and q.label != 'metrics' and q.label != 'health' and q.label != 'cmstats'",
      "service_name": "aws_redshift",
      "duration": 2
    }
  },
  "sink": {
    "type": "elasticsearch",
    "config": {
      "index_tables": "true",
      "index_topics": "true",
      "index_dashboards": "true",
      "es_host": "localhost",
      "es_port": 9200
    }
  },
  "metadata_server": {
    "type": "metadata-server",
    "config": {
      "api_endpoint": "http://localhost:8585/api",
      "auth_provider_type": "no-auth"
    }
  }
}
```
Airflow DAG run shows following error:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1308, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/ingestion/examples/airflow/dags/airflow_metadata_to_es.py", line 48, in metadata_ingestion_workflow
    workflow.execute()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 157, in execute
    for record in self.source.next_record():
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/redshift_usage.py", line 104, in next_record
    for row in self._get_raw_extract_iter():
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/redshift_usage.py", line 95, in _get_raw_extract_iter
    rows = self.alchemy_helper.execute_query()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/sql_alchemy_helper.py", line 57, in execute_query
    self.results = self.connection.execute(self.query)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) Result size exceeds LISTAGG limit
DETAIL:  
  -----------------------------------------------
  error:  Result size exceeds LISTAGG limit
  code:      8001
  context:   LISTAGG limit: 65535
  query:     10522813
  location:  string_ops.cpp:116
  process:   query0_869_10522813 [pid=32491]
  -----------------------------------------------


[SQL: 
        WITH query_sql AS (
                 SELECT
                    query,
                    LISTAGG(text) WITHIN GROUP (ORDER BY sequence) AS sql
                FROM stl_querytext 
                GROUP BY 1
        )

        SELECT
            q.query,  q.label, userid,  xid,  pid,  starttime,  endtime,
            DATEDIFF(milliseconds, starttime, endtime) AS duration,
            TRIM(database) AS database,
            '2021-11-07 00:00:00' as analysis_date,
            (CASE aborted WHEN 1 THEN TRUE ELSE FALSE END) AS aborted,
        sql
        FROM
            stl_query q JOIN query_sql qs ON (q.query = qs.query)
        WHERE
        endtime between '2021-11-07 00:00:00' and '2021-11-12 00:00:00'
        and q.label != 'metrics' and q.label != 'health' and q.label != 'cmstats'
        ORDER BY starttime;
        ]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

Reason for this is large a queries, over 290Kb  long.  

As I understood, it completely blocks redshift-uage ingestions for me.

**Comment by harshach** [comment]
@Densol92 thanks for giving it a try. We made the query simpler to not use LISTAGG https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/source/redshift_usage.py#L35
@ayush-shah can you publish dev python package. So that @Densol92 can try with new changes.

**Comment by ayush-shah** [comment]
Hey @Densol92, created a new dev package

`pip install 'openmetadata-ingestion[redshift-usage]==0.4.0.dev6'`

The above command will install all the dependencies related to redshift-usage with the latest changes onto your system.

**Comment by harshach** [comment]
@Densol92 if you tried it again please let us know if this issue is fixed for you. Appreciate any feedback here. Thanks
