### ISSUE TITLE
make generate issue

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#1119]
Working on https://github.com/open-metadata/OpenMetadata/issues/1099 we've found the following error:

```
> make generate
datamodel-codegen  --input catalog-rest-service/src/main/resources/json  --input-file-type jsonschema --output ingestion/src/metadata/generated
/Users/p.brull/projects/OpenMetadata/venv/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py:397: UserWarning: format of 'timezone' not understood for 'string' - using default
  warn(
Traceback (most recent call last):
  File "pydantic/main.py", line 574, in pydantic.main.BaseModel.parse_obj
TypeError: 'bool' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/p.brull/projects/OpenMetadata/venv/lib/python3.9/site-packages/datamodel_code_generator/__main__.py", line 495, in main
    generate(
  File "/Users/p.brull/projects/OpenMetadata/venv/lib/python3.9/site-packages/datamodel_code_generator/__init__.py", line 353, in generate
    results = parser.parse()
  File "/Users/p.brull/projects/OpenMetadata/venv/lib/python3.9/site-packages/datamodel_code_generator/parser/base.py", line 426, in parse
    self.parse_raw()
  File "/Users/p.brull/projects/OpenMetadata/venv/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1177, in parse_raw
    self._parse_file(self.raw_obj, obj_name, path_parts)
  File "/Users/p.brull/projects/OpenMetadata/venv/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1242, in _parse_file
    obj = JsonSchemaObject.parse_obj(model)
  File "pydantic/main.py", line 577, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for JsonSchemaObject
__root__
  JsonSchemaObject expected dict not bool (type=type_error)

make: *** [generate] Error 1
```

We need to review the root cause of this and fix it in order to be able to regenerate the pydantic models.

**Comment by pmbrull** [comment]
Breakdown of the different issues and where they are generated:
- `type/basic.json`; `sqlQuery`; `UserWarning: format of 'utc-millisec' not understood for 'string' - using default`
- `teams/createUser.json`; `UserWarning: format of 'timezone' not understood for 'string' - using default`
- `entity/data/table.json`; `tableConstraint`; `TypeError: 'bool' object is not iterable`
