### ISSUE TITLE
Quckstart - Local Deployment Bug in `metadata docker --help`

### ISSUE THREAD

**Issue by TheDarkTrumpet** [open-metadata/OpenMetadata#11434]
**Affected module**
Quickstart mostly

**Describe the bug**
Following the instructions on https://docs.open-metadata.org/v1.0.0/quick-start/local-deployment, the `metadata` command doesn't work and errors out.  Unsure specifically the root cause yet (still looking into it on this end, too)

**To Reproduce**

Visit https://docs.open-metadata.org/v1.0.0/quick-start/local-deployment

Follow steps in **Procedure** 1-6.  This errors out on part 6.

Please see the "Additional context" section below for stack trace and library versions installed.

**Expected behavior**

The ability to run through the entire guide.

**Version:**
 - OS: [e.g. iOS] Mac OSX 13.3.1 (a)
 - Python version: 3.11.3
 - OpenMetadata version: [e.g. 0.8]
   - N/A
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]
   - Ran `pip3 install --upgrade "openmetadata-ingestion[docker]"`, resulted in version `1.0.0.1` of `openmetadata_ingestion`

**Additional context**

The specific stack trace I'm getting is:

```
❯ metadata docker --help
Traceback (most recent call last):
  File "/Users/user/programming/work/labs/open-metadata/env/bin/metadata", line 5, in <module>
    from metadata.cmd import metadata
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/cmd.py", line 21, in <module>
    from metadata.cli.backup import UploadDestinationType, run_backup
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/cli/backup.py", line 22, in <module>
    from metadata.cli.utils import get_engine
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/cli/utils.py", line 18, in <module>
    from metadata.generated.schema.entity.services.connections.database.mysqlConnection import (
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/generated/schema/entity/services/connections/database/mysqlConnection.py", line 12, in <module>
    from metadata.ingestion.models.custom_pydantic import CustomSecretStr
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/ingestion/models/custom_pydantic.py", line 22, in <module>
    from metadata.utils.logger import ingestion_logger
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/utils/logger.py", line 20, in <module>
    from metadata.generated.schema.api.lineage.addLineage import AddLineageRequest
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/generated/schema/api/lineage/addLineage.py", line 11, in <module>
    from ...type import basic, entityLineage
  File "/Users/user/programming/work/labs/open-metadata/env/lib/python3.11/site-packages/metadata/generated/schema/type/basic.py", line 96, in <module>
    class EntityLink(BaseModel):
  File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    raise TypeError("Cannot subclass special typing classes")
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 366, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 864, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "pydantic/types.py", line 463, in pydantic.types.constr
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1
```

Other versions, noting here:
- **pydantic** at `1.10.7`

**Comment by TheDarkTrumpet** [comment]
Good morning ulixiux9.  It may be a good idea to update the quickstart guide (https://docs.open-metadata.org/v1.0.0/quick-start/local-deployment) to mention the limitation on Python.  Right now, it says "version 3.7 or greater"

![image](https://user-images.githubusercontent.com/92734/236796029-cd1ccf25-5120-499c-a7c8-ff630cd1cbe0.png)
