### ISSUE TITLE
1.0.0 - Elasticsearch Re-index with language other than EN will make error appears

### ISSUE THREAD

**Issue by cyclonstep** [open-metadata/OpenMetadata#11543]
**Affected module**
UI, Search and Maybe the Elasticsearch service that OM used. 

**Describe the bug**
Whenever I tried to reindex after adding glossaries with  languages other than EN (because I work in JP environment), this error appears.
The error:

`ailed while updating ES. Reason[Elasticsearch exception [type=index_not_found_exception, reason=no such index [glossary_search_index]]], Cause[null], Stack [[glossary_search_index] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [glossary_search_index]]]
at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1624)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1594)
at org.elasticsearch.client.RestHighLevelClient.deleteByQuery(RestHighLevelClient.java:670)
at org.openmetadata.service.elasticsearch.ElasticSearchEventPublisher.deleteEntityFromElasticSearchByQuery(ElasticSearchEventPublisher.java:877)
at org.openmetadata.service.elasticsearch.ElasticSearchEventPublisher.updateGlossary(ElasticSearchEventPublisher.java:543)
at org.openmetadata.service.elasticsearch.ElasticSearchEventPublisher.publish(ElasticSearchEventPublisher.java:159)
at org.openmetadata.service.events.AbstractEventPublisher.onEvent(AbstractEventPublisher.java:41)
at org.openmetadata.service.events.AbstractEventPublisher.onEvent(AbstractEventPublisher.java:10)
at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://internal-dc-s-2023042506015862650000000c-881446515.ap-northeast-1.elb.amazonaws.com:80]/, URI [/glossary_search_index/_delete_by_query?slices=1&requests_per_second=-1&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&refresh=true&wait_for_completion=true&timeout=1m], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [glossary_search_index]","resource.type":"index_or_alias","resource.id":"glossary_search_index","index_uuid":"na","index":"glossary_search_index"}],"type":"index_not_found_exception","reason":"no such index [glossary_search_index]","resource.type":"index_or_alias","resource.id":"glossary_search_index","index_uuid":"na","index":"glossary_search_index"},"status":404}
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)`

seems like there is a problem with the glossary. 
The after effects of this error, all of the search data cannot be accessed and everytime we got the explore page or other pages, the error (screenshot below) will be triggered.

**To Reproduce**
1. Add glossary to the system.
2. Reindex the elasticsearch with JP or ZH.

Screenshots or steps to reproduce
![Screenshot 2023-05-11 at 13 34 06](https://github.com/open-metadata/OpenMetadata/assets/6695152/ebc16b37-eca3-4a1e-ad07-82125dd6607b)

**Expected behavior**
There should be no error and the data can still be seen and searched.

**Version:**
 - OpenMetadata version: 1.0.0 using Docker images.

**Comment by harshach** [comment]
@cyclonstep thanks for reporting this. Did you install the required plugin for JP in elasticsearch

**Comment by cyclonstep** [comment]
Hello, thank you very much for replying!
seems like I haven't found anything about requiring to install JP plugin in OM documentations. Also, when I read the discussions at slack, seems like there is no need to install the plugin. 🤔
