### ISSUE TITLE
Mapping Nested Sample Data doesn't work in Avro Datalake

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#11638]
while profiling and ingesting sample for avro, sample data throws out an error

Affects Profiler module by throwing this error / traceback:

          
          | Sink   | test_datalake.default.test-om-bucket."konbert-export-cf45aef457c44.avro" | Failed to sink profiler & test data for test_datalake.default.test-om-bucket."konbert-export-cf45aef457c44.avro": Invalid column name nested | Traceback (most recent call last):                                                                                                                          |
          |        |                                                                          |                                                                                                                                              |   File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/ometa/client.py", line 221, in _one_request                             |
          |        |                                                                          |                                                                                                                                              |     resp.raise_for_status()                                                                                                                                 |
          |        |                                                                          |                                                                                                                                              |   File "/Users/ayushshah/Desktop/Code/OpenMetadata/env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status                      |
          |        |                                                                          |                                                                                                                                              |     raise HTTPError(http_error_msg, response=self)                                                                                                          |
          |        |                                                                          |                                                                                                                                              | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8585/api/v1/tables/c045cd3f-5eab-4f77-9749-e84330cc8785/tableProfile |
          |        |                                                                          |                                                                                                                                              |                                                                                                                                                             |
          |        |                                                                          |                                                                                                                                              | The above exception was the direct cause of the following exception:                                                                                        |
          |        |                                                                          |                                                                                                                                              |                                                                                                                                                             |
          |        |                                                                          |                                                                                                                                              | Traceback (most recent call last):                                                                                                                          |
          |        |                                                                          |                                                                                                                                              |   File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/profiler/sink/metadata_rest.py", line 87, in write_record                         |
          |        |                                                                          |                                                                                                                                              |     self.metadata.ingest_profile_data(                                                                                                                      |
          |        |                                                                          |                                                                                                                                              |   File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/ometa/mixins/table_mixin.py", line 136, in ingest_profile_data          |
          |        |                                                                          |                                                                                                                                              |     resp = self.client.put(                                                                                                                                 |
          |        |                                                                          |                                                                                                                                              |   File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/ometa/client.py", line 294, in put                                      |
          |        |                                                                          |                                                                                                                                              |     return self._request("PUT", path, data)                                                                                                                 |
          |        |                                                                          |                                                                                                                                              |   File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/ometa/client.py", line 198, in _request                                 |
          |        |                                                                          |                                                                                                                                              |     return self._one_request(method, url, opts, retry)                                                                                                      |
          |        |                                                                          |                                                                                                                                              |   File "/Users/ayushshah/Desktop/Code/OpenMetadata/ingestion/src/metadata/ingestion/ometa/client.py", line 229, in _one_request                             |
          |        |                                                                          |                                                                                                                                              |     raise APIError(error, http_error) from http_error                                                                                                       |
          |        |                                                                          |                                                                                                                                              | metadata.ingestion.ometa.client.APIError: Invalid column name nested                                                                                        |

**Comment by ayush-shah** [comment]
This is resolved from #11639, columns not getting ingested json, which calls for another issue.
