### ISSUE TITLE
Failure to connect to kafka & schema registry

### ISSUE THREAD

**Issue by jan-pieter** [open-metadata/OpenMetadata#11728]
**Affected module**
Ingestion

**Describe the bug**
When testing the connection while trying to ingest from kafka and a schema registry I get the following error:
```
test-connection-Kafka-qk0v3omC Failed to trigger workflow due to airflow API returned Internal Server Error and response {"error": "Error running automation workflow due to ['CustomSecretStr' object has no attribute 'split'] "}
```

**To Reproduce**
Add a new kafka service with the following values:

![image](https://github.com/open-metadata/OpenMetadata/assets/1197006/66ff7a04-0cac-4d06-9d44-7a422dfb5eaf)

After pressing `Test Connection` I get the following error:

![image](https://github.com/open-metadata/OpenMetadata/assets/1197006/cf55666d-5657-453e-a279-ae34839dbc0e)

**Expected behavior**
The connection should work without error.

**Version:**
 - OS: Linux (airflow docker image in the helm chart)
 - Python version: 3.9.13 (from the airflow docker image in the helm chart)
 - OpenMetadata version: 1.0.1
 - OpenMetadata Ingestion package version: 1.0.1.3

**Additional context**
The error message mentions an issue with splitting a secret so I presume this is an issue with the credentials of the schema registry (which is in the form `username:password`). My passwords do not contain any characters which need escaping.

When using version 0.13 my connection was working properly, but the passwords were supplied in the `Consumer Config` & `Schema Registry Config` and where thus not masked in the UI.

**Comment by jan-pieter** [comment]
Full stack trace:
```
airflow-web [2023-05-23 12:36:45,089] {run_automation.py:91} DEBUG - Traceback (most recent call last):                                                                                    │
│ airflow-web   File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/api/routes/run_automation.py", line 72, in run_automation                                   │
│ airflow-web     execute(automation_workflow)                                                                                                                                               │
│ airflow-web   File "/home/airflow/.local/lib/python3.9/site-packages/metadata/automations/runner.py", line 32, in execute                                                                  │
│ airflow-web     return run_workflow(automation_workflow.request, automation_workflow)                                                                                                      │
│ airflow-web   File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper                                                                                                           │
│ airflow-web     return dispatch(args[0].__class__)(*args, **kw)                                                                                                                            │
│ airflow-web   File "/home/airflow/.local/lib/python3.9/site-packages/metadata/automations/runner.py", line 50, in _                                                                        │
│ airflow-web     connection = get_connection(request.connection.config)                                                                                                                     │
│ airflow-web   File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/connections.py", line 49, in get_connection                                                 │
│ airflow-web     return get_connection_fn(connection)(connection)                                                                                                                           │
│ airflow-web   File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/messaging/kafka/connection.py", line 77, in get_connection                                  │
│ airflow-web     schema_registry_client = SchemaRegistryClient(connection.schemaRegistryConfig)                                                                                             │
│ airflow-web   File "/home/airflow/.local/lib/python3.9/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 292, in __init__                                     │
│ airflow-web     self._rest_client = _RestClient(conf)                                                                                                                                      │
│ airflow-web   File "/home/airflow/.local/lib/python3.9/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 107, in __init__                                     │
│ airflow-web     userinfo = tuple(conf_copy.pop('basic.auth.user.info', '').split(':'))                                                                                                     │
│ airflow-web AttributeError: 'CustomSecretStr' object has no attribute 'split'                                       
```
