### ISSUE TITLE
NullPointerException setting status on custom pipeline entity

### ISSUE THREAD

**Issue by cutz** [open-metadata/OpenMetadata#11820]
**Affected module**
Pipeline status

**Describe the bug**
I have a custom pipeline entity (serviceType = "CustomPipeline") with a single task that I am trying to set the status of via the `/api/v1/pipelines/{fqn}/status api`. I'm sending the following json:

```json
{
    "taskStatus": [
        {
            "executionStatus": "Pending",
            "name": "step1"
        }
    ]
}
```

An HTTP 500 is returned and the following stack trace is observed in the server logs:

```
2023-05-30 18:45:18 ERROR [2023-05-30 23:45:18,270] [dw-388 - PUT /api/v1/pipelines/MyCustomPipelineService.MyTestPipeline/status] o.o.s.r.p.PipelineResource - Got exception: [NullPointerException] / message [null] / related resource location: [org.openmetadata.service.resources.pipelines.PipelineResource.addPipelineStatus](PipelineResource.java:357)
2023-05-30 18:45:18 java.lang.NullPointerException: null
2023-05-30 18:45:18     at org.openmetadata.service.jdbi3.PipelineRepository.addPipelineStatus(PipelineRepository.java:105)
2023-05-30 18:45:18     at org.openmetadata.service.resources.pipelines.PipelineResource.addPipelineStatus(PipelineResource.java:357)
<snip>
```

**To Reproduce**

1. Create a custom pipeline service via the API.

```bash
POST /api/v1/services/pipelineServices HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer <redacted>
Connection: keep-alive
Content-Length: 98
Content-Type: application/json
Host: localhost:8585
User-Agent: HTTPie/3.2.1

{
    "connection": {
        "config": {}
    },
    "name": "MyCustomPipelineService",
    "serviceType": "CustomPipeline"
}


HTTP/1.1 201 Created
Content-Length: 391
Content-Type: application/json
Date: Tue, 30 May 2023 23:39:21 GMT
Location: http://localhost:8585/api/v1/services/pipelineServices/60790f2c-4355-406e-b878-1de43a74ebe5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

{
    "connection": {
        "config": {
            "type": "CustomPipeline"
        }
    },
    "deleted": false,
    "fullyQualifiedName": "MyCustomPipelineService",
    "href": "http://localhost:8585/api/v1/services/pipelineServices/60790f2c-4355-406e-b878-1de43a74ebe5",
    "id": "60790f2c-4355-406e-b878-1de43a74ebe5",
    "name": "MyCustomPipelineService",
    "serviceType": "CustomPipeline",
    "updatedAt": 1685489961118,
    "updatedBy": "ingestion-bot",
    "version": 0.1
}

```

2. Create a new pipeline with a single task based on that service:

```bash
POST /api/v1/pipelines HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer <redacted>
Connection: keep-alive
Content-Length: 94
Content-Type: application/json
Host: localhost:8585
User-Agent: HTTPie/3.2.1

{
    "name": "MyTestPipeline",
    "service": "MyCustomPipelineService",
    "tasks": [
        {
            "name": "step1"
        }
    ]
}


HTTP/1.1 201 Created
Content-Length: 704
Content-Type: application/json
Date: Tue, 30 May 2023 23:42:45 GMT
Location: http://localhost:8585/api/v1/pipelines/3f0e9411-c53d-4ef7-af01-da2f46d6fb36
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

{
    "deleted": false,
    "fullyQualifiedName": "MyCustomPipelineService.MyTestPipeline",
    "href": "http://localhost:8585/api/v1/pipelines/3f0e9411-c53d-4ef7-af01-da2f46d6fb36",
    "id": "3f0e9411-c53d-4ef7-af01-da2f46d6fb36",
    "name": "MyTestPipeline",
    "service": {
        "deleted": false,
        "fullyQualifiedName": "MyCustomPipelineService",
        "href": "http://localhost:8585/api/v1/services/pipelineServices/60790f2c-4355-406e-b878-1de43a74ebe5",
        "id": "60790f2c-4355-406e-b878-1de43a74ebe5",
        "name": "MyCustomPipelineService",
        "type": "pipelineService"
    },
    "serviceType": "CustomPipeline",
    "tasks": [
        {
            "fullyQualifiedName": "MyCustomPipelineService.MyTestPipeline.step1",
            "name": "step1"
        }
    ],
    "updatedAt": 1685490165534,
    "updatedBy": "ingestion-bot",
    "version": 0.1
}
```

3. Attempt to set the status for the task with name `step1`. Observe the API call returns a 500 and the NullPointerException in the logs.

```bash
PUT /api/v1/pipelines/MyCustomPipelineService.MyTestPipeline/status HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer <redacted>
Connection: keep-alive
Content-Length: 65
Content-Type: application/json
Host: localhost:8585
User-Agent: HTTPie/3.2.1

{
    "taskStatus": [
        {
            "executionStatus": "Pending",
            "name": "step1"
        }
    ]
}


HTTP/1.1 500 Internal Server Error
Content-Length: 91
Content-Type: application/json
Date: Tue, 30 May 2023 23:45:18 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

{
    "responseMessage": "An exception with message [null] was thrown while processing request."
}

```

Full stack trace

```
2023-05-30 18:45:18 ERROR [2023-05-30 23:45:18,270] [dw-388 - PUT /api/v1/pipelines/MyCustomPipelineService.MyTestPipeline/status] o.o.s.r.p.PipelineResource - Got exception: [NullPointerException] / message [null] / related resource location: [org.openmetadata.service.resources.pipelines.PipelineResource.addPipelineStatus](PipelineResource.java:357)
2023-05-30 18:45:18 java.lang.NullPointerException: null
2023-05-30 18:45:18     at org.openmetadata.service.jdbi3.PipelineRepository.addPipelineStatus(PipelineRepository.java:105)
2023-05-30 18:45:18     at org.openmetadata.service.resources.pipelines.PipelineResource.addPipelineStatus(PipelineResource.java:357)
2023-05-30 18:45:18     at jdk.internal.reflect.GeneratedMethodAccessor539.invoke(Unknown Source)
2023-05-30 18:45:18     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-30 18:45:18     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
2023-05-30 18:45:18     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
2023-05-30 18:45:18     at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
2023-05-30 18:45:18     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
2023-05-30 18:45:18     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
2023-05-30 18:45:18     at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
2023-05-30 18:45:18     at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
2023-05-30 18:45:18     at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
2023-05-30 18:45:18     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
2023-05-30 18:45:18     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
2023-05-30 18:45:18     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
2023-05-30 18:45:18     at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
2023-05-30 18:45:18     at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
2023-05-30 18:45:18     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
2023-05-30 18:45:18     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
2023-05-30 18:45:18     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
2023-05-30 18:45:18     at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
2023-05-30 18:45:18     at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
2023-05-30 18:45:18     at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
2023-05-30 18:45:18     at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
2023-05-30 18:45:18     at org.eclipse.jetty.servlets.HeaderFilter.doFilter(HeaderFilter.java:117)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
2023-05-30 18:45:18     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
2023-05-30 18:45:18     at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:315)
2023-05-30 18:45:18     at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
2023-05-30 18:45:18     at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
2023-05-30 18:45:18     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
2023-05-30 18:45:18     at org.eclipse.jetty.server.Server.handle(Server.java:516)
2023-05-30 18:45:18     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
2023-05-30 18:45:18     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
2023-05-30 18:45:18     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
2023-05-30 18:45:18     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
2023-05-30 18:45:18     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
2023-05-30 18:45:18     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
2023-05-30 18:45:18     at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
2023-05-30 18:45:18     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
2023-05-30 18:45:18     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
2023-05-30 18:45:18     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
2023-05-30 18:45:18     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
2023-05-30 18:45:18     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
2023-05-30 18:45:18     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
2023-05-30 18:45:18     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
2023-05-30 18:45:18     at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected behavior**

The call to set the status should not return a 500.

**Version:**
OpenMetadata version 1.0.2 running in docker as documented in the [Quickstart guide](https://docs.open-metadata.org/v1.0.0/quick-start/local-deployment)

**Comment by harshach** [comment]
@cutz thanks for the details in the bug report.
however, the payload for adding status should be of the following format
```{
"timestamp":epoch,
 "status": "running",
"taskStatus": [
        {
            "executionStatus": "Pending",
            "name": "step1",
             "timestamp": epoch
        }
    ]
}```

We added requirements to these fields so that error is more clear on the client side. But the above payload will work in the current and previous releases
