### ISSUE TITLE
For OM 1.0.4 and Dagster 1.3.9 the dagster integration is broken

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#11987]
For OM 1.0.4 and Dagster 1.3.9 the dagster integration is broken:

```
metadata ingest -c recipe_dagster.yml
[2023-06-14 14:47:37] INFO     {metadata.Ingestion:workflow:115} - Service type:ServiceType.Pipeline,dagster configured
/metadata/ingestion/source/pipeline/dagster/connection.py:37: ExperimentalWarning: "DagsterGraphQLClient" is an experimental class. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
  dagster_connection = DagsterGraphQLClient(
Traceback (most recent call last):
  File "/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/metadata/cmd.py", line 409, in metadata
    run_ingest(config_path=config_file)
  File "/metadata/cli/ingest.py", line 45, in run_ingest
    workflow.execute()
  File "/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/metadata/ingestion/api/workflow.py", line 196, in execute
    for record in self.source.next_record():
  File "/metadata/ingestion/api/topology_runner.py", line 132, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/metadata/ingestion/api/topology_runner.py", line 80, in process_nodes
    for entity_request in stage_fn(element) or []:
  File "/metadata/ingestion/source/pipeline/pipeline_service.py", line 212, in yield_create_request_pipeline_service
    yield self.metadata.get_create_service_from_source(
  File "/metadata/ingestion/ometa/mixins/service_mixin.py", line 48, in get_create_service_from_source
    return create_entity_class(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CreatePipelineServiceRequest
name -> __root__
  string does not match regex "^(?u)[\w\'\- .&()]+$" (type=value_error.str.regex; pattern=^(?u)[\w\'\- .&()]+$)

```

**Comment by geoHeil** [comment]
https://openmetadata.slack.com/archives/C02B6955S4S/p1686746236123469

**Comment by geoHeil** [comment]
my bad - I overlooked the 401

**Comment by geoHeil** [comment]
I am also observing:

```

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "dagster_meta_lineage"::

TypeError: type NoneType doesn't define __round__ method

Stack Trace:
  File "/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/dagster/_utils/__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
  File "/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/opt/dagster/dagster_home/src/MWF/assets/meta_governance/ops/open_metadata.py", line 172, in dagster_meta_lineage
    om_workflow_factory(context, workflow_config, is_profiler=False)
  File "/opt/dagster/dagster_home/src/MWF/assets/meta_governance/ops/open_metadata.py", line 87, in om_workflow_factory
    workflow.execute()
  File "/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/metadata/ingestion/api/workflow.py", line 196, in execute
    for record in self.source.next_record():
  File "/metadata/ingestion/api/topology_runner.py", line 132, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/metadata/ingestion/api/topology_runner.py", line 98, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/metadata/ingestion/api/topology_runner.py", line 80, in process_nodes
    for entity_request in stage_fn(element) or []:
  File "/metadata/ingestion/source/pipeline/dagster/metadata.py", line 205, in yield_pipeline_status
    endTime=round(run["endTime"]),
```

**Comment by geoHeil** [comment]
The first stacktrace was when using a recent 1.3.x version of dagster (but not the latest client binary). The last one (2nd one) is the result for the confirmed latest binaries

**Comment by OnkarVO7** [comment]
@geoHeil for the 1st error here what is the service name that you have defined in your yaml file?

> For OM 1.0.4 and Dagster 1.3.9 the dagster integration is broken:
> 
> ```
> metadata ingest -c recipe_dagster.yml
> [2023-06-14 14:47:37] INFO     {metadata.Ingestion:workflow:115} - Service type:ServiceType.Pipeline,dagster configured
> /metadata/ingestion/source/pipeline/dagster/connection.py:37: ExperimentalWarning: "DagsterGraphQLClient" is an experimental class. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
>   dagster_connection = DagsterGraphQLClient(
> Traceback (most recent call last):
>   File "/bin/metadata", line 8, in <module>
>     sys.exit(metadata())
>   File "/metadata/cmd.py", line 409, in metadata
>     run_ingest(config_path=config_file)
>   File "/metadata/cli/ingest.py", line 45, in run_ingest
>     workflow.execute()
>   File "/metadata/ingestion/api/workflow.py", line 215, in execute
>     raise err
>   File "/metadata/ingestion/api/workflow.py", line 196, in execute
>     for record in self.source.next_record():
>   File "/metadata/ingestion/api/topology_runner.py", line 132, in next_record
>     yield from self.process_nodes(get_topology_root(self.topology))
>   File "/metadata/ingestion/api/topology_runner.py", line 80, in process_nodes
>     for entity_request in stage_fn(element) or []:
>   File "/metadata/ingestion/source/pipeline/pipeline_service.py", line 212, in yield_create_request_pipeline_service
>     yield self.metadata.get_create_service_from_source(
>   File "/metadata/ingestion/ometa/mixins/service_mixin.py", line 48, in get_create_service_from_source
>     return create_entity_class(
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for CreatePipelineServiceRequest
> name -> __root__
>   string does not match regex "^(?u)[\w\'\- .&()]+$" (type=value_error.str.regex; pattern=^(?u)[\w\'\- .&()]+$)
> ```

**Comment by mudravrik** [comment]
Hi folks! Coming from Slack [discussion](https://openmetadata.slack.com/archives/C02B6955S4S/p1686875417419049) with another error.

I'm trying to setup connection between Dagster and OM.
We are running Dagster Cloud 1.3.10
OM is 1.0.4 run in Docker in GCP.
Connectivity test passes just fine, but ingestion itself fails with following error:
`[2023-06-16 00:21:56,601] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 228, in metadata_ingestion_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 196, in execute
    for record in self.source.next_record():
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 132, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 98, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 80, in process_nodes
    for entity_request in stage_fn(element) or []:
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/dagster/metadata.py", line 114, in yield_pipeline
    for job in jobs["solidHandles"]:
KeyError: 'solidHandles'`

**Comment by geoHeil** [comment]
@OnkarVO7 `dagster_source_prod`
