### ISSUE TITLE
Client SDK SearchApi cannot deserialize response fields into TimeValue model

### ISSUE THREAD

**Issue by jrasband9** [open-metadata/OpenMetadata#11990]
**Affected module**
Java Client SDK 

**Describe the bug**
Running SearchApi.searchEntitiesWithQuery() results in an exception regardless of inputs. It appears the SDK gets a response from the server, but is unable to construct instances of org.openmetadata.client.model.TimeValue from the response body.

`Exception in thread "main" feign.FeignException: Cannot construct instance of `org.openmetadata.client.model.TimeValue` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (10)
 at [Source: (BufferedReader); line: 1, column: 9] (through reference chain: org.openmetadata.client.model.SearchResponse["took"]) reading GET https://sandbox.open-metadata.org/api/v1/search/query?q=Music
	at feign.FeignException.errorReading(FeignException.java:167)
	at feign.InvocationContext.proceed(InvocationContext.java:42)
	at feign.ResponseHandler.decode(ResponseHandler.java:122)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:73)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:96)
	at com.sun.proxy.$Proxy79.searchEntitiesWithQuery(Unknown Source)
	at com.example.demoom.DemoOmApplication.main(DemoOmApplication.java:67)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.openmetadata.client.model.TimeValue` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (10)
 at [Source: (BufferedReader); line: 1, column: 9] (through reference chain: org.openmetadata.client.model.SearchResponse["took"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromInt(ValueInstantiator.java:324)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:376)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1442)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3659)
	at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65)
	at feign.InvocationContext.proceed(InvocationContext.java:36)
	... 7 more`

**To Reproduce**
After integrating the Client SDK and creating an OpenMetadata instance connected to an OpenMetdata server, run the following code. The bug should occur each time.

`        SearchApi searchApi = openMetadata.buildClient(SearchApi.class);
        Map<String, Object> params = new HashMap<>();
        params.put("q", "*");
        SearchResponse response = searchApi.searchEntitiesWithQuery(params);`

**Expected behavior**
A SearchResponse object is created from the response of running the search on the OpenMetadata server through the SDK client.

**Version:**
 - OS: Windows 10
 - Java version: 11
 - OpenMetadata version: 1.0.4
 - OpenMetadata Java Client SDK version: 1.0.4

**Additional context**
This issue was discussed in a [slack thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1684849892492659) with Harsha Ch and Mohit Yadav, who suggested making the Bug issue. They suggested a workaround to use the ElasticSearchApi, but this still fails to deserialize TimeValues unless my project using the SDK creates its own custom deserializer.

**Comment by jrasband9** [comment]
@harshach , @mohityadav766 , do we have a target version/date on this bugfix?
