### ISSUE TITLE
Clickhouse profiler can't identify schema_name 

### ISSUE THREAD

**Issue by ruffury** [open-metadata/OpenMetadata#12012]
**Affected module**
Ingestion Framework

**Describe the bug**
We are using Clickhouse Profiler which is created in UI base on query_log. Workflow is successful, but we got multiple errors in debug mode and it seems like no effect in OMD.
We got these errors on every query row:
```
[2023-06-16 14:14:33,924] {usage_source.py:119} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/ingestion/source/database/usage_source.py", line 115, in yield_table_queries
    databaseSchema=self.get_schema_name(row),
  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/ingestion/source/database/clickhouse/query_parser.py", line 56, in get_schema_name
    schema_list = ast.literal_eval(data["schema_name"])
  File "/usr/local/lib/python3.8/ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "/usr/local/lib/python3.8/ast.py", line 98, in _convert
    return _convert_signed_num(node)
  File "/usr/local/lib/python3.8/ast.py", line 75, in _convert_signed_num
    return _convert_num(node)
  File "/usr/local/lib/python3.8/ast.py", line 66, in _convert_num
    _raise_malformed_node(node)
  File "/usr/local/lib/python3.8/ast.py", line 63, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: ['system']
```
At the end we have logs

```
[2023-06-16 14:14:34,094] {client.py:196} DEBUG - URL https://omd/api/v1/usage/compute.percentile/table/2023-06-16, method POST
[2023-06-16 14:14:34,094] {client.py:197} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '********'}, 'allow_redirects': False, 'verify': None}
[2023-06-16 14:14:34,176] {ometa_api.py:771} DEBUG - published compute percentile None
[2023-06-16 14:14:34,177] {client.py:196} DEBUG - URL https://omd/api/v1/usage/compute.percentile/database/2023-06-16, method POST
[2023-06-16 14:14:34,177] {client.py:197} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '********'}, 'allow_redirects': False, 'verify': None}
[2023-06-16 14:14:34,258] {ometa_api.py:771} DEBUG - published compute percentile None
[2023-06-16 14:14:34,260] {logger.py:183} INFO - [1mStatuses detailed info:[0m
[2023-06-16 14:14:34,260] {logger.py:183} INFO - [1mSource Status:[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - {'failures': [], 'filtered': [], 'records': [], 'source_start_time': 1686924822.8747423, 'success': [], 'warnings': []}[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - [1mStage Status:[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - {'failures': [], 'records': [], 'warnings': []}[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - [1mBulk Sink Status:[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - {'failures': [], 'records': [], 'warnings': []}[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - [1mProcessor Status:[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - {'failures': [], 'records': [], 'warnings': []}[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - [1mWorkflow Summary:[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - Total processed records: 0[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - Total warnings: 0[0m
[2023-06-16 14:14:34,261] {logger.py:183} INFO - Total filtered: 0[0m
[2023-06-16 14:14:34,262] {logger.py:183} INFO - Total errors: 0[0m
[2023-06-16 14:14:34,262] {logger.py:183} INFO - [1m[36;1mSuccess %: 100.0[0m
[2023-06-16 14:14:34,262] {logger.py:183} INFO - [1m[36;1mWorkflow finished in time: 51.39s[0m
[2023-06-16 14:14:34,262] {logger.py:183} INFO - [1m[32;1mWorkflow finished successfully[0m
[2023-06-16 14:14:34,262] {client.py:196} DEBUG - URL https://omd/api/v1/usage/compute.percentile/table/2023-06-16, method POST
[2023-06-16 14:14:34,262] {client.py:197} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '********'}, 'allow_redirects': False, 'verify': None}
[2023-06-16 14:14:34,355] {ometa_api.py:771} DEBUG - published compute percentile None
[2023-06-16 14:14:34,355] {client.py:196} DEBUG - URL https://omd/api/v1/usage/compute.percentile/database/2023-06-16, method POST
[2023-06-16 14:14:34,355] {client.py:197} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '********'}, 'allow_redirects': False, 'verify': None}
[2023-06-16 14:14:34,436] {ometa_api.py:771} DEBUG - published compute percentile None
```

**To Reproduce**

Clickhouse version 22.8.17.17. OMD version 1.0.2. 
Profiler ingestion
![image](https://github.com/open-metadata/OpenMetadata/assets/23666121/14bfceec-7c11-46a0-9035-6c14a85e53fb)

**Expected behavior**
I expect successful Workflow and some results on platform - at least usage percentile.

**Version:**
 - OS: linux
 - Python version: 3.9
 - OpenMetadata version: 1.0.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by TeddyCr** [comment]
@ruffury I believe this is the usage workflow. 
--
cc @ulixius9
