### ISSUE TITLE
[ES Failure] Sending invalid eventType throws off indexing 

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#12043]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Failed while updating ES. Reason[Elasticsearch exception [type=document_missing_exception, reason=[_doc][adcb18d5-7821-48d1-be73-84d7c07c27d7]: document missing]], Cause[null], Stack [[query_search_index/iZUtxFZjS76QBLKq_1e4AA][[query_search_index][4]] ElasticsearchStatusException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][adcb18d5-7821-48d1-be73-84d7c07c27d7]: document missing]]
at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1624)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1594)
at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:1061)
at org.openmetadata.service.elasticsearch.ElasticSearchEventPublisher.updateElasticSearch(ElasticSearchEventPublisher.java:861)
at org.openmetadata.service.elasticsearch.ElasticSearchEventPublisher.updateQuery(ElasticSearchEventPublisher.java:632)
at org.openmetadata.service.elasticsearch.ElasticSearchEventPublisher.publish(ElasticSearchEventPublisher.java:192)
at org.openmetadata.service.events.AbstractEventPublisher.onEvent(AbstractEventPublisher.java:41)
at org.openmetadata.service.events.AbstractEventPublisher.onEvent(AbstractEventPublisher.java:10)
at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [[https://vpc-tl-om-prod-os-sa6rsw2v65eekylfvhx3xr2pwi.us-east-1.es.amazonaws.com:443](https://vpc-tl-om-prod-os-sa6rsw2v65eekylfvhx3xr2pwi.us-east-1.es.amazonaws.com/)], URI [/query_search_index/_update/adcb18d5-7821-48d1-be73-84d7c07c27d7?timeout=1m], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"document_missing_exception","reason":"[_doc][adcb18d5-7821-48d1-be73-84d7c07c27d7]: document missing","index_uuid":"iZUtxFZjS76QBLKq_1e4AA","shard":"4","index":"query_search_index"}],"type":"document_missing_exception","reason":"[_doc][adcb18d5-7821-48d1-be73-84d7c07c27d7]: document missing","index_uuid":"iZUtxFZjS76QBLKq_1e4AA","shard":"4","index":"query_search_index"},"status":404}
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)
... 13 mor

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@07Himank we can close this right?

**Comment by 07Himank** [comment]
> @07Himank we can close this right?

Yes harsha , i didn't see this error anymore.
