### ISSUE TITLE
Ignore lineage for table not in metadata

### ISSUE THREAD

**Issue by nitisha-cb** [open-metadata/OpenMetadata#12128]
**Affected module**
Lineage 

**Describe the bug**
The tool tries to add lineage indefinitely for a table that doesn't exist in metadata (or has been deleted). Since this table is no longer present, it fails after 750 tries.

```
[2023-06-23, 01:08:23 UTC] {sql_lineage.py:353} DEBUG - Running lineage with query: INSERT INTO <tablename>
        SELECT "created_on",
               'ROLE ACCESS',
               'ROLE',
               "role",
               "granted_to",
               "grantee_name",
               NULL,
               "granted_by",
               '2023-06-22 18:00:00+00:00'
```

Additional logs:
```
[2023-06-23, 01:08:24 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 910, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002043 (02000): SQL compilation error:
Object does not exist, or operation cannot be performed.

```

**To Reproduce**
- Ignore table via ignoring schema, ingest metadata
- Run lineage

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - OpenMetadata version: 1.0.4

**Additional context**

**Comment by pmbrull** [comment]
hi @nitisha-cb I think @ulixius9 has been trying to reach out since we need more info. Please provide any extra details in the issue, thanks!

**Comment by ulixius9** [comment]
closing this ticket as no longer relevant
