### ISSUE TITLE
OpenMetaData 1.1.0 docker-compose.yml file not launching a functional app

### ISSUE THREAD

**Issue by CorsettiS** [open-metadata/OpenMetadata#12243]
**Affected module**
Docker compose yml file

**Describe the bug**

When I try to launch the openmetadata 1.1.0 sandbox locally using the tutorial provided [here](https://docs.open-metadata.org/v1.0.0/quick-start/local-deployment), the docker container of openmetadata-server fails to start. After checking the logs, I found the following: 

```
Initializing OpenMetadata Server...

Migrating the database to the latest version and the indexes in ElasticSearch...

org.openmetadata.service.exception.InvalidServiceConnectionException: InvalidServiceConnectionException for service [Airflow] due to [Failed to encrypt connection instance of Airflow].

at org.openmetadata.service.exception.InvalidServiceConnectionException.byMessage(InvalidServiceConnectionException.java:22)

at org.openmetadata.service.secrets.SecretsManager.decryptServiceConnectionConfig(SecretsManager.java:84)

at org.openmetadata.service.secrets.SecretsManagerUpdateService.updateService(SecretsManagerUpdateService.java:120)

at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

at org.openmetadata.service.secrets.SecretsManagerUpdateService.updateServices(SecretsManagerUpdateService.java:84)

at org.openmetadata.service.secrets.SecretsManagerUpdateService.updateEntities(SecretsManagerUpdateService.java:73)

at org.openmetadata.service.OpenMetadataApplication.run(OpenMetadataApplication.java:196)

at org.openmetadata.service.OpenMetadataApplication.run(OpenMetadataApplication.java:121)

at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)

at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)

at io.dropwizard.cli.Cli.run(Cli.java:78)

at io.dropwizard.Application.run(Application.java:94)

at org.openmetadata.service.OpenMetadataApplication.main(OpenMetadataApplication.java:475)

```

**To Reproduce**

1. wget https://github.com/open-metadata/OpenMetadata/releases/download/1.1.0-release/docker-compose.yml
2. docker compose up -d --build

**Expected behavior**
The server cannot be started

**Version:**
 - OpenMetadata version: 1.1.0

**Additional context**

**Comment by harshach** [comment]
@CorsettiS please do not open a ticket before asking in http://slack.open-metadata.org

**Comment by kizimenko** [comment]
same problem
