### ISSUE TITLE
Ingestion Error from Postgresql 11.19

### ISSUE THREAD

**Issue by isoctcolo** [open-metadata/OpenMetadata#12390]
**Affected module**
Profiler ingestion

**Describe the bug**
It scans over many tables then I get this error:

[2023-07-12, 11:27:37 UTC] {ingestion_pipeline_mixin.py:51} DEBUG - Created Pipeline Status for pipeline Datavault Dev Old.Datavault_Dev_Old_profiler_OoQUHSDY: {'eventType': 'entityUpdated', 'entityType': 'ingestionPipeline', 'entityId': '6a066f15-7e11-4835-a6a3-a1ce6c41624f', 'entityFullyQualifiedName': 'Datavault Dev Old.Datavault_Dev_Old_profiler_OoQUHSDY', 'previousVersion': 0.4, 'currentVersion': 0.4, 'userName': 'ingestion-bot', 'timestamp': 1689161257745, 'changeDescription': {'fieldsAdded': [], 'fieldsUpdated': [{'name': 'pipelineStatus', 'oldValue': {'runId': '1ecdb929-d7f0-4638-a498-1b65426c87e6', 'pipelineState': 'running', 'startDate': 1689160015681, 'timestamp': 1689160015681}, 'newValue': {'runId': '1ecdb929-d7f0-4638-a498-1b65426c87e6', 'pipelineState': 'failed', 'startDate': 1689160015681, 'timestamp': 1689160015681, 'endDate': 1689161257713}}], 'fieldsDeleted': [], 'previousVersion': 0.4}, 'entity': {'id': '6a066f15-7e11-4835-a6a3-a1ce6c41624f', 'name': 'Datavault_Dev_Old_profiler_OoQUHSDY', 'displayName': 'Datavault_Dev_Old_profiler_OoQUHSDY', 'pipelineType': 'profiler', 'fullyQualifiedName': 'Datavault Dev Old.Datavault_Dev_Old_profiler_OoQUHSDY', 'sourceConfig': {'config': {'type': 'Profiler', 'threadCount': 5, 'timeoutSeconds': 43200, 'profileSampleType': 'PERCENTAGE', 'generateSampleData': True, 'processPiiSensitive': False, 'schemaFilterPattern': {'excludes': ['dbo']}, 'databaseFilterPattern': {'includes': ['postgres']}}}, 'airflowConfig': {'pausePipeline': False, 'concurrency': 1, 'startDate': 1689033600000, 'pipelineTimezone': 'UTC', 'retries': 3, 'retryDelay': 300, 'pipelineCatchup': False, 'scheduleInterval': '15 * * * *', 'maxActiveRuns': 1, 'workflowDefaultView': 'tree', 'workflowDefaultViewOrientation': 'LR'}, 'loggerLevel': 'DEBUG', 'deployed': True, 'enabled': True, 'href': 'http://openmetadata-server:8585/api/v1/services/ingestionPipelines/6a066f15-7e11-4835-a6a3-a1ce6c41624f', 'version': 0.4, 'updatedAt': 1689159965032, 'updatedBy': 'geschwinde', 'changeDescription': {'fieldsAdded': [], 'fieldsUpdated': [{'name': 'deployed', 'oldValue': False, 'newValue': True}], 'fieldsDeleted': [], 'previousVersion': 0.3}, 'deleted': False, 'provider': 'user'}}
[2023-07-12, 11:27:37 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/profiler.py", line 49, in profiler_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 326, in execute
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 317, in execute
    profile = self.run_profiler(entity, profiler_source)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 269, in run_profiler
    profiler_runner: Profiler = profiler_source.get_profiler_runner(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/source/base_profiler_source.py", line 205, in get_profiler_runner
    profiler_interface = self.create_profiler_interface(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/source/base_profiler_source.py", line 185, in create_profiler_interface
    ] = ProfilerProtocol.create(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/interface/profiler_protocol.py", line 99, in create
    return cls.subclasses[_profiler_type](
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/interface/sqlalchemy/profiler_interface.py", line 103, in __init__
    self._table = self._convert_table_to_orm_object(sqa_metadata)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/mixins/sqalchemy/sqa_mixin.py", line 62, in _convert_table_to_orm_object
    return ometa_to_sqa_orm(self.table_entity, self.ometa_client, sqa_metadata_obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/orm/converter.py", line 267, in ometa_to_sqa_orm
    orm = type(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/decl_api.py", line 72, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 126, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 177, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 326, in __init__
    self._early_mapping(mapper_kw)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 209, in _early_mapping
    self.map(mapper_kw)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 1004, in map
    mapper_cls(self.cls, self.local_table, **self.mapper_args),
  File "<string>", line 2, in __init__
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 683, in __init__
    self._configure_properties()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1451, in _configure_properties
    self._configure_property(key, prop, False)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1719, in _configure_property
    prop = self._property_from_column(key, prop)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py", line 1892, in _property_from_column
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: When configuring property 'ClubRunner.StorageAccess.Collections.Classes.DateEpochDomainMod' on mapped class postgres_mnmigration_order_name->order_name, column 'order_name.ClubRunner.StorageAccess.Collections.Classes.DateEpochDomainMod' is not represented in the mapper's table. Use the `column_property()` function to force this column to be mapped as a read-only attribute.
[2023-07-12, 11:27:37 UTC] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Datavault_Dev_Old_profiler_OoQUHSDY, task_id=profiler_task, execution_date=20230712T110641, start_date=20230712T110652, end_date=20230712T112737
[2023-07-12, 11:27:37 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 44 for task profiler_task (When configuring property 'ClubRunner.StorageAccess.Collections.Classes.DateEpochDomainMod' on mapped class postgres_mnmigration_order_name->order_name, column 'order_name.ClubRunner.StorageAccess.Collections.Classes.DateEpochDomainMod' is not represented in the mapper's table. Use the `column_property()` function to force this column to be mapped as a read-only attribute.; 17964)
[2023-07-12, 11:27:37 UTC] {local_task_job.py:156} INFO - Task exited with return code 1

**To Reproduce**

I just throws the error with this table. The table has only text and float8 columns.
I have no idea what could go wrong here. 

**Expected behavior**
No error during profiling.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
Maybe this is related to issue https://github.com/open-metadata/OpenMetadata/issues/12388 - but other tables are working fine.

**Comment by ayush-shah** [comment]
@isoctcolo 
feel free to contribute for the same as we don't have many requests for the same.
Looks like 11.19 / 11.21 is near EOL support, Thanks.
Let me know if that works for you, or else will be closing the ticket in couple of days. We can reopen it if someone wants to work on it post that based on request.

**Comment by isoctcolo** [comment]
@ayush-shah please close it - you are right and 11.x is a special version for maintaining

**Comment by isoctcolo** [comment]
I close it
