### ISSUE TITLE
Athena db, lineage and useage ingestion fails on Parameter validation

### ISSUE THREAD

**Issue by WarrenWittenborn** [open-metadata/OpenMetadata#12402]
**Affected module**
Ingestion Framework

**Describe the bug**
Database service for Athena, metadata job works, lineage and usage jobs fail with: botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter QueryExecutionIds, value: 0, valid min length: 1

**To Reproduce**
Create database service for Athena.  Leave the 
 Create and run metadata job - successful. Create lineage and usage jobs using default values.  Run lineage and usage jobs:  see failure.  see this error in the log: botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter QueryExecutionIds, value: 0, valid min length: 1

<img width="484" alt="Screenshot 2023-07-12 at 1 21 49 PM" src="https://github.com/open-metadata/OpenMetadata/assets/137526677/92aa1a2a-d6a9-42ed-8ebf-ef675a44780c">

[2023-07-12 18:07:37,719] {standard_task_runner.py:80} INFO - Job 305: Subtask usage_task
[2023-07-12 18:07:37,792] {task_command.py:371} INFO - Running <TaskInstance: DecisionSupportServiceSandbox_usage.usage_task manual__2023-07-12T18:07:34+00:00 [running]> on host f7fb12ac8bdf
[2023-07-12 18:07:37,836] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-07-12 18:07:37,842] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=DecisionSupportServiceSandbox_usage
AIRFLOW_CTX_TASK_ID=usage_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-12T18:07:34+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-12T18:07:34+00:00
[2023-07-12 18:07:37,882] {workflow.py:115} INFO - Service type:ServiceType.Database,athena-usage configured
[2023-07-12 18:07:37,912] {aws_client.py:146} INFO - Getting AWS client for service [athena]
[2023-07-12 18:07:38,158] {table_usage.py:81} INFO - Creating the directory to store staging data in /tmp/query_log
[2023-07-12 18:07:38,161] {workflow.py:168} INFO - BulkSink type:metadata-usage,<class 'metadata.ingestion.bulksink.metadata_usage.MetadataUsageBulkSink'> configured
[2023-07-12 18:07:38,572] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 221, in metadata_ingestion_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 196, in execute
    for record in self.source.next_record():
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/usage_source.py", line 129, in next_record
    for table_queries in self.get_table_query():
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/usage_source.py", line 79, in get_table_query
    yield from self.yield_table_queries()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/athena/usage.py", line 39, in yield_table_queries
    for query_list in self.get_queries() or []:
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/athena/query_parser.py", line 72, in get_queries
    query_details_response = self.client.batch_get_query_execution(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 878, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 939, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter QueryExecutionIds, value: 0, valid min length: 1
[2023-07-12 18:07:38,579] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=DecisionSupportServiceSandbox_usage, task_id=usage_task, execution_date=20230712T180734, start_date=20230712T180737, end_date=20230712T180738
[2023-07-12 18:07:38,587] {standard_task_runner.py:92} ERROR - Failed to execute job 305 for task usage_task (Parameter validation failed:
Invalid length for parameter QueryExecutionIds, value: 0, valid min length: 1; 6922)
[2023-07-12 18:07:38,621] {local_task_job.py:156} INFO - Task exited with return code 1

**Expected behavior**
These jobs should run successfully.  They did on OM version 1.0

**Version:**
 - OS: OSX
 - Python version:  3.9
 - OpenMetadata version: 1.1.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==1.1.0`]

**Comment by harshach** [comment]
@OnkarVO7 can you check this and validate and if require lets push a fix as part of 1.1.1
