### ISSUE TITLE
Failing to run profiler for a Snowflake table because of the max number of rows (10000) error

### ISSUE THREAD

**Issue by alogvinov-forter** [open-metadata/OpenMetadata#12798]
**Affected module**
Ingestion Framework

**Describe the bug**
I am trying to set up a profiler for one of the tables in Snowflake, and it fails with the following error:
```
[2023-08-08 12:56:19,369] {test_connections.py:213} INFO - failed=['\'GetTables\': This is a mandatory step and we won\'t be able to extract necessary metadata. Failed due to: (snowflake.connector.errors.ProgrammingError) 090153 (22000): The result set size exceeded the max number of rows(10000) supported for SHOW statements. Use LIMIT option to limit result set to a smaller number.\n[SQL: /* {"app": "OpenMetadata", "version": "1.0.5.0"} */\nSHOW /* sqlalchemy:get_table_names */ TABLES]\n(Background on this error at: https://sqlalche.me/e/14/f405)'] success=["'CheckAccess': Pass", "'GetDatabases': Pass", "'GetSchemas': Pass", "'GetViews': Pass", "'GetTags': Pass", "'GetQueries': Pass"] warning=[]
[2023-08-08 12:56:19,370] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/profiler.py", line 47, in profiler_workflow
    workflow = ProfilerWorkflow.create(config)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 153, in create
    return cls(config)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 117, in __init__
    self.test_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 562, in test_connection
    test_connection_fn(self.metadata, self.engine, service_config)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/snowflake/connection.py", line 166, in test_connection
    test_connection_steps(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/connections/test_connections.py", line 261, in test_connection_steps
    return timeout(timeout_seconds)(_test_connection_steps)(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/timeout.py", line 54, in inner
    result = fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/connections/test_connections.py", line 104, in _test_connection_steps
    _test_connection_steps_during_ingestion(steps=steps)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/connections/test_connections.py", line 216, in _test_connection_steps_during_ingestion
    raise SourceConnectionException
```
Database, Schema and Table filter patterns are all present (targeting just one table), but it seems they are not propagated to the code which tests connection. What's interesting is that the metadata ingestion works fine, even though it only has the Database filter pattern configured, so clearly should fail as well given we have more than 10k tables in this database.

Funnily enough, the exact same issue has been reported for DataHub: https://github.com/datahub-project/datahub/issues/3530.

**Expected behavior**
Testing connection should not require listing all the tables in a database.

**Version:**
 - Python version: 3.9
 - OpenMetadata version: 1.0.5.0
 - OpenMetadata Ingestion package version: 1.0.5.0

**Comment by pmbrull** [comment]
hi @alogvinov-forter, thanks for opening this. Weirdly I am not able to replicate it 
![image](https://github.com/open-metadata/OpenMetadata/assets/35870520/d1b22080-6d0b-48db-8b53-ac075c270872)

However, we can still improve and speed up the testing process since we just end up running a query in `INFORMATION_SCHEMA.TABLES`, so we'll update how the connection test is executed

**Comment by alogvinov-forter** [comment]
@pmbrull thanks a lot for fixing this issue! Any idea when this will be released?

I just ran into this problem when trying to set up a brand new database service for a different database which definitely has less than 10k tables:

<img width="742" alt="Screenshot 2023-08-21 at 18 59 44" src="https://github.com/open-metadata/OpenMetadata/assets/101105498/f15db79f-8ae3-4664-a931-480c3dad502e">

Makes me wonder if the connection settings are propagated correctly 🤔
