### ISSUE TITLE
When setting multi project in bigquery database, metadata ingestion fails with an 404 error.

### ISSUE THREAD

**Issue by hansh0801** [open-metadata/OpenMetadata#12989]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Framework

**Describe the bug**

In bigquery database settings, I want to set Multiple Project ID to get schema and lineage from all related projects.

Referring to https://docs.open-metadata.org/v1.1.1/connectors/database/bigquery, I set two Multiple Project IDs.

1. main-project
2. sub-project

We created a service account in main project and enabled the bigquery role in sub-project by referring to the following document.
Referenced documentation : https://www.cloudquery.io/blog/creating-cross-project-service-accounts-in-gcp
Using a single service account, we see that we can access both projects.

I'm running metadata scraping, but I'm getting the following error.

The error that the main project schema and tables are not found in the subproject and , error that the subproject schema and tables are not found in the main project.

ERROR log example

NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/{sub-project}/datasets/{schema}/tables/{main-project-table}`?prettyPrint=false: Not found:

```
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/bigquery-project-external/datasets/dataset/tables/example-table?prettyPrint=false: Not found: Table bigquery-project-external:dataset.example-table
[2023-08-24, 09:15:34 UTC] {common_db_source.py:419} WARNING - Unexpected exception to yield table [example-table]: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/bigquery-project-external/datasets/dataset/tables/example-table?prettyPrint=false: Not found: Table bigquery-project-external:dataset.example-table
[2023-08-24, 09:15:34 UTC] {helpers.py:128} DEBUG - yield_table executed in 0.61s
[2023-08-24, 09:15:34 UTC] {topology_runner.py:77} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.table.Table'> processor='yield_table' context='table' ack_sink=True nullable=False must_return=False cache_all=False clear_cache=False overwrite=True consumer=['database_service', 'database', 'database_schema']
[2023-08-24, 09:15:34 UTC] {sql_column_handler.py:119} DEBUG - Cannot obtain unique constraints for table [example-table]: NotImplementedError
[2023-08-24, 09:15:35 UTC] {common_db_source.py:418} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/common_db_source.py", line 395, in yield_table
    is_partitioned, partition_details = self.get_table_partition_details(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/bigquery/metadata.py", line 394, in get_table_partition_details
    table = self.client.get_table(f"{database}.{schema_name}.{table_name}")
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1034, in get_table
    api_response = self._call_api(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/bigquery-project-external/datasets/dataset/tables/example-table?prettyPrint=false: Not found: Table bigquery-project-external:example-table
[2023-08-24, 09:15:35 UTC] {common_db_source.py:419} WARNING - Unexpected exception to yield table [example-table]: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/bigquery-project-external/datasets/dataset/tables/example-table?prettyPrint=false: Not found: Table bigquery-project-external:example-table
[2023-08-24, 09:15:35 UTC] {helpers.py:128} DEBUG - yield_table executed in 0.53s
[2023-08-24, 09:15:35 UTC] {topology_runner.py:77} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.table.Table'> processor='yield_table' context='table' ack_sink=True nullable=False must_return=False cache_all=False clear_cache=False overwrite=True consumer=['database_service', 'database', 'database_schema']
[2023-08-24, 09:15:35 UTC] {sql_column_handler.py:119} DEBUG - Cannot obtain unique constraints for table [dataset.table_example_table]: NotImplementedError
[2023-08-24, 09:15:35 UTC] {common_db_source.py:418} DEBUG - Traceback (most recent call last):
```

1. it works fine when only MAIN PROJECT is set.
2. If I set up database service separately for main project and sub project, it works normally.
3. If I set both main project and sub project in one database service, the error mentioned above occurs.

**To Reproduce**

set both main project and sub project in one database service, the error mentioned above occurs.

**Expected behavior**

**Version:**
 - OS: [e.g. iOS] `docker image 1.1.1`, on kubernetes ENV
 - Python version: `docker image 1.1.1` 
 - OpenMetadata version: [e.g. 0.8] `1.1.1`
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] `docker image 1.1.1` 

**Additional context**
slack thread : https://openmetadata.slack.com/archives/C02B6955S4S/p1692602059966489

**Comment by ayush-shah** [comment]
Fixed in #13176
