### ISSUE TITLE
[Looker] Error when run ingest metadata from Looker

### ISSUE THREAD

**Issue by locnh2012** [open-metadata/OpenMetadata#13067]
**Affected module**
Ingestion Framework

**Describe the bug**
```
[2023-08-29, 06:07:13 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 221, in metadata_ingestion_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 196, in execute
    for record in self.source.next_record():
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 132, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 98, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 83, in process_nodes
    yield from self.sink_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 194, in sink_request
    entity_fqn = self.fqn_from_context(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/dashboard/dashboard_service.py", line 491, in fqn_from_context
    *context_names, entity_request.name.__root__
AttributeError: 'AddLineageRequest' object has no attribute 'name'
```

**To Reproduce**

Error when ingesting lineage metadata from looker which specify LookML repo

**Expected behavior**
The pipeline run successfully

**Version:**
 - Python version:
 - OpenMetadata version: 1.1.1
 - OpenMetadata Ingestion package version: openmetadata-ingestion[looker] == 1.1.1

**Additional context**
None

**Comment by locnh2012** [comment]
@pmbrull I think this issue was already resolved, right?

**Comment by pmbrull** [comment]
correct, thanks! We just missed linking the issue to the PR.

Issue closed by https://github.com/open-metadata/OpenMetadata/pull/13140
