### ISSUE TITLE
Test suite fails 404

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#13072]
ERROR [2023-09-04 09:59:39,865] [dw-185 - PUT /api/v1/services/ingestionPipelines/local_datalake_s3.default.awsdatalake-testing.%22data/customers/customers.csv%22.testSuite.data_customers_customers_csv_TestSuite/pipelineStatus] o.o.s.e.CatalogGenericExceptionMapper - Got exception: [NotFoundException] / message [HTTP 404 Not Found]
      javax.ws.rs.NotFoundException: HTTP 404 Not Found
	      at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	      at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	      at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	      at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	      at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	      at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	      at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	      at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
	      at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	      at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	      at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	      at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	      at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	      at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	      at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	      at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	      at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	      at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	      at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	      at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
	      at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
	      at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	      at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	      at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292)
	      at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	      at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	      at org.eclipse.jetty.servlets.HeaderFilter.doFilter(HeaderFilter.java:117)
	      at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	      at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	      at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	      at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	      at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	      at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	      at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	      at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	      at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	      at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:315)
	      at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	      at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
	      at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
	      at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	      at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	      at org.eclipse.jetty.server.Server.handle(Server.java:516)
	      at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	      at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	      at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	      at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	      at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	      at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)

**Comment by TeddyCr** [comment]
@mohityadav766 this is reproducible, though not consistently. The flow, when we create the 1st test case is:
- send a POST request to the testSuite/executable endpoint from the frontend (if not testSuite exists)
- send a POST request to the testCase endpoint. At this point we'll validate if the testSuite is executable `repository.isTestSuiteExecutable(create.getTestSuite());` which implies fetching the entity. At this point it will throw an entity not found error -- even though it is available in the DB (see below). If I then, exit the page, go back to the entity page and add a test case it will work as expected -- see screen recording.

Do you think something could be going on with transactions. @ShaileshParmar11 could you also confirm that the two steps above are done sequentially (i.e. we wait for the testSuite to be created before sending the testCase request)?

```java
  public void isTestSuiteExecutable(String testSuiteFqn) {
    TestSuite testSuite = Entity.getEntityByName(Entity.TEST_SUITE, testSuiteFqn, null, null, false);
    if (Boolean.FALSE.equals(testSuite.getExecutable())) {
      throw new IllegalArgumentException(
          "Test suite "
              + testSuite.getName()
              + " is not executable. Cannot create test cases for non-executable test suites.");
    }
  }
```
![Screenshot 2023-09-15 at 10 35 41 AM](https://github.com/open-metadata/OpenMetadata/assets/13626425/16a081e3-af7f-4b59-bffd-d5d6b5abd77a)
![Screenshot 2023-09-15 at 10 36 12 AM](https://github.com/open-metadata/OpenMetadata/assets/13626425/1d21c3bb-1960-433f-a226-fbba42efc615)

https://github.com/open-metadata/OpenMetadata/assets/13626425/c57f6371-050e-477f-a88e-fe7996e1943e

**Comment by ShaileshParmar11** [comment]
Yes, We 1st create testsuite then testCase.
