### ISSUE TITLE
Recursion issues while parsing complex avro schema nested records

### ISSUE THREAD

**Issue by mgorsk1** [open-metadata/OpenMetadata#13371]
**Affected module**
- Ingestion Framework

**Describe the bug**
While parsing AVRO schemas from confluent schema registry following error appears when the schema is more complex:

```
[2023-09-27, 17:20:23 UTC] {avro_parser.py:261} DEBUG - Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/metadata/parsers/avro_parser.py", line 259, in get_avro_fields
    field_models.append(parse_single_field(field, cls=cls))
  File "/opt/venv/lib/python3.8/site-packages/metadata/parsers/avro_parser.py", line 210, in parse_single_field
    obj = cls(
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
RecursionError: maximum recursion depth exceeded while calling a Python object
[2023-09-27, 17:20:23 UTC] {avro_parser.py:262} WARNING - Unable to parse the avro schema into models: maximum recursion depth exceeded while calling a Python object
[2023-09-27, 17:20:24 UTC] {local_task_job_runner.py:225} INFO - Task exited with return code Negsignal.SIGABRT
```
This cannot be worked around by try except blog as we get SIGABRT (because of the recursion issue) which is final and fatal.

**To Reproduce**

exemplary schema that will cause the issue:

```
{
   "name":"MainRecord",
   "type":"record",
   "fields":[
      {
         "default":"None",
         "name":"NestedRecord",
         "type":[
            "null",
            {
               "fields":[
                  {
                     "default":"None",
                     "name":"FieldA",
                     "type":[
                        "null",
                        {
                           "items":{
                              "fields":[
                                 {
                                    "name":"FieldAA",
                                    "type":"string"
                                 },
                                 {
                                    "default":"None",
                                    "name":"FieldBB",
                                    "type":[
                                       "null",
                                       "string"
                                    ]
                                 },
                                 {
                                    "default":"None",
                                    "name":"FieldCC",
                                    "type":[
                                       "null",
                                       "RecursionIssueRecord"
                                    ]
                                 }
                              ],
                              "name":"RecursionIssueRecord",
                              "type":"record"
                           },
                           "type":"array"
                        }
                     ]
                  }
               ],
               "name":"FieldInNestedRecord",
               "type":"record"
            }
         ]
      }
   ]
}
```

**Expected behavior**
Schema is properly parsed and ingested to be later visualized in UI.

**Version:**
 - Python version: 3.8
 - OpenMetadata version: 1.1.5
 - OpenMetadata Ingestion package version: 1.1.5

**Additional context**
The error did not appear in version 1.1.0 where `parse_single_field` was used to parse 'record' entries instead of parse_record_field (however this behavior yielded not accurate results). Recursion issues are handled in pydantic 2+ - with this pr to pydantic-core https://github.com/pydantic/pydantic-core/pull/134/files - this makes recursion issues easier to try/catch, not mitigate them. I think in case of recursive references it would be ok to handle like it that.

**Comment by mgorsk1** [comment]
cc @OnkarVO7 @ulixius9
