### ISSUE TITLE
Entity Ingestion Data Conflict (metadata.ingestion.ometa.client.APIError: Entity already exists)

### ISSUE THREAD

**Issue by yogocik** [open-metadata/OpenMetadata#13416]
**Affected module**
So far, the process is still completed even error is raised. I am not sure about the further effect of this to entity data update behind scene. 

**Describe the bug**
It's related with internal data relationship or management which cause some kind of rejection of duplicated entity data. 

**To Reproduce**
Ingest pipeline metadata such as Airbyte or Dagster after first attempt.

**Expected behavior**
The ingestion data will be replicated or overwritten with latest one

**Version:**
 - OS:  MacOS BigSur 11.7.10
 - Python version: 3.10.11
 - OpenMetadata version: 1.1.5.0
 - OpenMetadata Ingestion package version: openmetadata-ingestion[bigquery,bigquery-usage,postgres]==1.1.5.0

**Additional context**
Slack Thread URL : https://openmetadata.slack.com/archives/C02B6955S4S/p1695966060169629

**Error snippet**,
[2023-09-29 12:32:40] DEBUG    {metadata.Ingestion:topology_runner:77} - Processing stage: type_=<class 'metadata.ingestion.models.pipeline_status.OMetaPipelineStatus'> processor='yield_pipeline_status' context='pipeline_status' ack_sink=False nullable=True must_return=False cache_all=False clear_cache=False overwrite=True consumer=['pipeline_service']
[2023-09-29 12:32:41] DEBUG    {metadata.Ingestion:metadata_rest:355} - Traceback (most recent call last):
  File "/my-folder/.venv/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 212, in _one_request
    resp.raise_for_status()
  File "my-folder/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://localhost:8585/api/v1/pipelines/airbyte_source.066e6253-5550-44e3-be01-cbfce4a9310b/status
metadata.ingestion.ometa.client.APIError: Entity already exists
[2023-09-29 12:33:24] DEBUG    {metadata.Ingestion:topology_runner:77} - Processing stage: type_=<class 'metadata.generated.schema.api.lineage.addLineage.AddLineageRequest'> processor='yield_pipeline_lineage' context='lineage' ack_sink=False nullable=True must_return=False cache_all=False clear_cache=False overwrite=True consumer=['pipeline_service']
[2023-09-29 12:33:24] DEBUG    {metadata.Ingestion:topology_runner:101} - Post processing node producer='get_services' stages=[NodeStage(type_=<class 'metadata.generated.schema.entity.services.pipelineService.PipelineService'>, processor='yield_create_request_pipeline_service', context='pipeline_service', ack_sink=True, nullable=False, must_return=True, cache_all=False, clear_cache=False, overwrite=False, consumer=None)] children=['pipeline'] post_process=['mark_pipelines_as_deleted']
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Statuses detailed info:
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Source Status:
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - {'failures': [],
'records': ['airbyte_source.066e6253-5550-44e3-be01-cbfce4a9310b', 'airbyte_source.0e6931ea-00b7-4623-bf09-f185a5503ad0'],
 'source_start_time': 1695960360.285953,
 'success': [],
 'warnings': []}
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Sink Status:
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - {'failures': [],
 'records': ['Pipeline: airbyte_source.066e6253-5550-44e3-be01-cbfce4a9310b',
             'Pipeline Status: airbyte_source.066e6253-5550-44e3-be01-cbfce4a9310b',
             'Pipeline: airbyte_source.0e6931ea-00b7-4623-bf09-f185a5503ad0',
             'Pipeline Status: airbyte_source.0e6931ea-00b7-4623-bf09-f185a5503ad0'],
 'warnings': []}
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Workflow Summary:
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Total processed records: 6
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Total warnings: 0
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Total filtered: 90
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Total errors: 0
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Success %: 100.0
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Workflow finished in time: 1.0h 87.0m 24.4s
[2023-09-29 12:33:24] INFO     {metadata.Utils:logger:183} - Workflow finished successfully

**Comment by pmbrull** [comment]
looks like we might need to review how we are passing the status timestamps here since it is colliding with the PK

**Comment by pmbrull** [comment]
this has already been fixed in main here https://github.com/open-metadata/OpenMetadata/pull/13384

Will be released in 1.2
