### ISSUE TITLE
MSSQL Database Services - Usage - 'table_usage_count' referenced before assignment

### ISSUE THREAD

**Issue by AnZelie** [open-metadata/OpenMetadata#13499]
New issue with the version 1.1.7.

*** Found local files:
***   * /opt/airflow/logs/dag_id=docuware_usage/run_id=manual__2023-10-09T14:09:44+00:00/task_id=usage_task/attempt=1.log
[2023-10-09, 14:09:45 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docuware_usage.usage_task manual__2023-10-09T14:09:44+00:00 [queued]>
[2023-10-09, 14:09:45 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docuware_usage.usage_task manual__2023-10-09T14:09:44+00:00 [queued]>
[2023-10-09, 14:09:45 UTC] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-10-09, 14:09:45 UTC] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): usage_task> on 2023-10-09 14:09:44+00:00
[2023-10-09, 14:09:45 UTC] {standard_task_runner.py:57} INFO - Started process 676790 to run task
[2023-10-09, 14:09:45 UTC] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'docuware_usage', 'usage_task', 'manual__2023-10-09T14:09:44+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/docuware_usage.py', '--cfg-path', '/tmp/tmpod0w0c19']
[2023-10-09, 14:09:45 UTC] {standard_task_runner.py:85} INFO - Job 235: Subtask usage_task
[2023-10-09, 14:09:46 UTC] {task_command.py:410} INFO - Running <TaskInstance: docuware_usage.usage_task manual__2023-10-09T14:09:44+00:00 [running]> on host e2dee958a89c
[2023-10-09, 14:09:46 UTC] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='docuware_usage' AIRFLOW_CTX_TASK_ID='usage_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T14:09:44+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-09T14:09:44+00:00'
[2023-10-09, 14:09:46 UTC] {workflow.py:115} INFO - Service type:ServiceType.Database,mssql-usage configured
[2023-10-09, 14:09:46 UTC] {helpers.py:475} INFO - Creating the directory to store staging data in /tmp/query_log
[2023-10-09, 14:09:46 UTC] {workflow.py:168} INFO - BulkSink type:metadata-usage,<class 'metadata.ingestion.bulksink.metadata_usage.MetadataUsageBulkSink'> configured
[2023-10-09, 14:09:46 UTC] {usage_source.py:91} INFO - Scanning query logs for 2023-10-08 - 2023-10-09
[2023-10-09, 14:10:10 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:10 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:10 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:10 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:10 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:10 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:11 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:12 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:13 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:13 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:13 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:13 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:13 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:13 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:14 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:15 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:16 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:16 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:16 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:16 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:16 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:16 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:17 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:18 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:18 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:25 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:26 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:26 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:26 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:26 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:26 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:26 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:27 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:28 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:29 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:29 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:29 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:29 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:29 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:29 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:30 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:31 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:31 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:31 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:31 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:31 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:31 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:32 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:33 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.object_id = cs2.object_id
[2023-10-09, 14:10:33 UTC] {parser.py:308} WARNING - Cannot find ingredients from cs1.index_id = cs2.index_id
[2023-10-09, 14:10:46 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-10-09, 14:10:46 UTC] {workflow_reporter.py:47} INFO - Bulk Sink: Processed 0 records, found 0 errors
[2023-10-09, 14:11:46 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-10-09, 14:11:46 UTC] {workflow_reporter.py:47} INFO - Bulk Sink: Processed 0 records, found 0 errors
[2023-10-09, 14:12:03 UTC] {table_usage.py:140} WARNING - Error in staging record: 1 validation error for CreateQueryRequest
usedBy -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
[2023-10-09, 14:12:03 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 236, in metadata_ingestion_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 202, in execute
    self.stage.stage_record(processed_record)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/stage/table_usage.py", line 157, in stage_record
    self._handle_table_usage(parsed_data=parsed_data, table=table)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/stage/table_usage.py", line 141, in _handle_table_usage
    self.table_usage[(table, parsed_data.date)] = table_usage_count
UnboundLocalError: local variable 'table_usage_count' referenced before assignment
[2023-10-09, 14:12:03 UTC] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=docuware_usage, task_id=usage_task, execution_date=20231009T140944, start_date=20231009T140945, end_date=20231009T141203
[2023-10-09, 14:12:03 UTC] {common.py:311} INFO - Sending failed status from callback...
[2023-10-09, 14:12:03 UTC] {common.py:317} INFO - Sending status to Ingestion Pipeline docuware.docuware_usage
[2023-10-09, 14:12:04 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 235 for task usage_task (local variable 'table_usage_count' referenced before assignment; 676790)
[2023-10-09, 14:12:04 UTC] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-09, 14:12:04 UTC] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by pmbrull** [comment]
hi this has been fixed in 1.2.0 release
