### ISSUE TITLE
Workflow with FileSink not working

### ISSUE THREAD

**Issue by locian98** [open-metadata/OpenMetadata#13673]
**Affected module**
OpenMetadata/ingestion/src/metadata/ingestion/sink/file.py

**Describe the bug**
Using FileSink in an ingestion workflow results in errors.

**To Reproduce**
Use the following python script to create a workflow:
```python
import os
import yaml

from metadata.ingestion.api.workflow import Workflow

with open("config.yaml", "r") as stream:
    workflow_config = yaml.safe_load(stream)

def run():
    workflow = Workflow.create(workflow_config)
    workflow.execute()
    workflow.raise_from_status()
    workflow.print_status()
    workflow.stop()

if __name__ == "__main__":
    run()
```
Where conifg.yaml is as follows:
```yaml
source:
  type: redshift
  serviceName: 'my_database'
  serviceConnection:
    config:
      type: Redshift
      scheme: 'redshift+psycopg2'
      hostPort: 'my-endpoint.eu-west-1.redshift.amazonaws.com:8192'
      username: admin
      password: redacted
      database: 'my_database'
      sslMode: prefer
  sourceConfig:
    config:
      includeViews: false
      includeTags: false
      markDeletedTables: true
      type: DatabaseMetadata
sink:
  type: file
  config:
    filename: output.txt
workflowConfig:
  loggerLevel: DEBUG
  openMetadataServerConfig:
    hostPort: https://my-openmetadata.endpoint/api
    authProvider: openmetadata
    securityConfig:
      jwtToken: 'my-ingestion-bot-jwt'
```

The following error is generated
```
[2023-10-19 15:26:45] DEBUG    {metadata.OMetaAPI:server_mixin:63} - Validating client and server versions
[2023-10-19 15:26:45] INFO     {metadata.Ingestion:workflow:115} - Service type:ServiceType.Database,redshift configured
[2023-10-19 15:26:46] DEBUG    {metadata.OMetaAPI:server_mixin:63} - Validating client and server versions
[2023-10-19 15:26:54] INFO     {metadata.Metadata:test_connections:215} - Test connection results:
[2023-10-19 15:26:54] INFO     {metadata.Metadata:test_connections:216} - failed=[] success=["'CheckAccess': Pass", "'GetDatabases': Pass", "'GetSchemas': Pass", "'GetTables': Pass", "'GetViews': Pass", "'GetPartitionTableDetails': Pass", "'GetQueries': Pass"] warning=[]
[2023-10-19 15:26:54] DEBUG    {metadata.Ingestion:workflow:128} - Source type:redshift,<class 'metadata.ingestion.source.database.redshift.metadata.RedshiftSource'> configured
[2023-10-19 15:26:54] DEBUG    {metadata.Ingestion:workflow:130} - Source type:redshift,<class 'metadata.ingestion.source.database.redshift.metadata.RedshiftSource'>  prepared
[2023-10-19 15:26:54] DEBUG    {metadata.Ingestion:workflow:159} - Sink type:file,<class 'metadata.ingestion.sink.file.FileSink'> configured
[2023-10-19 15:26:54] DEBUG    {metadata.Ingestion:topology_runner:67} - Processing node producer='get_services' stages=[NodeStage(type_=<class 'metadata.generated.schema.entity.services.databaseService.DatabaseService'>, processor='yield_create_request_database_service', context='database_service', ack_sink=True, nullable=False, must_return=True, cache_all=False, clear_cache=False, overwrite=False, consumer=None)] children=['database'] post_process=['yield_view_lineage']
[2023-10-19 15:26:54] DEBUG    {metadata.Ingestion:topology_runner:77} - Processing stage: type_=<class 'metadata.generated.schema.entity.services.databaseService.DatabaseService'> processor='yield_create_request_database_service' context='database_service' ack_sink=True nullable=False must_return=True cache_all=False clear_cache=False overwrite=False consumer=None
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    run()
  File "main.py", line 13, in run
    workflow.execute()
  File "/Users/lorenzo/.pyenv/versions/3.8.18/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/Users/lorenzo/.pyenv/versions/3.8.18/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 196, in execute
    for record in self.source.next_record():
  File "/Users/lorenzo/.pyenv/versions/3.8.18/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 132, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/Users/lorenzo/.pyenv/versions/3.8.18/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 83, in process_nodes
    yield from self.sink_request(
  File "/Users/lorenzo/.pyenv/versions/3.8.18/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 221, in sink_request
    raise MissingExpectedEntityAckException(
metadata.ingestion.api.topology_runner.MissingExpectedEntityAckException: Missing ack back from [DatabaseService: __root__='my_database'] - Possible causes are changes in the server Fernet key or mismatched JSON Schemas for the service connection.
```

**Expected behavior**
The workflow should run successfully.

**Version:**
 - OS: MacOS 13.5.2
 - Python version: 3.8
 - OpenMetadata version: 1.1.7
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.1.7.0

**Additional context**
Reflecting the discussion on Slack:
https://openmetadata.slack.com/archives/C02B6955S4S/p1697716840850389
As can be observed from the logs there is no issue in the yaml or the connection parameters.
I have been asked to try authProvider: basic but even that results in other errors.

**Comment by muhsincan** [comment]
I have started investigating this issue, I believe this file - topology_runner.py - is the key to progressing this but not sure how to go about it:
https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/ingestion/api/topology_runner.py

**Comment by pmbrull** [comment]
yes we have a couple of validations to ensure that some records have been properly processed by the OM server before moving forward. E.g., we can't ingest databases unless the service is there, so we do some GET calls.

We also compare some incoming fingerprints vs. the existing asset if it was previously ingested. So we'll need to rework a few things if we want the process to run completely without server

**Comment by pmbrull** [comment]
IMO this can get tricky since the ingestion process requires the state of the server (e.g., we want to ensure the service is created before moving forward).

If the metadata needs to be exported anywhere, we can do so via the API once it has been ingested in the OM server
