### ISSUE TITLE
Table 'openmetadata_db.SERVER_CHANGE_LOG' doesn't exist

### ISSUE THREAD

**Issue by zlobniyshurik** [open-metadata/OpenMetadata#13761]
**Affected module**
backend

**Describe the bug**
`./bootstrap/bootstrap_storage.sh drop-create-all` lead to error `Table 'openmetadata_db.SERVER_CHANGE_LOG' doesn't exist`

**To Reproduce**
1. Create empty MySQL DB with:
```
CREATE DATABASE openmetadata_db;
CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';
GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT OPTION;
commit;
```
2. go to the openmetadata dir

3. run `./bootstrap/bootstrap_storage.sh drop-create-all`

4. got error
```
You are about drop all the data in the database. ALL METADATA WILL BE DELETED. 
This is not recommended for a Production setup or any deployment where you have collected 
a lot of information from the users, such as descriptions, tags, etc.

Enter QUIT to quit. If you still want to continue, please enter DELETE: 
DELETE
DONE
07:25:31.602 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.app.AppMarketPlaceDefinition appMarketPlaceDefinition
07:25:31.644 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.app.App app
07:25:31.676 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.Bot bot
07:25:31.723 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Chart chart
07:25:31.753 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.classification.Classification classification
07:25:31.785 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Container container
07:25:31.815 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.DashboardDataModel dashboardDataModel
07:25:31.850 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Dashboard dashboard
07:25:31.899 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.DashboardService dashboardService
07:25:31.931 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.dataInsight.DataInsightChart dataInsightChart
07:25:31.959 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.domains.DataProduct dataProduct
07:25:31.987 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Database database
07:25:32.017 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.DatabaseSchema databaseSchema
07:25:32.067 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.DatabaseService databaseService
07:25:32.100 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entities.docStore.Document document
07:25:32.138 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.domains.Domain domain
07:25:32.165 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.events.EventSubscription eventsubscription
07:25:32.203 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Glossary glossary
07:25:32.238 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.GlossaryTerm glossaryTerm
07:25:32.275 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.ingestionPipelines.IngestionPipeline ingestionPipeline
07:25:32.297 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.dataInsight.kpi.Kpi kpi
07:25:32.338 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.MessagingService messagingService
07:25:32.370 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.MetadataService metadataService
07:25:32.390 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Metrics metrics
07:25:32.425 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.MlModel mlmodel
07:25:32.459 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.MlModelService mlmodelService
07:25:32.485 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.teams.Persona persona
07:25:32.509 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Pipeline pipeline
07:25:32.539 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.PipelineService pipelineService
07:25:32.567 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.policies.Policy policy
07:25:32.596 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Query query
07:25:32.654 [main] INFO  o.o.s.Entity - Registering entity time series class org.openmetadata.schema.analytics.ReportData entityReportData
07:25:32.682 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Report report
07:25:32.709 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.teams.Role role
07:25:32.733 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.SearchIndex searchIndex
07:25:32.756 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.SearchService searchService
07:25:32.780 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.StorageService storageService
07:25:32.813 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.StoredProcedure storedProcedure
07:25:32.851 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Table table
07:25:32.870 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.classification.Tag tag
07:25:32.890 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.teams.Team team
07:25:32.925 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.tests.TestCase testCase
07:25:32.945 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.services.connections.TestConnectionDefinition testConnectionDefinition
07:25:32.964 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.tests.TestDefinition testDefinition
07:25:32.990 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.tests.TestSuite testSuite
07:25:33.017 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.data.Topic topic
07:25:33.035 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.Type type
07:25:33.068 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.teams.User user
07:25:33.093 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.analytics.WebAnalyticEvent webAnalyticEvent
07:25:33.110 [main] INFO  o.o.s.Entity - Registering entity class org.openmetadata.schema.entity.automations.Workflow workflow
createoption failed with : org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.SQLSyntaxErrorException: Table 'openmetadata_db.SERVER_CHANGE_LOG' doesn't exist [statement:"SELECT MAX(version) FROM SERVER_CHANGE_LOG", arguments:{positional:{}, named:{}, finder:[]}]
        at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1789)
        at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$3(ResultProducers.java:94)
        at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:58)
        at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:244)
        at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$SingleValueReturner.mappedResult(ResultReturner.java:259)
        at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:65)
        at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:196)
        at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:27)
        at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:135)
        at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:75)
        at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:141)
        at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:135)
        at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:108)
        at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$invoke$5(OnDemandExtensions.java:99)
        at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
        at org.jdbi.v3.core.internal.OnDemandExtensions.invoke(OnDemandExtensions.java:99)
        at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$2(OnDemandExtensions.java:83)
        at org.jdbi.v3.core.Jdbi.callWithExtension(Jdbi.java:502)
        at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:489)
        at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$3(OnDemandExtensions.java:83)
        at jdk.proxy2/jdk.proxy2.$Proxy55.getMaxServerMigrationVersion(Unknown Source)
        at org.openmetadata.service.migration.api.MigrationWorkflow.filterAndGetMigrationsToRun(MigrationWorkflow.java:98)
        at org.openmetadata.service.migration.api.MigrationWorkflow.loadMigrations(MigrationWorkflow.java:51)
        at org.openmetadata.service.util.TablesInitializer.validateAndRunSystemDataMigrations(TablesInitializer.java:360)
        at org.openmetadata.service.util.TablesInitializer.execute(TablesInitializer.java:284)
        at org.openmetadata.service.util.TablesInitializer.main(TablesInitializer.java:209)
Caused by: java.sql.SQLSyntaxErrorException: Table 'openmetadata_db.SERVER_CHANGE_LOG' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
        at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
        at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1787)
        ... 25 more
```

**Expected behavior**
No errors

**Version:**
 - OS: Debian 12
 - Python version: Python 3.11.2
 - OpenMetadata version: 1.2.0
- MySQL: 8.0.35 MySQL Community Server - GPL
- openjdk-17-jre-headless/stable,stable-security,now 17.0.8+7-1~deb12u1 amd64
- opensearch/stable,now 1.3.13 amd64

**Additional context**
Same problem with 1.1.7 release.

**Comment by harshach** [comment]
@zlobniyshurik use https://slack.open-metadata.org to discuss the bugs before filing one github tickets.
