### ISSUE TITLE
MWAA Ingestion generates error logs

### ISSUE THREAD

**Issue by Shanthan0** [open-metadata/OpenMetadata#13865]
**Affected module**
Ingestion Framework

**Describe the bug**
I connected MWAA with OpenMetadata by getting the connection details using a DAG.  The MWAA ingestion pipeline runs successfully and I can see the MWAA pipelines in OpenMetadata. But I don't see any lineage and the ingestion pipeline generates error logs siting invalid task name and entity already exists for all the MWAA tasks.

**To Reproduce**

`[2023-11-07, 04:00:08 +08] {metadata_rest.py:356} ERROR - Unexpected error writing pipeline status [pipeline_fqn='MWAA.pipeline__periscope__integration_eligibilities' pipeline_status=PipelineStatus(timestamp=Timestamp(__root__=1685560500), executionStatus=<StatusType.Successful: 'Successful'>, taskStatus=[TaskStatus(name='DataProcessing.end_integration_eligibilities', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685659807753), endTime=Timestamp(__root__=1685659808873), logLink=None), TaskStatus(name='DataProcessing.populate', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685659384829), endTime=Timestamp(__root__=1685659389220), logLink=None), TaskStatus(name='DataProcessing.create', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685658375626), endTime=Timestamp(__root__=1685658376153), logLink=None), TaskStatus(name='DataProcessing.drop', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685658236876), endTime=Timestamp(__root__=1685658237632), logLink=None), TaskStatus(name='DataProcessing.start_integration_eligibilities', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685656936021), endTime=Timestamp(__root__=1685656936943), logLink=None), TaskStatus(name='processing_ready', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685655111643), endTime=Timestamp(__root__=1685655111643), logLink=None), TaskStatus(name='waiting_for_pipeline__periscope__option_optionables_view', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685655110852), endTime=Timestamp(__root__=1685655111431), logLink=None), TaskStatus(name='waiting_for_clone__aspireapp__businesses', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685648329178), endTime=Timestamp(__root__=1685648329637), logLink=None), TaskStatus(name='waiting_for_clone__aspireapp__people', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685648269887), endTime=Timestamp(__root__=1685648270413), logLink=None), TaskStatus(name='waiting_for_clone__aspireapp__integrations', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685648266796), endTime=Timestamp(__root__=1685648267333), logLink=None), TaskStatus(name='waiting_for_clone__aspireapp__accounts', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685648201975), endTime=Timestamp(__root__=1685648202598), logLink=None), TaskStatus(name='waiting_for_pipeline__periscope__person_phone', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685648091157), endTime=Timestamp(__root__=1685648091849), logLink=None), TaskStatus(name='waiting_for_pipeline__periscope__person_email', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685648084017), endTime=Timestamp(__root__=1685648084575), logLink=None), TaskStatus(name='waiting_for_clone__aspireapp__state_logs', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685648036335), endTime=Timestamp(__root__=1685648036857), logLink=None), TaskStatus(name='waiting_for_pipeline__periscope__eligibilities', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685647952147), endTime=Timestamp(__root__=1685647952736), logLink=None), TaskStatus(name='waiting_for_clone__aspireapp__countries', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685647949597), endTime=Timestamp(__root__=1685647950200), logLink=None)])]: Invalid task name DataProcessing.end_integration_eligibilities`

`[2023-11-07, 04:00:09 +08] {metadata_rest.py:356} ERROR - Unexpected error writing pipeline status [pipeline_fqn='MWAA.pipeline__analytics__budget_transactions' pipeline_status=PipelineStatus(timestamp=Timestamp(__root__=1698379373), executionStatus=<StatusType.Successful: 'Successful'>, taskStatus=[TaskStatus(name='data_processing_pipeline__analytics__budget_transactions.end_budget_transactions', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1698379431717), endTime=Timestamp(__root__=1698379433445), logLink=None), TaskStatus(name='data_processing_pipeline__analytics__budget_transactions.drop_budget_transactions', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1698379422975), endTime=Timestamp(__root__=1698379424301), logLink=None), TaskStatus(name='data_processing_pipeline__analytics__budget_transactions.populate_budget_transactions', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1698379393758), endTime=Timestamp(__root__=1698379415865), logLink=None), TaskStatus(name='data_processing_pipeline__analytics__budget_transactions.drop_staging_budget_transactions', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1698379386577), endTime=Timestamp(__root__=1698379387497), logLink=None), TaskStatus(name='data_processing_pipeline__analytics__budget_transactions.start_budget_transactions', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1698379379009), endTime=Timestamp(__root__=1698379380307), logLink=None)])]: Entity already exists`

`[2023-11-07, 04:00:09 +08] {metadata_rest.py:356} ERROR - Unexpected error writing pipeline status [pipeline_fqn='MWAA.pipeline__utils__months' pipeline_status=PipelineStatus(timestamp=Timestamp(__root__=1685894400), executionStatus=<StatusType.Successful: 'Successful'>, taskStatus=[TaskStatus(name='populate', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685980816177), endTime=Timestamp(__root__=1685980817546), logLink=None), TaskStatus(name='create', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685980812260), endTime=Timestamp(__root__=1685980812707), logLink=None), TaskStatus(name='drop', executionStatus=<StatusType.Successful: 'Successful'>, startTime=Timestamp(__root__=1685980806187), endTime=Timestamp(__root__=1685980806997), logLink=None)])]: Invalid task name populate`

**Expected behavior**
Ideally there should not be any error logs while ingesting

**Version:**
 - OpenMetadata version: 1.1.7
 - OpenMetadata Airflow: 2.6.3
 - MWAA: 2.5.1

**Comment by ayush-shah** [comment]
> OpenMetadata version: 1.1.7
OpenMetadata Airflow: 2.6.3
MWAA: 2.5.1


@Shanthan0 if you can upgrade to latest 1.6.8 and let us know if you are facing the same, I will close the ticket, if the error is reproduced, we can reopen the ticket, Thanks

**Comment by tejas18-only** [comment]
Im also trying to connect openmetadata with mwaa, but facing the issue of Broken DAG: [/usr/local/airflow/dags/openmetadata_dq_usage_records.py]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/airflow/dags/openmetadata_dq_usage_records.py", line 8, in <module>
    from metadata.workflow.data_quality import TestSuiteWorkflow
ModuleNotFoundError: No module named 'metadata',

The requirement.txt contains a lot boto3==1.34.137
munch==4.0.0
pandas==2.2.2
numpy==1.26.4
psycopg2-binary==2.9.9
pydantic==2.8.0
PyYAML==6.0.1
redshift-connector==2.1.2
requests==2.32.3
python-dateutil==2.9.0
pysftp==0.2.9
pymssql==2.3.0
pytest==8.3.3
pyspark==3.5.1
pydeequ==1.4.0
pymysql==1.1.1
fuzzywuzzy==0.18.0
coverage==7.6.4
pytest-mock==3.14.0
paramiko==3.5.0
cryptography==44.0.0
cffi==1.17.1
PyNaCl==1.5.0
asn1crypto==1.5.1
urllib3==1.26.20
openmetadata-ingestion==1.11.0
openmetadata-managed-apis==1.11.0

can you please help ??
