### ISSUE TITLE
Superset Ingestion Issues while ingesting dashboard datamodels

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#14348]
**Affected module**
Ingestion Framework

**Describe the bug**

**To Reproduce**
Superset ingestion is failing with below errors. This happens with superset db connection.
```
value is not a valid integer (type=type_error.integer)
[2023-12-12, 09:35:46 UTC] {mixin.py:225} WARNING - Error to yield datamodel column: 1 validation error for Column
dataLength
  value is not a valid integer (type=type_error.integer)
[2023-12-12, 09:35:46 UTC] {mixin.py:225} WARNING - Error to yield datamodel column: 1 validation error for Column
dataLength
  value is not a valid integer (type=type_error.integer)
[2023-12-12, 09:35:46 UTC] {db_source.py:186} WARNING - chart details for id: 645 not found, skipped
[2023-12-12, 09:35:46 UTC] {db_source.py:186} WARNING - chart details for id: 646 not found, skipped
[2023-12-12, 09:35:46 UTC] {db_source.py:186} WARNING - chart details for id: 647 not found, skipped
[2023-12-12, 09:35:46 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/venv/lib/python3.8/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 236, in metadata_ingestion_workflow
    workflow.execute()
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 215, in execute
    raise err
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 196, in execute
    for record in self.source.next_record():
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 132, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 98, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 80, in process_nodes
    for entity_request in stage_fn(element) or []:
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/source/dashboard/superset/db_source.py", line 196, in yield_datamodel
    col_names = self.get_column_list(chart_json.table_name)
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/source/dashboard/superset/db_source.py", line 81, in get_column_list
    sql_query = sql.text(FETCH_COLUMN.format(table_name=table_name.lower()))
AttributeError: 'NoneType' object has no attribute 'lower'
[2023-12-12, 09:35:46 UTC] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Superset_Ather_metadata_connection, task_id=ingestion_task, execution_date=20231212T093450, start_date=20231212T093454, end_date=20231212T093546
[2023-12-12, 09:35:46 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 1021 for task ingestion_task ('NoneType' object has no attribute 'lower'; 4116908)
[2023-12-12, 09:35:46 UTC] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-12, 09:35:46 UTC] {common.py:311} INFO - Sending failed status from callback...
[2023-12-12, 09:35:46 UTC] {common.py:317} INFO - Sending status to Ingestion Pipeline Superset Ather.Superset_Ather_metadata_connection
[2023-12-12, 09:35:46 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

Fix the above issues and handle the exceptions

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 1.1.7]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by OnkarVO7** [comment]
Fixed by https://github.com/open-metadata/OpenMetadata/pull/14371
