### ISSUE TITLE
run lineage.yaml,  Error initializing LINEAGE: 500 Server Error

### ISSUE THREAD

**Issue by win-shy** [open-metadata/OpenMetadata#14432]
hello, I do experiments on the Demo files， But the result often go wrong. which one did I operate the error.

first YAML file:
 `openmetadata-demo/lineage.yaml`
```yaml
source:
  type: query-log-lineage
  serviceName: hive
  sourceConfig:
    config:
      type: DatabaseLineage
      queryLogFilePath: ./query_log.csv
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: DEBUG
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: openmetadata
    securityConfig:
      jwtToken: <ingestion-bot-token>
```
then run:
`metadata ingest -c lineage.yaml`

Console Result:
```
[2023-12-19 09:53:57] DEBUG    {Metadata:ingest:41} - Traceback (most recent call last):
  File "/root/my-venv/lib/python3.8/site-packages/metadata/cli/ingest.py", line 38, in run_ingest
    workflow = Workflow.create(config_dict)
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 213, in create
    return cls(config)
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 103, in __init__
    self.metadata = OpenMetadata(config=metadata_config)
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/ometa/ometa_api.py", line 225, in __init__
    self.validate_versions()
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/server_mixin.py", line 88, in validate_versions
    server_version = self.get_server_version()
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/server_mixin.py", line 70, in get_server_version
    raw_version = self.client.get("/version")["version"]
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 232, in get
    return self._request("GET", path, data)
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 179, in _request
    return self._one_request(method, url, opts, retry)
  File "/root/my-venv/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 201, in _one_request
    resp.raise_for_status()
  File "/root/my-venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8585/api/v1/version


Error initializing LINEAGE: 500 Server Error: Internal Server Error for url: http://localhost:8585/api/v1/version
```

and `openmetadata.log`  Reuslt
```
ERROR [2023-12-19 01:53:57,493] [dw-879 - GET /api/v1/version] o.o.s.e.CatalogGenericExceptionMapper - Got exception: [NotFoundException] / message [HTTP 404 Not Found]
javax.ws.rs.NotFoundException: HTTP 404 Not Found
```

**Comment by harshach** [comment]
@win-shy github issue are for bugs. Please check in #support channel in https://slack.open-metadata.org
