### ISSUE TITLE
Python SDK add_lineage_by_query has error

### ISSUE THREAD

**Issue by ningyanhui** [open-metadata/OpenMetadata#14434]
use add_lineage_by_query has error.
error detail:
    resp.raise_for_status()
  File "C:\Program Files\Anaconda\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://metadata.juexiaotime.com/api/v1/lineage

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Juexiao\python_scripts\openmetadata\metadata_test.py", line 247, in <module>
    metadata.add_lineage_by_query(database_service=database_entity, sql=sql)
  File "C:\Users\16332\AppData\Roaming\Python\Python39\site-packages\metadata\ingestion\ometa\mixins\lineage_mixin.py", line 180, in add_lineage_by_query
    resp = self.add_lineage(lineage_request)
  File "C:\Users\16332\AppData\Roaming\Python\Python39\site-packages\metadata\ingestion\ometa\mixins\lineage_mixin.py", line 59, in add_lineage
    raise err
  File "C:\Users\16332\AppData\Roaming\Python\Python39\site-packages\metadata\ingestion\ometa\mixins\lineage_mixin.py", line 50, in add_lineage
    self.client.put(self.get_suffix(AddLineageRequest), data=data.json())
  File "C:\Users\16332\AppData\Roaming\Python\Python39\site-packages\metadata\ingestion\ometa\client.py", line 288, in put
    return self._request("PUT", path, data)
  File "C:\Users\16332\AppData\Roaming\Python\Python39\site-packages\metadata\ingestion\ometa\client.py", line 189, in _request
    return self._one_request(method, url, opts, retry)
  File "C:\Users\16332\AppData\Roaming\Python\Python39\site-packages\metadata\ingestion\ometa\client.py", line 230, in _one_request
    raise APIError(error, http_error) from http_error
metadata.ingestion.ometa.client.APIError: Unrecognized field "left" (class org.openmetadata.schema.api.lineage.AddLineage), not marked as ignorable (one known property: "edge"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 14] (through reference chain: org.openmetadata.schema.api.lineage.AddLineage["left"])

**Comment by harshach** [comment]
@ningyanhui can you please reach out us in https://slack.open-metadata.org. This looks like misconfiguration in your code.
