### ISSUE TITLE
Using existing Airflow with 1.2.3, test suite ingestion fails without trino package installed

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#14519]
**Affected module**
Ingestion

**Describe the bug**
I do not have a Trino data source, only MS SQL.  After upgrading to OpenMetadata 1.2.3, most of my existing ingestions work, but a test suite is failing with `Unhandled exception during workflow processing: [No module named 'trino']`.

I tried modifying my custom Airflow instance's `requirements.txt` to include `openmetadata-ingestion[mssql,trino]==1.2.3` and that resolved the error.  Is there an `import trino` call happening somewhere inside the test suite code where it should not be?

**To Reproduce**

1. Set up OpenMetadata v1.2.3 with an external Airflow (I'm using image `apache/airflow:2.6.1-python3.8`).
2. Create a data quality test and run it

**Expected behavior**
Test suite succeeds without requiring installation of trino package.

**Version:**
 - OS: Ubuntu (Docker Compose deployment)
 - Python version: 3.8
 - OpenMetadata version: 1.2.3
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[mssql]==1.2.3`

**Stacktrace from Airflow**
```
[2023-12-28T09:15:25.730+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/openmetadata_managed_apis/workflows/ingestion/test_suite.py", line 51, in test_suite_workflow
    workflow.raise_from_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/workflow/workflow_status_mixin.py", line 146, in raise_from_status
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/workflow/workflow_status_mixin.py", line 143, in raise_from_status
    self._raise_from_status_internal(raise_warnings)
  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/workflow/workflow_status_mixin.py", line 81, in _raise_from_status_internal
    raise WorkflowExecutionError(
metadata.config.common.WorkflowExecutionError: ('TestCaseRunner reported errors', Status(source_start_time=1703754924.7241292, records=[], warnings=[], filtered=[], failures=[StackTraceError(name='Unhandled', error="Unhandled exception during workflow processing: [No module named 'trino']", stack_trace='Traceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/ingestion/api/step.py", line 71, in run\n    result: Either = self._run(record)\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/data_quality/processor/test_case_runner.py", line 93, in _run\n    test_suite_runner = test_suite_source_factory.create(\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/data_quality/runner/base_test_suite_source.py", line 119, in get_data_quality_runner\n    return DataTestsRunner(self.create_data_quality_interface())\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/data_quality/runner/base_test_suite_source.py", line 103, in create_data_quality_interface\n    test_suite_interface_factory.create(\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/data_quality/interface/test_suite_interface_factory.py", line 83, in create\n    return interface(\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py", line 75, in __init__\n    self._sampler = self._create_sampler()\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py", line 121, in _create_sampler\n    from metadata.profiler.processor.sampler.sampler_factory import (  # pylint: disable=import-outside-toplevel\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/profiler/processor/sampler/sampler_factory.py", line 33, in <module>\n    from metadata.profiler.processor.sampler.sqlalchemy.trino.sampler import TrinoSampler\n  File "/home/airflow/.local/lib/python3.8/site-packages/metadata/profiler/processor/sampler/sqlalchemy/trino/sampler.py", line 16, in <module>\n    from trino.sqlalchemy.dialect import TrinoDialect\nModuleNotFoundError: No module named \'trino\'\n')]))
```

**Comment by TeddyCr** [comment]
@sfirke could you try upgrading to the latest version? I could not reproduce it locally.

**Comment by OnkarVO7** [comment]
Hi we could not reproduce the issue. Feel free to re-open the same if you have more details
