### ISSUE TITLE
Helm 1.2.5 app 1.2.3 doesn't connect to AWS RDS Postgresql | Message : The connection attempt failed.

### ISSUE THREAD

**Issue by tirelibirefe** [open-metadata/OpenMetadata#14534]
Helm 1.2.5 app 1.2.3 doesn't connecto to AWS RDS Postgresql

```
repairoption failed with : org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:postgresql://xxxxx.rds.amazonaws.com:5432/openmetadata?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=Europe/Istanbul) for user 'xxxx': The connection attempt failed.
-------------------------
SQL State  : 08001
Error Code : 0
Message    : The connection attempt failed.

  at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
  at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
  at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:142)
  at org.flywaydb.core.Flyway.repair(Flyway.java:354)
  at org.openmetadata.service.util.TablesInitializer.execute(TablesInitializer.java:321)
  at org.openmetadata.service.util.TablesInitializer.main(TablesInitializer.java:209)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
  at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
  at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
  at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
  at org.postgresql.Driver.makeConnection(Driver.java:443)
  at org.postgresql.Driver.connect(Driver.java:297)
  at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
  at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
  at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
  ... 5 more
Caused by: java.net.SocketTimeoutException: Read timed out
  at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
  at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
  at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
  at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
  at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
  at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
  at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
  at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
  at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
  at org.postgresql.core.PGStream.receiveChar(PGStream.java:465)
  at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:589)
  at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:191)
  at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
  ... 12 more
````

**Version:**
OpenMetadata 1.2.3 Helm Chart 1.2.5

**Additional context**
The problem indicates that [bug](https://postgrespro.com/list/thread-id/2510792):

A postgresql client in the same namespace can connect to the database by using the same credentials.

**Comment by tirelibirefe** [comment]
https://github.com/quarkusio/quarkus/issues/12022
