### ISSUE TITLE
Elasticsearch index creation fails when running ./bootstrap/bootstrap_storage.sh drop-create-all

### ISSUE THREAD

**Issue by ericson007** [open-metadata/OpenMetadata#14655]
**Affected module**
backend

**Describe the bug**
Bare-metal install:
Error during ./bootstrap/bootstrap_storage.sh drop-create-all

**CLI output**
09:08:00.128 [main] INFO  o.o.s.m.a.MigrationWorkflow - [MigrationWorkflow] WorkFlow Completed
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --es-create
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:561)
	at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:383)
	at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:334)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:540)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:712)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:679)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:660)
	at org.openmetadata.service.util.TablesInitializer.main(TablesInitializer.java:133)

**To Reproduce**
Install Airflow 2.8.0 and Elasticsearch 8.10.2
Create venv for Airflow and execute via systemd
Use postgresql as backend DB
Set Elasticsearch settings to xpath false to remove need for authentication
Run ./bootstrap/bootstrap_storage.sh drop-create-all

**Expected behavior**
Elastic search indexes should be created

**Version:**
 - OS: RHEL9.3
 - Python version:3.9
 - OpenMetadata version: 1.2.4
 - OpenMetadata Ingestion package version: N/A

**Additional context**
None

**Comment by ericson007** [comment]
**Workaround**

When initially installing, use OpenMetadata version 1.2.3. This work as intended.
Prepare the OpenMetadata version 1.2.4 directory.
Copy config file from 1.2.3 to 1.2.4
Migrate the database:
    ./bootstrap/bootstrap_storage.sh migrate

Start the server and it will work using 1.2.4

**Comment by harshach** [comment]
please use ./bootstrap/openmetadata-ops.sh reindex
