### ISSUE TITLE
Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]

### ISSUE THREAD

**Issue by PascalStehling** [open-metadata/OpenMetadata#14704]
**Affected module**
It affects the UI, as no Data is shown
![image](https://github.com/open-metadata/OpenMetadata/assets/33455644/2132c20f-1153-4b03-be41-b11df124e69a)

**Describe the bug**
After adding a Postgres database and ingestingthe metadata, the tables are loaded, but cannot be viewed in the Main Page. Everything is fine when viewed via the Settings.

**To Reproduce**

Not quite sure how to reproduce, but for ElasticSearch, an Instance from the ElasticSearch Cloud hosted via azure is used (smallest variant).

Also here is the Error stack trace, the real elastic host was obscured with `ELASTIC_CLOUD_PATH`

```
Suppressed: es.org.elasticsearch.client.ResponseException: method [POST], host [https://<ELASTIC_CLOUD_PATH>.elastic-cloud.com:443], URI [/table_search_index/_search?typed_keys=true&max_concurrent_shard_requests=5&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 400 Bad Request]
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Fielddata is disabled on [columnNames] in [table_search_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [columnNames] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "table_search_index",
        "node": "FiZL6wI8SAqdUm0cM7I98w",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Fielddata is disabled on [columnNames] in [table_search_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [columnNames] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Fielddata is disabled on [columnNames] in [table_search_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [columnNames] in order to load field data by uninverting the inverted index. Note that this can use significant memory.",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Fielddata is disabled on [columnNames] in [table_search_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [columnNames] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
      }
    }
  },
  "status": 400
}
2024-01-12T15:37:36.532081330Z 		at es.org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
2024-01-12T15:37:36.532086030Z 		at es.org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
2024-01-12T15:37:36.532090631Z 		at es.org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
2024-01-12T15:37:36.532095331Z 		at es.org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699)
2024-01-12T15:37:36.532100031Z 		at es.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171)
2024-01-12T15:37:36.532104732Z 		... 78 common frames omitted
2024-01-12T15:37:36.532112732Z Caused by: es.org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=Fielddata is disabled on [columnNames] in [table_search_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [columnNames] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]
2024-01-12T15:37:36.532118933Z 	at es.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:519)
2024-01-12T15:37:36.532123833Z 	at es.org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:430)
2024-01-12T15:37:36.532128534Z 	at es.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:460)
2024-01-12T15:37:36.532133234Z 	at es.org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:626)
2024-01-12T15:37:36.532137935Z 	at es.org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:170)
2024-01-12T15:37:36.532142535Z 	... 81 common frames omitted
2024-01-12T15:37:36.532151036Z Caused by: es.org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=Fielddata is disabled on [columnNames] in [table_search_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [columnNames] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]
2024-01-12T15:37:36.532157236Z 	at es.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:519)
2024-01-12T15:37:36.532161937Z 	at es.org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:430)
2024-01-12T15:37:36.532166637Z 	at es.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:460)
2024-01-12T15:37:36.532171337Z 	... 85 common frames omitted
```

**Expected behavior**
Just working normaly :D

**Version:**
For open Metadata, the latest Postgres docker setup ([version 1.2.4](https://github.com/open-metadata/OpenMetadata/releases/tag/1.2.4-release)) was used, but configured to use ElasticSearch from the ElasticCloud.

**Comment by harshach** [comment]
@PascalStehling did you try going Settings -> Application -> SearchReindexing Application -> Configure -> Run Now to re-index. 
It looks like indexes weren't created?

**Comment by harshach** [comment]
Also which version of ElasticSearch are you using, we need 8.x

**Comment by PascalStehling** [comment]
> @PascalStehling did you try going Settings -> Application -> SearchReindexing Application -> Configure -> Run Now to re-index. It looks like indexes weren't created?

Ok, that was the Problem. Thanks for your Help :)

Maybe as an Idea:
The ES instance was completely empty at the beginning, maybe you should check for that and generate everything automatically, instead of needing to do it by hand. And/Or add some Documentation about Indexing, whats its purpose, how to do it manually and where to find it. As its not quite Obvious and there is nothing about it in your whole Documentation.

**Comment by harshach** [comment]
it is done automatically by execute_migrate_all

**Comment by PascalStehling** [comment]
I ran it, but it seems it didn't worked. But atleast its working now :)

**Comment by Nicolas-Chollet** [comment]
Hello,

We just had a similar issue, but it sends an error even when triggered manually... any idea where it can come from ?

<img width="2068" alt="Screenshot 2024-01-15 at 18 18 05" src="https://github.com/open-metadata/OpenMetadata/assets/68106658/f7a64de3-0447-41c9-aac7-f626a00ed7d2">

Here is the error log:
`{"errorFrom":"sink","lastFailedReason":"[EsWriter][BulkItemResponse] Got Following Error Responses: [ {\n  \"lastFailedAt\" : 1705337545421,\n  \"lastFailedReason\" : \"Index Type: [database_service_search_index], Reason: [ElasticsearchException[Elasticsearch exception [type=unavailable_shards_exception, reason=[database_service_search_index][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[database_service_search_index][0]] containing [update {[database_service_search_index][182745fa-5d36-4167-bb21-03aeee545819], doc_as_upsert[true], doc[index {[null][null], source[n/a, actual length: [4kb], max length: 2kb]}], scripted_upsert[false], detect_noop[true]}]]]]] \\n Trace : [ElasticsearchException[Elasticsearch exception [type=unavailable_shards_exception, reason=[database_service_search_index][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[database_service_search_index][0]] containing [update {[database_service_search_index][182745fa-5d36-4167-bb21-03aeee545819], doc_as_upsert[true], doc[index {[null][null], source[n/a, actual length: [4kb], max length: 2kb]}], scripted_upsert[false], detect_noop[true]}]]]]\\n\\tat es.org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:519)\\n\\tat es.org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:430)\\n\\tat es.org.elasticsearch.action.bulk.BulkItemResponse.fromXContent(BulkItemResponse.java:128)\\n\\tat es.org.elasticsearch.action.bulk.BulkResponse.fromXContent(BulkResponse.java:184)\\n\\tat es.org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484)\\n\\tat es.org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:2105)\\n\\tat es.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2188)\\n\\tat es.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)\\n\\tat es.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105)\\n\\tat es.org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:620)\\n\\tat org.openmetadata.service.search.elasticsearch.ElasticSearchClient.bulk(ElasticSearchClient.java:1252)\\n\\tat org.openmetadata.service.search.elasticsearch.ElasticSearchIndexSink.write(ElasticSearchIndexSink.java:31)\\n\\tat org.openmetadata.service.search.elasticsearch.ElasticSearchIndexSink.write(ElasticSearchIndexSink.java:16)\\n\\tat org.openmetadata.service.apps.bundles.searchIndex.SearchIndexApp.entitiesReIndex(SearchIndexApp.java:204)\\n\\tat org.openmetadata.service.apps.bundles.searchIndex.SearchIndexApp.startApp(SearchIndexApp.java:131)\\n\\tat org.openmetadata.service.apps.AbstractNativeApplication.execute(AbstractNativeApplication.java:206)\\n\\tat org.quartz.core.JobRunShell.run(JobRunShell.java:202)\\n\\tat org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)\\n]\",\n  \"context\" : \"EsWriterContext: Encountered Error While Writing Data \\n Entity \\n ID : [182745fa-5d36-4167-bb21-03aeee545819] \"\n} ] ","lastFailedAt":1705337485401}
`
