### ISSUE TITLE
Unrecognized option: --es-create

### ISSUE THREAD

**Issue by thesal84** [open-metadata/OpenMetadata#14814]
**Affected module**
backend

**Describe the bug**
When we try to bootstrap a new OpenMetadata installation we get the error

```java
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --es-create
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:561)
        at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:383)
        at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:334)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:540)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:712)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:679)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:660)
        at org.openmetadata.service.util.TablesInitializer.main(TablesInitializer.java:133)
``` 
With the OpenMetadata version 1.2.2 it worked.

**To Reproduce**
Run the command ./bootstrap/bootstrap_storage.sh drop-create-all or a ./bootstrap/bootstrap_storage.sh es-create

**Expected behavior**
Create the indexes in ElasticSearch

**Version:**
 - OS: Rhel 8.8
 - Python version: 3.6.8
 - OpenMetadata version: 1.2.4

**Comment by thesal84** [comment]
@harshach thank you for your answer.
We also get the error when we use the command ./bootstrap/bootstrap_storage.sh drop-create-all

**Comment by harshach** [comment]
@thesal84 can you give us some details what are you trying to do . it would be great to have this in our slack instead of github issue. We can file a ticket if its indeed a bug. 
Come over to slack https://slack.open-metadata.org
