### ISSUE TITLE
Data Profiling error due to mutually exclusive tags (PII Sensitive tags) to single column 

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#14943]
**Affected module**
Ingestion Framework

**Describe the bug**
After going through the logs of the data profiling jobs at OM found below error happening

> metadata.ingestion.ometa.client.APIError: Tag labels PII.Sensitive and PII.NonSensitive are mutually exclusive and can't be assigned together
I guess profiler is trying to assign mutually exclusive tags to single column. 

**To Reproduce**
Use redshift as source and do profiling 

Here is the copy of the logs with the error
File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 212, in _one_request
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: [http://XXX:80/api/v1/tables/17a12599-701a-4150-970d-6c20c1ea5270](http://xxx/api/v1/tables/17a12599-701a-4150-970d-6c20c1ea5270)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/mixins/patch_mixin.py", line 180, in patch
    res = self.client.patch(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 301, in patch
    return self._request(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 189, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 230, in _one_request
    raise APIError(error, http_error) from http_error
metadata.ingestion.ometa.client.APIError: Tag labels PII.Sensitive and PII.NonSensitive are mutually exclusive and can't be assigned together

**Expected behavior**
The log shouls not have above error

**Version:**
 - Python version: 3.9
 - OpenMetadata version: 1.2.3

**Additional context**
[Slack link.](https://openmetadata.slack.com/archives/C02B6955S4S/p1705907834605079)

**Comment by pmbrull** [comment]
also, update the error message to show the FQN, not the table ID
