### ISSUE TITLE
The java cilent api got a bug

### ISSUE THREAD

**Issue by fanyo190** [open-metadata/OpenMetadata#15065]
When I use the Java Client API of OpenMetadata 1.3.0,I got a bug as fellow:

Caused by: java.lang.NullPointerException: Cannot invoke "org.openmetadata.client.ApiClient.getObjectMapper()" because "this.apiClient" is null
	at org.openmetadata.client.gateway.OpenMetadata.initClient(OpenMetadata.java:55)
	at org.openmetadata.client.gateway.OpenMetadata.<init>(OpenMetadata.java:43)
	at org.springblade.bigdata.dataassets.configuration.GatewayConfig.buildMetadataGateway(GatewayConfig.java:37)
	at org.springblade.bigdata.dataassets.configuration.GatewayConfig$$EnhancerBySpringCGLIB$$cde01ee8.CGLIB$buildMetadataGateway$8(<generated>)
	at org.springblade.bigdata.dataassets.configuration.GatewayConfig$$EnhancerBySpringCGLIB$$cde01ee8$$FastClassBySpringCGLIB$$6891da4e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.springblade.bigdata.dataassets.configuration.GatewayConfig$$EnhancerBySpringCGLIB$$cde01ee8.buildMetadataGateway(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 51 common frames omitted

**Comment by fanyo190** [comment]
the source of 1.3.0:
![image](https://github.com/open-metadata/OpenMetadata/assets/14494673/caaace6e-2f38-421b-8806-8dff2fbebe00)
the source of 1.2.5:
![image](https://github.com/open-metadata/OpenMetadata/assets/14494673/f92085af-e214-4b19-be93-90f709b266af)

**Comment by stlkielbasa** [comment]
I don't know if this is helpful but I have the same issue.  Thank you.

**Comment by harshach** [comment]
Fixed
