### ISSUE TITLE
AWS temporary security credentials is not supported

### ISSUE THREAD

**Issue by matef** [open-metadata/OpenMetadata#1523]
I tried to use my temp AWS session credentials to ingest from Glue catalog to local OpenMetadata setup. The Configuration has only two parameters which are the `aws_access_key_id` and `aws_secret_access_key`. There is a missing part here which is the `session_token` to overcome this issue I commented out the part where you populate those values so boto3 could pick up the current session.

```
[2021-12-01 16:36:29,488] ERROR    {metadata.ingestion.source.glue:144} - Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/glue.py", line 112, in ingest_tables
    for tables in self.glue.get_tables(DatabaseName=self.config.database)[
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetTables operation: The security token included in the request is invalid.
```

**Comment by harshach** [comment]
seems like a duplicate of https://github.com/open-metadata/OpenMetadata/issues/1522 . Lets close one of these.

**Comment by matef** [comment]
closing this one.
