### ISSUE TITLE
Configuration environment variable substitution is not always valid YAML.

### ISSUE THREAD

**Issue by mitchellmann** [open-metadata/OpenMetadata#15232]
/conf/openmetadata.yaml is currently templated with environment variables.

However, when a given environment variable is not valid YAML (due to not being encased in strings) it throws an error.
Error exampled below for string of "]edTSFx3iqHwfhR))[)Bw@7o".

I considered wrapping the above in a set of quotes, but it is actually being directly mounted in from a k8s secret.

Any thoughts on fixing this? Perhaps with improved substitution that supports YAML?
I am happy to contribute on this if a direction is decided.

Quick link to substitution: https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java#L192

```Exception in thread "main" io.dropwizard.configuration.ConfigurationParsingException: /opt/openmetadata/bootstrap/../conf/openmetadata.yaml has an error:
  * Malformed YAML at line: 127, column: 12; while parsing a block node
 in 'reader', line 126, column 13:
      password: ]edTSFx3iqHwfhR))[)Bw@7o
                ^
expected the node content, but found ']'
 in 'reader', line 126, column 13:
      password: ]edTSFx3iqHwfhR))[)Bw@7o
                ^

 at [Source: (ByteArrayInputStream); line: 126, column: 11]

        at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:277)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:101)
        at org.openmetadata.service.util.TablesInitializer.main(TablesInitializer.java:169)
Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block node
                ^
expected the node content, but found ']'
 in 'reader', line 126, column 13:
      password: ]edTSFx3iqHwfhR))[)Bw@7o
                ^

 at [Source: (ByteArrayInputStream); line: 126, column: 11]
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:28)

        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:422)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:541)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:100)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3084)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:86)
Caused by: while parsing a block node
 in 'reader', line 126, column 13:
      password: ]edTSFx3iqHwfhR))[)Bw@7o
                ^
expected the node content, but found ']'
 in 'reader', line 126, column 13:
      password: ]edTSFx3iqHwfhR))[)Bw@7o
                ^

        at org.yaml.snakeyaml.parser.ParserImpl.parseNode(ParserImpl.java:515)
        at org.yaml.snakeyaml.parser.ParserImpl.parseBlockNodeOrIndentlessSequence(ParserImpl.java:407)
        at org.yaml.snakeyaml.parser.ParserImpl.access$2100(ParserImpl.java:119)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:674)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:170)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:418)
        ... 8 more```

https://github.com/open-metadata/OpenMetadata/blob/5b0d75bf3a912db4d8cddb8504c8e7078639c557/openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java#L192

**Comment by harshach** [comment]
@tutte any ideas here

**Comment by mitchellmann** [comment]
When I initially looked at this, I almost wondered if the cleanest way would be pushing for a change/contributing in how dropwizard does config/substitution, rather than an OPMD change.

It's really an issue with YamlConfigurationFactory and EnvironmentVariableSubstitutor not working together well and missing the quotes.

**Comment by tutte** [comment]
I think we should allow values to be retrieved from environment variables directly instead of parsing the YAML and replacing them.
It is pretty standard in the industry (ie [MySQL](https://dev.mysql.com/doc/refman/8.3/en/environment-variables.html), [Ansible](https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html), [Keycloak](https://www.keycloak.org/server/configuration)).
