### ISSUE TITLE
Error trying to PATCH Table in Metadata pipeline with Databricks connector

### ISSUE THREAD

**Issue by Limp-monkey** [open-metadata/OpenMetadata#15347]
**Affected module**
Ingestion Framework

**Describe the bug**
When running the metadata pipeline in a Databricks service (databricks connector), it's ingests the metadata correctly for the first time. However, when running the pipeline again, the pipeline will succeed, but if fact it will not update any information on already ingested objects. 

In the pipeline log, we find the following errors during the second and later runs:
`[2024-02-26T01:17:19.987+0000] {sql_column_handler.py:120} DEBUG - Cannot obtain unique constraints for table [ad.users]: NotImplementedError
[2024-02-26T01:17:21.207+0000] {helpers.py:144} DEBUG - yield_table executed in 1.22s
[2024-02-26T01:17:21.298+0000] {patch_mixin.py:155} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/mixins/patch_mixin.py", line 148, in patch
    res = self.client.patch(
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 304, in patch
    return self._request(
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 192, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 215, in _one_request
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://openmetadata:8585/api/v1/tables/22b930a9-c06d-46e6-ad82-39a6665e17b2
[2024-02-26T01:17:21.298+0000] {patch_mixin.py:156} ERROR - Error trying to PATCH Table [22b930a9-c06d-46e6-ad82-39a6665e17b2]: 500 Server Error: Internal Server Error for url: http://openmetadata:8585/api/v1/tables/22b930a9-c06d-46e6-ad82-39a6665e17b2
`

**To Reproduce**

1. Create a Databricks connector service
2. Create a metadata ingestion pipeline
3. Run ingestion on a table
4. Change the description of the table in Databricks
5. Run the ingestion table again 
6. Check if the table definition was updated in OM and then the logs of the pipeline

**Expected behavior**
The table description should be updated in OM after the description was changed in Databricks and the metadata pipeline was run successfuly

**Version:**

    OS: AKS
    Python version: openmetadata ingestion 1.3
    OpenMetadata version: 1.3
    OpenMetadata Ingestion package version: [e.g. openmetadata-ingestion[docker]==1.3]
    OpenMetadata DB: Postgres

**Additional context**

**Comment by kenyyh** [comment]
This issue is also happened on PostgreSQL Database with same method reproduce, maybe there are some other datasource may also encounter this issue.  

1. Create a PostgreSQL Database service
2. Create a metadata ingestion pipeline
3. Run ingestion on a table
4. Change the column type of the table in PostgreSQL 
5. Run the ingestion table again
6. Check if the table definition was updated in OM and then the logs of the pipeline

**Comment by ulixius9** [comment]
This should be fixed after upgrading to latest binaries!
