### ISSUE TITLE
Upgrade caused column type change resulting in profiler error

### ISSUE THREAD

**Issue by kallison-trv** [open-metadata/OpenMetadata#15576]
It looks like the OM version upgrade (from 1.0.5 to 1.3.1) changed the data type of some existing columns named Version. They were all defined as string before, but were changed if the value looked like an int or float. So 0.0.1 stayed as string, 0.1 became float, and 1 became int. The old Version column was deleted and the new Version column was added with the new data type. The sourceHash column (internal use only) was also added in all cases at the same time.

I've attached two json files.
	• analysis.json is the schema file
	• Example Analysis.json is an example json file with the same format as the ones causing a problem.

We would like to know how to change the data type for the version column back to string without having to drop and recreate the entities.  I've rerun the Analyses ingestion and the data type did not change back to string, though perhaps a new file timestamp is not enough to cause an update.  We could not find a way in the UI or the API to update the data type of a column.

We discovered the data type change because the Analyses profiler run after the upgrade caused an error that seems to trace back to the data type change.  Below is part of the log showing the error.
[2024-03-12T23:14:42.063+0000] {profiler_interface.py:298} ERROR - SQALikeColumn(name='Version', type=<DataType.FLOAT: 'FLOAT'>) metric_type.value: unsupported operand type(s) for +: 'int' and 'str'
[2024-03-12T23:14:42.064+0000] {status.py:76} WARNING - SQALikeColumn(name='Version', type=<DataType.FLOAT: 'FLOAT'>) metric_type.value: unsupported operand type(s) for +: 'int' and 'str'
[2024-03-12T23:14:42.064+0000] {status.py:77} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/profiler/interface/pandas/profiler_interface.py", line 177, in _compute_static_metrics
    metric_resp = metric(column).df_fn(runner)
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/profiler/metrics/static/sum.py", line 53, in df_fn
    return sum(df[self.col.name].sum() for df in dfs)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/profiler/interface/pandas/profiler_interface.py", line 290, in compute_metrics
    row = self._get_metric_fn[metric_func.metric_type.value](
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/profiler/interface/pandas/profiler_interface.py", line 186, in _compute_static_metrics
    raise RuntimeError(exc)
RuntimeError: unsupported operand type(s) for +: 'int' and 'str'

[analysis.json](https://github.com/open-metadata/OpenMetadata/files/14604955/analysis.json)
[Example Analysis.json](https://github.com/open-metadata/OpenMetadata/files/14604957/Example.Analysis.json)

**Comment by harshach** [comment]
@ayush-shah any updates here?

**Comment by ayush-shah** [comment]
@harshach will be validating the same tomorrow, this seems to be an issue where we are safely evaluating an expression node and assigning a data type, but when it comes to profiler, on running metrics over DataFrames the data comes in as String because of pandas' default property, will validate the same and push a fix tomorrow
