### ISSUE TITLE
Fail to bootstrap mysql in main branch

### ISSUE THREAD

**Issue by zjffdu** [open-metadata/OpenMetadata#15945]
**Affected module**
backend

**Describe the bug**
Fail to bootstrap mysql when I run command in main branch (latest git hash: 39fc846fdbed2284d47dee157ca694ac7c7fe3d6)
```
sh bootstrap/bootstrap_storage.sh drop-create-all
```

Here's the error I got:

```
Enter QUIT to quit. If you still want to continue, please enter DELETE:
DELETE
Exception in thread "main" java.lang.NoSuchMethodError: 'javax.json.JsonValue javax.json.JsonReader.readValue()'
	at org.openmetadata.service.util.JsonUtils.readJson(JsonUtils.java:249)
	at org.openmetadata.service.search.SearchRepository.loadIndexMappings(SearchRepository.java:132)
	at org.openmetadata.service.search.SearchRepository.<init>(SearchRepository.java:123)
	at org.openmetadata.service.util.TablesInitializer.execute(TablesInitializer.java:301)
	at org.openmetadata.service.util.TablesInitializer.main(TablesInitializer.java:232)
```

**To Reproduce**

Follow the steps here to reproduce this issue: https://docs.open-metadata.org/v1.3.x/developers/contribute/build-code-and-run-tests/openmetadata-server

**Expected behavior**

**Version:**
 - OS: Mac
 - Python version: 3.9.7
 - OpenMetadata version: 1.4.0-SNAPSHOT
 - OpenMetadata Ingestion package version: 

**Additional context**

**Comment by sushi30** [comment]
Doe not reproduce in d1d964867dede9ccedc7c5960d0c96175d17c330

**Comment by sushi30** [comment]
lets connect on [slack #support channel](https://slack.open-metadata.org/). this appears to be a specific issue.

**Comment by zjffdu** [comment]
This is due to my local CLASSPATH setting, I have fixed it, thanks @sushi30
