### ISSUE TITLE
Error omiting all results on explore and search for any term.

### ISSUE THREAD

**Issue by heitorrbarros** [open-metadata/OpenMetadata#16199]
**Affected module**
The bug was impacting the explore menu on UI.

**Describe the bug**
When we try to search for a table or something else the error is raised.

**To Reproduce**

1. Go to explore menu 
![image](https://github.com/open-metadata/OpenMetadata/assets/3456754/9029a300-86c7-4100-b712-90d09a6b55fa)
2. Search for any table, for exemple `orders`
![image](https://github.com/open-metadata/OpenMetadata/assets/3456754/1a04ccc2-9c0a-4cfb-9d30-32957b8530ed)

**Expected behavior**
We expect the results that matches with the search terms.

**Version:**
 - OS: OpenMetadata container, docker.getcollate.io/openmetadata/server:1.3.4
 - OpenMetadata version: 1.3.4

**Additional context**
Stack trace:
```
ERROR [2024-05-09 12:36:10,416] [dw-1845 - GET /api/v1/search/query?q=orders&from=0&size=15&index=table_search_index] o.o.s.r.s.SearchResource - Got exception: [OpenSearchStatusException] / message [OpenSearch exception [type=search_phase_execution_exception, reason=all shards failed]] / related resource location: [org.openmetadata.service.resources.search.SearchResource.search](SearchResource.java:173)
os.org.opensearch.OpenSearchStatusException: OpenSearch exception [type=search_phase_execution_exception, reason=all shards failed]
 at os.org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:207)
 at os.org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2228)
 at os.org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2205)
 at os.org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1924)
 at os.org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1877)
 at os.org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1845)
 at os.org.opensearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1088)
 at org.openmetadata.service.search.opensearch.OpenSearchClient.search(OpenSearchClient.java:450)
 at org.openmetadata.service.search.SearchRepository.search(SearchRepository.java:643)
 at org.openmetadata.service.resources.search.SearchResource.search(SearchResource.java:173)
 at jdk.internal.reflect.GeneratedMethodAccessor948.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
 at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
 at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
 at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
 at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
 at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
 at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
 at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
 at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
 at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
 at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
 at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
 at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
 at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292)
 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
 at org.eclipse.jetty.servlets.HeaderFilter.doFilter(HeaderFilter.java:117)
 at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
 at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
 at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:318)
 at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
 at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
 at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
 at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
 at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
 at org.eclipse.jetty.server.Server.handle(Server.java:516)
 at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
 at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
 at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
 at java.base/java.lang.Thread.run(Thread.java:840)
 Suppressed: os.org.opensearch.client.ResponseException: method [POST], host [https://vpc-open-metadata-prod-tik6t5bw3yjwz7faf3vonup4hi.us-east-1.es.amazonaws.com:443], URI [/table_search_index/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"script_exception","reason":"runtime error","script_stack":["org.opensearch.index.fielddata.ScriptDocValues$Longs.get(ScriptDocValues.java:143)","org.opensearch.index.fielddata.ScriptDocValues$Longs.getValue(ScriptDocValues.java:137)","if (doc.containsKey('totalVotes') && doc['totalVotes'].value != null) { ","                                                      ^---- HERE"],"script":"double score = _score;if (doc.containsKey('totalVotes') && doc['totalVotes'].value != null) { score = score + doc['totalVotes'].value; }if (doc.containsKey('usageSummary') && doc['usageSummary.weeklyStats.count'].value != null) { score = score + doc['usage ...","lang":"painless","position":{"offset":76,"start":22,"end":94}}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"table_search_index","node":"wXwWei_tRgG7NN2p0C7c4A","reason":{"type":"script_exception","reason":"runtime error","script_stack":["org.opensearch.index.fielddata.ScriptDocValues$Longs.get(ScriptDocValues.java:143)","org.opensearch.index.fielddata.ScriptDocValues$Longs.getValue(ScriptDocValues.java:137)","if (doc.containsKey('totalVotes') && doc['totalVotes'].value != null) { ","                                                      ^---- HERE"],"script":"double score = _score;if (doc.containsKey('totalVotes') && doc['totalVotes'].value != null) { score = score + doc['totalVotes'].value; }if (doc.containsKey('usageSummary') && doc['usageSummary.weeklyStats.count'].value != null) { score = score + doc['usage ...","lang":"painless","position":{"offset":76,"start":22,"end":94},"caused_by":{"type":"illegal_state_exception","reason":"A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!"}}}]},"status":400}
  at os.org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
  at os.org.opensearch.client.RestClient.performRequest(RestClient.java:345)
  at os.org.opensearch.client.RestClient.performRequest(RestClient.java:320)
  at os.org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1911)
  ... 78 common frames omitted
```

**Comment by pmbrull** [comment]
hi @heitorrbarros, as I explained in the PR. Let's have first a discussion on slack https://slack.open-metadata.org/ and see what we can support. If needed, we can reopen this. Thanks
