### ISSUE TITLE
Great-Expectation OpenMetadataValidationAction fail in case on update

### ISSUE THREAD

**Issue by MHajjem** [open-metadata/OpenMetadata#16560]
**Affected module**
Ingestion Framework

**Describe the bug**
Can't to make update on testSuites from GX with OpenMetadataValidationAction.

**To Reproduce**
Launch GX with well configured OpenMetadataValidationAction  twice. The first one will pass the second will throw exception

Screenshots or steps to reproduce
Launch GX with well configured OpenMetadataValidationAction  twice. The first one will pass the second will throw exception

[2024-06-06, 13:53:18 CEST] {validation_operators.py:507} ERROR - Error running action with name update_openmetadata
Traceback (most recent call last):
  File "/var/dte/airflow/python/airflow-venv/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 478, in _run_actions
    action_result = self.actions[name].run(
  File "/var/dte/airflow/python/airflow-venv/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py", line 100, in run
    return self._run(
  File "/var/dte/airflow/python/airflow-venv/lib/python3.8/site-packages/metadata/great_expectations/action.py", line 153, in _run
    test_suite = self._check_or_create_test_suite(table_entity)
  File "/var/dte/airflow/python/airflow-venv/lib/python3.8/site-packages/metadata/great_expectations/action.py", line 251, in _check_or_create_test_suite
    TestSuite, table_entity.testSuite.fullyQualifiedName.__root__
AttributeError: 'str' object has no attribute '__root__'

**Expected behavior**
in case of a testsuite with same name. openmetadata should update lastRun and both results are shown on the test result Interface.

**Version:**
 - OS: centos
 - Python version: 3.8
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[great-expectation]==1.4.1.0`]

**Additional context**

**Comment by harshach** [comment]
@TeddyCr can you review this?

**Comment by harshach** [comment]
cc @sushi30
