### ISSUE TITLE
Python generated code is missing when using pip install git+https

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1670]
Step to reproduce it.

1. Create a venv and activate it.
2. ```pip install 'git+https://github.com/amiorin/OpenMetadata@fa46fdfb6061077dc2c922871e3b91d99cd3ab33#egg=openmetadata-ingestion[glue]&subdirectory=ingestion'```
3. ```metadata ingest -c examples/workflows/glue.json```

```
[2021-12-10 10:45:38,421] INFO     {metadata.cmd:74} - Using config: {'source': {'type': 'glue', 'config': {'region_name': 'us-west-2', 'service_name': 'glue_db', 'pipeline_service_name': 'glue_pipeline', 'storage_service_name': 's3'}}, 'sink': {'type': 'metadata-rest', 'config': {}}, 'metadata_server': {'type': 'metadata-server', 'config': {'api_endpoint': 'http://localhost:8585/api', 'auth_provider_type': 'no-auth'}}}
Traceback (most recent call last):
  File "/Users/amiorin/.pyenv/versions/test/bin/metadata", line 33, in <module>
    sys.exit(load_entry_point('openmetadata-ingestion==0.4.5.dev1', 'console_scripts', 'metadata')())
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/metadata/cmd.py", line 75, in ingest
    workflow = Workflow.create(workflow_config)
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 150, in create
    return cls(config)
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 61, in __init__
    source_class = self.get(
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 144, in get
    MyClass = getattr(importlib.import_module(module_name), class_name)
  File "/Users/amiorin/.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/amiorin/.pyenv/versions/3.9.7/envs/test/lib/python3.9/site-packages/metadata/ingestion/source/glue.py", line 19, in <module>
    from metadata.generated.schema.entity.data.database import Database
ModuleNotFoundError: No module named 'metadata.generated'
```

**Comment by pmbrull** [comment]
I think that this is intended. We are generating the sources and publishing them when deploying them to PyPI. However, if developers want to use specific branches, let's just run `make generate` after the `pip install` from git

**Comment by amiorin** [comment]
Ok.

**Comment by amiorin** [comment]
@pmbrull 
WDYT if we package the generated Python code in his own Python package (```openmetadata-ingestion-generated```) and we make it a default dependency so that users can test any commit with ```pip install git+http```?

Best
Alberto

**Comment by pmbrull** [comment]
Hi, I am not quite sure if that would be the best approach 🤔 

If we are playing with a commit that changes the JSON schemas (or comes from changes), we would have some misalignments. Is it a bit hard for me atm to find a clear win situation that pays for the added complexity. If users need specific commits, I am assuming they might be knowledgeable enough to prepare a `venv` and run `make generate`.

However, you are the ones having close checks with all the users, so I am happy to leave the decision up to you.

@harshach any thoughts here?

Thanks!

**Comment by amiorin** [comment]
Some users tried to test some branches with K8s. ```pip install``` in the Dockerfile is simpler for them.

The misalignment between module A and dependency B can be avoided with ```==``` in ```setup.py```.
