### ISSUE TITLE
Issue with Deploying OpenMetadata on AWS EKS

### ISSUE THREAD

**Issue by sairan-01** [open-metadata/OpenMetadata#17116]
Pre-installation Setup:

Persistent Volumes (PV) / Persistent Volume Claims (PVC)
RDS database using MariaDB
OpenSearch version 2.7
Required secrets configured
Deployment Details:
The deployment followed the instructions from the official [OpenMetadata deployment guide for EKS](https://docs.open-metadata.org/v1.4.x/deployment/kubernetes/eks).

Configurations:

OpenSearch credentials configured in elasticsearch-secrets
MariaDB credentials configured in mysql-secrets
Issue:
Despite setting the necessary parameters in openmetadata-values.prod.yaml, which should override default values when running the Helm command:

helm install openmetadata open-metadata/openmetadata --values openmetadata-values.prod.yaml
The configurations seem not to be utilized. I am encountering errors such as:

MySQLdb.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
During the database migration phase:

Migrating the OpenMetadata Schema.
Failed to db migration due to org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Schema `openmetadata_db` contains a failed migration to version 001!
This error persists, indicating an issue with the schema migration and database connection, despite correct configurations.

Request:
Could you please assist in resolving these issues, ensuring that the configurations in openmetadata-values.prod.yaml are recognized correctly during the Helm installation? Any guidance on troubleshooting this would be greatly appreciated.

**Comment by ddiljkan** [comment]
Is there any news regarding this issue? I have the same issue and would appreciate it if someone from OpenMetadata could at least acknowledge this with a comment. Is the issue with the configuration of the values in the yaml file or with the helm installation process?

**Comment by 804e** [comment]
I have the same issue
my helm install command
```sh
helm upgrade --install openmetadata open-metadata/openmetadata --values openmetadata-values.prod.yaml
```
error logs 
```
Migrating the OpenMetadata Schema.
Flyway Community Edition 9.22.3 by Redgate
See release notes here: https://rd.gt/416ObMi
Database: jdbc:mysql://10.0.1.147:3306/openmetadata (MySQL 8.0)
Current version of schema `openmetadata`: 005
Failed to db migration due to 
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Schema `openmetadata` contains a failed migration to version 005 !
 at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:218)
 at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
 at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
 at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
 at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
 at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
 at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
 at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:188)
 at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:213)
 at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
 at org.openmetadata.service.util.OpenMetadataOperations.migrate(OpenMetadataOperations.java:349)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:569)
 at picocli.CommandLine.executeUserObject(CommandLine.java:2070)
 at picocli.CommandLine.access$1500(CommandLine.java:148)
 at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
 at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
 at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
 at picocli.CommandLine.execute(CommandLine.java:2174)
 at org.openmetadata.service.util.OpenMetadataOperations.main(OpenMetadataOperations.java:955)
```
openmetadata-values.prod.yaml file
```yaml
openmetadata:
  config:
    elasticsearch:
      host: "10.0.2.150"
      searchType: elasticsearch
      port: 9200
      scheme: http
      connectionTimeoutSecs: 5
      socketTimeoutSecs: 60
      keepAliveTimeoutSecs: 600
      batchSize: 10
      auth:
        enabled: true
        username: "elastic"
        password:
          secretRef: elasticsearch-secrets
          secretKey: openmetadata-elasticsearch-password
    database:
      host: "10.0.1.147"
      port: 3306
      driverClass: com.mysql.cj.jdbc.Driver
      dbScheme: mysql
      databaseName: openmetadata
      auth:
        username: openmetadata
        password:
          secretRef: mysql-secrets
          secretKey: openmetadata-mysql-password
    pipelineServiceClientConfig:
      enabled: true
      apiEndpoint: "http://airflow-webserver:8080"
      metadataApiEndpoint: "http://openmetadata:8585/api"
      auth:
        username: "admin"
        password:
          secretRef: airflow-secrets
          secretKey: openmetadata-airflow-password

```

**Comment by pmbrull** [comment]
please reach out in slack.open-metadata.org, we can give a hand in there
