### ISSUE TITLE
Error get sample data in Oracle when column Type=Raw

### ISSUE THREAD

**Issue by AlexeySmirnov74** [open-metadata/OpenMetadata#17658]
**Affected module**
Sample Data output

**Describe the bug**
Error get sample data in Oracle when column Type=Raw

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1: invalid start byte

**To Reproduce**

1. Create a table TESTTABLE3 with column type=Raw:

```
CREATE TABLE DQ."TESTTABLE3"(
       COL1 NUMBER,
       COL2 RAW(10)
       )  DEFAULT COLLATION "USING_NLS_COMP"

INSERT INTO DQ.TESTTABLE3 (COL1,COL2)VALUES(0,'FFF')
```

2. Go to Profiler and scan table ^TESTTABLE3.*

Results:

![image](https://github.com/user-attachments/assets/c74f4760-1402-4cd8-87c7-cd4062940827)

**Expected behavior**

Shows sample data with column type Raw

**Version:**
 - OS: Ubuntu 22.04.4 LTS
 - Docker version 27.0.3
 - Python version: --
 - OpenMetadata version: 1.4.7.0
 - OpenMetadata Ingestion package version: 1.4.7
 - Oracle: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0
 - scheme: oracle+cx_oracle
 - instantClientDirectory: /usr/lib/oracle/19.23
 - encoding: UTF-8

**Additional context**
Error Log TESTTABLE3:

```
[2024-08-28T08:43:29.730+0000] {metadata_rest.py:534} DEBUG - Successfully ingested profile metrics for oracle-il.IL.dq.TESTTABLE3
[2024-08-28T08:43:29.734+0000] {table_mixin.py:76} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/mixins/table_mixin.py", line 73, in ingest_table_sample_data
    data=sample_data.json(),
  File "pydantic/main.py", line 504, in pydantic.main.BaseModel.json
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 88, in pydantic.json.pydantic_encoder
  File "pydantic/json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1: invalid start byte
[2024-08-28T08:43:29.735+0000] {table_mixin.py:77} WARNING - Error trying to PUT sample data for oracle-il.IL.dq.TESTTABLE3: 'utf-8' codec can't decode byte 0xff in position 1: invalid start byte
[2024-08-28T08:43:29.735+0000] {status.py:76} WARNING - Error trying to ingest sample data for table

```

**Comment by ayush-shah** [comment]
https://github.com/user-attachments/assets/bc0fcdb9-9e67-44d5-84b8-21eaf106cf07

Not able to reproduce in 1.7.2
