### ISSUE TITLE
Ingesting DBT Data is not working - OMD 1.5.2

### ISSUE THREAD

**Issue by mazenorabi** [open-metadata/OpenMetadata#17781]
**Affected module**
Ingestion Framework

**Describe the bug**
Running dbt workflow externally to ingest dbt data return many errors as below and nothing happen:
```
nodes.`model.snowflake_dbt.sessions`.Nodes7.latest_version
[   Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
     For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
nodes.`model.snowflake_dbt.sessions`.Nodes7.deprecation_date
   Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
     For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden]
 Traceback (most recent call last):
   File "/ingestion/main.py", line 114, in <module>
     main()
  File "/ingestion/main.py", line 108, in main
  workflow.raise_from_status()
 File "/usr/local/lib/python3.10/site-packages/metadata/workflow/workflow_status_mixin.py", line 134, in raise_from_status
raise err
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/workflow_status_mixin.py", line 131, in raise_from_status     
self.raise_from_status_internal(raise_warnings)
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/ingestion.py", line 150, in raise_from_status_internal
  raise WorkflowExecutionError(
 metadata.config.common.WorkflowExecutionError: dbt reported errors: dbt Summary: [0 Records, [0 Updated Records, 0 Warnings, 1 Errors, 0 Filtered]
```

**To Reproduce**

Use this yaml config to run DBT ingestion (run the ingestion framework as docker image on K8s):
```
source:
  type: dbt
  serviceName: {{ DATABASE_SERVICE_NAME }}
  sourceConfig:
    config:
      type: DBT
      dbtConfigSource:
        dbtConfigType: local
        dbtCatalogFilePath: {{ DBT_CATALOG_PATH }}
        dbtManifestFilePath: {{ DBT_MANIFEST_PATH }}
        dbtRunResultsFilePath: {{ DBT_RUN_RESULTS_PATH }}
      dbtUpdateDescriptions: true
      includeTags: true
      dbtClassificationName: {{ DBT_CLASSIFICATION_NAME }}
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: DEBUG
  openMetadataServerConfig:
    hostPort: https://openmetadata/api
    authProvider: openmetadata
    verifySSL: ignore
    securityConfig:
      jwtToken: ***
```

**Expected behavior**
to ingest DBT Data, see lineage and DBT tab on UI.

**Version:**
 - OS: K8s
 - Python version: 3.10
 - OpenMetadata version: 1.5.2 Upgraded from 1.4.7
 - OpenMetadata Ingestion package version: ingestion-base==1.5.2
 - DBT version: 1.8.5
 - Warehouse: Snowflake

**Additional context**

**Comment by LeoLuo123** [comment]
We also see this issue. Wondering when this can be fixed

**Comment by ulixius9** [comment]
closing by https://github.com/yu-iskw/dbt-artifacts-parser/pull/130

upgrading to dbt-artifacts-parser==0.8.0 fixes this issue
