### ISSUE TITLE
Usage ingestion fails for PostgreSQL with Entity already exists error

### ISSUE THREAD

**Issue by Prajwal214** [open-metadata/OpenMetadata#18154]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? -- Ingestion

**Describe the bug**

-- Usage ingestion for PostgreSQL in OpenMetadata v1.5.6 fails due to a 409 Conflict error when processing usage queries. The error message `Entity already exists` is raised, which should ideally be handled gracefully by the ingestion process and not cause a failure.

**To Reproduce**

Screenshots or steps to reproduce

```
[2024-10-04T00:25:22.564+0000] {base.py:290} INFO - Table Usage: Processed 218 records, updated 0 records, filtered 0 records, found 0 errors
[2024-10-04T00:25:22.564+0000] {base.py:290} INFO - OpenMetadata: Processed 0 records, updated 0 records, filtered 0 records, found 3 errors
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://...........:8585/api/v1/queries
    raise APIError(error, http_error) from http_error
metadata.ingestion.ometa.client.APIError: Entity already exists
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://.........:8585/api/v1/queries
    raise APIError(error, http_error) from http_error
metadata.ingestion.ometa.client.APIError: Entity already exists
[2024-10-04T00:26:22.564+0000] {base.py:290} INFO - Postgres: Processed 1 records, updated 0 records, filtered 0 records, found 0 errors
```
**Expected behavior**

-- The ingestion process should detect that the entity (query) already exists and either skip or update the existing entity, without throwing an error. This should not cause the entire ingestion job to fail.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] OM v1.5.6
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] v1.5.6

**Additional context**

**Comment by Prajwal214** [comment]
For Oracle Metadata Ingestion Also we are seeing same issue,

```
[2024-10-08T13:41:28.250+0000] {common.py:304} INFO - Sending failed status from callback...
[2024-10-08T13:41:28.257+0000] {server_mixin.py:74} INFO - OpenMetadata client running with Server version [1.5.4] and Client version [1.5.4.1]
[2024-10-08T13:41:28.257+0000] {common.py:310} INFO - Sending status to Ingestion Pipeline {service}.{service}_metadata_TgRU37zZ
[2024-10-08T13:41:28.362+0000] {ingestion_pipeline_mixin.py:52} DEBUG - Created Pipeline Status for pipeline {service}.{service}_metadata_TgRU37zZ: runId='0d1912c2-f0d2-49da-947a-7ab47dffdb00' pipelineState=<PipelineState.failed: 'failed'> startDate=Timestamp(root=1728394259757) timestamp=Timestamp(root=1728394259757) endDate=Timestamp(root=1728394888273) status=IngestionStatus(root=[StepSummary(name='Oracle', records=1312, updated_records=284, warnings=0, errors=0, filtered=237, failures=[]), StepSummary(name='OpenMetadata', records=1310, updated_records=283, warnings=0, errors=2, filtered=0, failures=[StackTraceError(name="name=None displayName=None description=None owners=None tags=None query=SqlQuery(root='INSERT INTO FL_PAYMENTITEM ( ID, IDOWNER, IDKIND, IDCONS, FAMOUNT, IDPROMOBM ) SELECT FL_PAYMENTITEMID.NEXTVAL , :B5 , :B4 , D0.IDPERSON , D0.FAMOUNT , :B3 FROM ( SELECT /*+ cardinality(t 100) */ T.IDPERSON , SUM( NVL( T.FAMMOUNT, PP.FSUM * NVL( PP.NQUANTOR, 1 ) ) ) FAMOUNT FROM TABLE( :B1 ) T JOIN FL_PROMOPERSON PP ON PP.IDPROMO = T.IDPROMO AND PP.IDPERSON = T.IDPERSON JOIN XC_PERSON XP ON XP.ID = T.IDPERSON AND XP.BACTUAL = 1 WHERE T.IDPROMO = :B3 AND NVL( T.IDCURRENCY, PP.IDCURR ) = :B2 GROUP BY T.IDPERSON ) D0 WHERE D0.FAMOUNT > 0 ') query_type='INSERT' exclude_usage=None duration=None users=None usedBy=None queryDate=Timestamp(root=1728385800000) queryUsedIn=None triggeredBy=EntityReference(id=Uuid(root=UUID('9d5cd5f9-60dc-431c-b30f-1dac2f632a2a')), type='storedProcedure', name=None, fullyQualifiedName=None, description=None, displayName=None, deleted=None, inherited=None, href=None) processedLineage=True service=FullyQualifiedEntityName(root='STANDBY') domain=None", error="Failed to ingest name=None displayName=None description=None owners=None tags=None query=SqlQuery(root='INSERT INTO FL_PAYMENTITEM ( ID, IDOWNER, IDKIND, IDCONS, FAMOUNT, IDPROMOBM ) SELECT FL_PAYMENTITEMID.NEXTVAL , :B5 , :B4 , D0.IDPERSON , D0.FAMOUNT , :B3 FROM ( SELECT /*+ cardinality(t 100) */ T.IDPERSON , SUM( NVL( T.FAMMOUNT, PP.FSUM * NVL( PP.NQUANTOR, 1 ) ) ) FAMOUNT FROM TABLE( :B1 ) T JOIN FL_PROMOPERSON PP ON PP.IDPROMO = T.IDPROMO AND PP.IDPERSON = T.IDPERSON JOIN XC_PERSON XP ON XP.ID = T.IDPERSON AND XP.BACTUAL = 1 WHERE T.IDPROMO = :B3 AND NVL( T.IDCURRENCY, PP.IDCURR ) = :B2 GROUP BY T.IDPERSON ) D0 WHERE D0.FAMOUNT > 0 ') query_type='INSERT' exclude_usage=None duration=None users=None usedBy=None queryDate=Timestamp(root=1728385800000) queryUsedIn=None triggeredBy=EntityReference(id=Uuid(root=UUID('9d5cd5f9-60dc-431c-b30f-1dac2f632a2a')), type='storedProcedure', name=None, fullyQualifiedName=None, description=None, displayName=None, deleted=None, inherited=None, href=None) processedLineage=True service=FullyQualifiedEntityName(root='STANDBY') domain=None due to api request failure: Entity already exists", stackTrace='Traceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 243, in _one_request\n    resp.raise_for_status()\n  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://openmetadata-server:8585/api/v1/queries\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/sink/metadata_rest.py", line 146, in _run\n    return self._run_dispatch(record)\n  File "/usr/local/lib/python3.10/functools.py", line 926, in _method\n    return method.__get__(obj, cls)(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/sink/metadata_rest.py", line 137, in _run_dispatch\n    return self.write_create_request(record)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/sink/metadata_rest.py", line 167, in write_create_request\n    created = self.metadata.create_or_update(entity_request)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/ometa_api.py", line 276, in create_or_update\n    return self._create(data=data, method="put")\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/ometa_api.py", line 267, in _create\n    resp = fn(self.get_suffix(entity), data=data.model_dump_json())\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/execution_time_tracker.py", line 195, in inner\n    result = func(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 324, in put\n    return self._request("PUT", path, data)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 212, in _request\n    return self._one_request(method, url, opts, retry)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 263, in _one_request\n    raise APIError(error, http_error) from http_error\nmetadata.ingestion.ometa.client.APIError: Entity already exists\n'), StackTraceError(name="name=None displayName=None description=None owners=None tags=None query=SqlQuery(root='INSERT INTO FL_PAYMENTITEM ( ID, IDOWNER, IDKIND, IDCONS, FAMOUNT, IDPROMOBM ) SELECT FL_PAYMENTITEMID.NEXTVAL , :B5 , :B4 , D0.IDPERSON , D0.FAMOUNT , :B3 FROM ( SELECT /*+ cardinality(t 100) */ T.IDPERSON , SUM( NVL( T.FAMMOUNT, PP.FSUM * NVL( PP.NQUANTOR, 1 ) ) ) FAMOUNT FROM TABLE( :B1 ) T JOIN FL_PROMOPERSON PP ON PP.IDPROMO = T.IDPROMO AND PP.IDPERSON = T.IDPERSON JOIN XC_PERSON XP ON XP.ID = T.IDPERSON AND XP.BACTUAL = 1 WHERE T.IDPROMO = :B3 AND NVL( T.IDCURRENCY, PP.IDCURR ) = :B2 GROUP BY T.IDPERSON ) D0 WHERE D0.FAMOUNT > 0 ') query_type='INSERT' exclude_usage=None duration=None users=None usedBy=None queryDate=Timestamp(root=1728385800000) queryUsedIn=None triggeredBy=EntityReference(id=Uuid(root=UUID('9d5cd5f9-60dc-431c-b30f-1dac2f632a2a')), type='storedProcedure', name=None, fullyQualifiedName=None, description=None, displayName=None, deleted=None, inherited=None, href=None) processedLineage=True service=FullyQualifiedEntityName(root='{service}') domain=None", error="Failed to ingest name=None displayName=None description=None owners=None tags=None query=SqlQuery(root='INSERT INTO FL_PAYMENTITEM ( ID, IDOWNER, IDKIND, IDCONS, FAMOUNT, IDPROMOBM ) SELECT FL_PAYMENTITEMID.NEXTVAL , :B5 , :B4 , D0.IDPERSON , D0.FAMOUNT , :B3 FROM ( SELECT /*+ cardinality(t 100) */ T.IDPERSON , SUM( NVL( T.FAMMOUNT, PP.FSUM * NVL( PP.NQUANTOR, 1 ) ) ) FAMOUNT FROM TABLE( :B1 ) T JOIN FL_PROMOPERSON PP ON PP.IDPROMO = T.IDPROMO AND PP.IDPERSON = T.IDPERSON JOIN XC_PERSON XP ON XP.ID = T.IDPERSON AND XP.BACTUAL = 1 WHERE T.IDPROMO = :B3 AND NVL( T.IDCURRENCY, PP.IDCURR ) = :B2 GROUP BY T.IDPERSON ) D0 WHERE D0.FAMOUNT > 0 ') query_type='INSERT' exclude_usage=None duration=None users=None usedBy=None queryDate=Timestamp(root=1728385800000) queryUsedIn=None triggeredBy=EntityReference(id=Uuid(root=UUID('9d5cd5f9-60dc-431c-b30f-1dac2f632a2a')), type='storedProcedure', name=None, fullyQualifiedName=None, description=None, displayName=None, deleted=None, inherited=None, href=None) processedLineage=True service=FullyQualifiedEntityName(root='{service}') domain=None due to api request failure: Entity already exists", stackTrace='Traceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 243, in _one_request\n    resp.raise_for_status()\n  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://openmetadata-server:8585/api/v1/queries\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/sink/metadata_rest.py", line 146, in _run\n    return self._run_dispatch(record)\n  File "/usr/local/lib/python3.10/functools.py", line 926, in _method\n    return method.__get__(obj, cls)(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/sink/metadata_rest.py", line 137, in _run_dispatch\n    return self.write_create_request(record)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/sink/metadata_rest.py", line 167, in write_create_request\n    created = self.metadata.create_or_update(entity_request)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/ometa_api.py", line 276, in create_or_update\n    return self._create(data=data, method="put")\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/ometa_api.py", line 267, in _create\n    resp = fn(self.get_suffix(entity), data=data.model_dump_json())\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/execution_time_tracker.py", line 195, in inner\n    result = func(*args, **kwargs)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 324, in put\n    return self._request("PUT", path, data)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 212, in _request\n    return self._one_request(method, url, opts, retry)\n  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/ometa/client.py", line 263, in _one_request\n    raise APIError(error, http_error) from http_error\nmetadata.ingestion.ometa.client.APIError: Entity already exists\n')])])
[2024-10-08T13:41:28.393+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 500 for task ingestion_task (OpenMetadata
```

**Comment by mohityadav766** [comment]
@harshach here for OM the Query is only created once, and is bound to a service 
What happens in case the same query is used across services?

**Comment by akashverma0786** [comment]
I am working on this.
