### ISSUE TITLE
Quicksight Dashboard Lineage ingestion does not support Custom SQL

### ISSUE THREAD

**Issue by dan-marra-ebrs** [open-metadata/OpenMetadata#18197]
Consider the following log output snippet for ingestion:

```
[2024-10-09T16:55:28.848+0000] {topology_runner.py:395} DEBUG - No changes detected for Dashboard 'Quicksight Test-1.45b8abbc-141f-4b66-ad5a-75126eea2599'
[2024-10-09T16:55:28.848+0000] {topology_runner.py:231} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.api.lineage.addLineage.AddLineageRequest'> processor='yield_dashboard_lineage' nullable=True must_return=False overwrite=True consumer=['dashboard_service'] context=None store_all_in_context=False clear_context=False store_fqn=False cache_entities=False use_cache=False
[2024-10-09T16:55:29.381+0000] {status.py:91} WARNING - Error to yield dashboard lineage details for DB service name [Athena Test-1]: "We currently don't support lineage to ['CustomSql']"
[2024-10-09T16:55:29.381+0000] {status.py:92} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/dashboard/quicksight/metadata.py", line 243, in yield_dashboard_lineage_details
    raise KeyError(
KeyError: "We currently don't support lineage to ['CustomSql']"
[2024-10-09T16:55:29.381+0000] {status.py:91} WARNING - Error to yield dashboard lineage details for DB service name [Athena Test-1]: local variable 'data_source_resp' referenced before assignment
[2024-10-09T16:55:29.381+0000] {status.py:92} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/dashboard/quicksight/metadata.py", line 261, in yield_dashboard_lineage_details
    schema_name = data_source_resp.schema_name
UnboundLocalError: local variable 'data_source_resp' referenced before assignment
```

We'll focus on the `"We currently don't support lineage to ['CustomSql']"` part. This is related to the following code snippet:

https://github.com/open-metadata/OpenMetadata/blob/1.5.6-release/ingestion/src/metadata/ingestion/source/dashboard/quicksight/metadata.py#L244

```python
            for dataset_id in dataset_ids or []:
                for data_source in (
                    list(
                        self.client.describe_data_set(
                            AwsAccountId=self.aws_account_id, DataSetId=dataset_id
                        )["DataSet"]["PhysicalTableMap"].values()
                    )
                    or []
                ):
                    try:
                        if not data_source.get("RelationalTable"):
                            raise KeyError(
                                f"We currently don't support lineage to {list(data_source.keys())}"
                            )
                        data_source_resp = DataSourceResp(
                            **data_source["RelationalTable"]
                        )
                    except (KeyError, ValidationError) as err:
                        yield Either(
                            left=StackTraceError(
                                name="Lineage",
                                error=(
                                    "Error to yield dashboard lineage details for DB service"
                                    f" name [{db_service_name}]: {err}"
                                ),
                                stackTrace=traceback.format_exc(),
                            )
                        )
```

The problem here is that only `RelationalTable` is looked for. BUT, if a datasource is based on a custom SQL statement, the format of a quicksight exported object will look something like this:

```json
{
  "resourceType": "dataset",
  "dataSetId": "ae8906d1-66ff-4df7-9c9b-c626dc950ff1",
  "name": "my_dataset",
  "physicalTableMap": {
    "955d224f-6497-40b9-8fa9-bdadb0679583": {
      "customSql": {
        "dataSourceArn": "arn:aws:quicksight:us-east-1:1234567890123:datasource/204359b4-7833-4010-8fa0-f8c73f9ce9e5",
        "name": "sql_name",
        "sqlQuery": "SELECT foo \r\n FROM mydb.bar \r\n WHERE biz='baz'",
  
         ... other fields ...        
```

In a case like this, the SQL should be parsed out to determine lineage

A short term solution for users could be to just use views instead of directly using custom SQL, but this is difficult (if not impossible) to police; lineage would slip through the cracks. Ideally the custom SQL is just supported.

**Comment by ulixius9** [comment]
closing by https://github.com/open-metadata/OpenMetadata/pull/18348
