### ISSUE TITLE
Snowflake Comment/Table Description Ingestion Failing

### ISSUE THREAD

**Issue by ojgregory-uoe** [open-metadata/OpenMetadata#18257]
**Affected module**
Metadata ingestion

**Describe the bug**
I'm finding that we're not getting the table descriptions coming through from snowflake even with the overwrite metadata option enabled. I'm getting this message in the log

```
[2024-10-14T13:21:52.613+0000] {common_db_source.py:283} DEBUG - Traceback (most recent call last):  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/common_db_source.py", line 280, in get_table_description 
 table_info: dict = inspector.get_table_comment(table_name, schema_name) 
 File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 652, in get_table_comment 
 return self.dialect.get_table_comment( 
 File "<string>", line 2, in get_table_comment 
 File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache 
 ret = fn(self, con, *args, **kw) 
 File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/snowflake/utils.py", line 239, in get_table_comment 
 return get_table_comment_wrapper( 
 File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/sqlalchemy_utils.py", line 43, in get_table_comment_wrapper 
 self.get_all_table_comments(connection, query) 
 File "<string>", line 2, in get_all_table_comments 
 File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 47, in cache 
 return fn(self, con, *args, **kw) 
 File "/home/airflow/.local/lib/python3.10/site-packages/metadata/utils/sqlalchemy_utils.py", line 35, in get_all_table_comments 
 self.all_table_comments[(table.table_name, table.schema)] = table.table_comment 
AttributeError: Could not locate column in row for column 'table_comment' 
[2024-10-14T13:21:52.613+0000] {common_db_source.py:284} WARNING - Table description error for table [INTEGRATED.TABLE]: Could not locate column in row for column 'table_comment'
```

From the query that is running on the snowflake side I can see that it's returning all of the comments in the DB so can't see why it's not loading it

**To Reproduce**
Any table with a description is causing this message

**Expected behavior**
I would expect the comment to be loaded into the description for the table

**Version:**
 - OpenMetadata version: 1.5.5

**Additional context**
I raised this on slack and was redirected here

**Comment by akashverma0786** [comment]
Hi @ojgregory-uoe 
I tried replicating the error, 
but I was able too successfully ingest comments from the  snowflake table

![Image](https://github.com/user-attachments/assets/07fbc9af-0ea3-449d-8199-d487aa60457e)

overrideMetadata: true

![Image](https://github.com/user-attachments/assets/ac300357-a9e2-4251-a637-fc5fed41491d)

Try upgrading to the latest version of OMD, Thanks.
