### ISSUE TITLE
Wrong logic for version check in API

### ISSUE THREAD

**Issue by imishchuk-tsgs** [open-metadata/OpenMetadata#18349]
**Affected module**
API

**Describe the bug**
Current version check in [openmetadata-airflow-apis/opendata_managed_apis/api/utils.py](https://github.com/open-metadata/OpenMetadata/blob/8e87fb8454ff2c74ab6cb831d818cdd2d6556f2c/openmetadata-airflow-apis/openmetadata_managed_apis/api/utils.py#L113) is done lexiographically, instead of proper version comparison

```
 if airflow_version >= "2.6":
```

This works fine for Airflow version `2.9.*` but breaks for `2.10.*`

```
Process ScanDagsTask-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/airflow/.local/lib/python3.12/site-packages/openmetadata_managed_apis/api/utils.py", line 116, in run
    scheduler_job = self._run_old_scheduler_job()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openmetadata_managed_apis/api/utils.py", line 148, in _run_old_scheduler_job
    from airflow.jobs.scheduler_job import SchedulerJob
ModuleNotFoundError: No module named 'airflow.jobs.scheduler_job'
```

Airflow version

```
airflow version
2.10.2
```

**To Reproduce**

* Use Airflow version `2.10.*` and try to create ingestion DAG

**Expected behavior**
Version comparison is done correctly, i.e. `2.10.*` is newer than `2.9.*`

**Version:**
 - OS: "Debian GNU/Linux 12 (bookworm)"
 - Python version: Python 3.12.6
 - OpenMetadata version: 1.5.6
 - OpenMetadata Ingestion package version: openmetadata-ingestion[postgres]==1.5.6

**Additional context**

```
c = "2.9"

if c >= "2.6":
    print("OK")
else:
    print("NOK")

OK
```

```
c = "2.10"

if c >= "2.6":
    print("OK")
else:
    print("NOK")

NOK
```

Fixed

```
from packaging import version

c = "2.10"

if version.parse(c) >= version.parse("2.6"):
    print("OK")
else:
    print("NOK")

OK
```

**Comment by imishchuk-tsgs** [comment]
https://github.com/open-metadata/OpenMetadata/pull/18352
