### ISSUE TITLE
airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend exception using Airflow 2.10.2

### ISSUE THREAD

**Issue by alexsanderp** [open-metadata/OpenMetadata#18402]
**Affected module**
Ingestion Framework

**Describe the bug**
When installing the ingestion library in an existing Airflow version 2.10.2, we are receiving the following error during the start of the DAG Processor when using the environment variable:

AIRFLOW__LINEAGE__BACKEND: airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend

```
Defaulted container "dag-processor" out of: dag-processor, dag-processor-log-groomer, minio-sync, wait-for-airflow-migrations (init), wait-for-minio (init)
....................
ERROR! Maximum number of retries (20) reached.

Last check result:
$ airflow db check
/home/airflow/.local/lib/python3.11/site-packages/airflow/configuration.py:765 FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.
cannot import name 'IncEx' from 'pydantic.main' (/home/airflow/.local/lib/python3.11/site-packages/pydantic/main.py)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/configuration.py", line 1219, in getimport
    return import_string(full_qualified_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow_provider_openmetadata/lineage/backend.py", line 21, in <module>
    from airflow_provider_openmetadata.lineage.config.loader import (
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow_provider_openmetadata/lineage/config/loader.py", line 22, in <module>
    from metadata.generated.schema.entity.services.connections.metadata.openMetadataConnection import (
  File "/home/airflow/.local/lib/python3.11/site-packages/metadata/generated/schema/entity/services/connections/metadata/openMetadataConnection.py", line 13, in <module>
    from metadata.ingestion.models.custom_pydantic import BaseModel
  File "/home/airflow/.local/lib/python3.11/site-packages/metadata/ingestion/models/custom_pydantic.py", line 24, in <module>
    from pydantic.main import IncEx
ImportError: cannot import name 'IncEx' from 'pydantic.main' (/home/airflow/.local/lib/python3.11/site-packages/pydantic/main.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/__init__.py", line 74, in <module>
    settings.initialize()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py", line 782, in initialize
    import_local_settings()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py", line 730, in import_local_settings
    import airflow_local_settings
  File "/opt/airflow/config/airflow_local_settings.py", line 29, in <module>
    from airflow.models.dag import DAG, TaskInstance
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dag.py", line 103, in <module>
    from airflow.models.baseoperator import BaseOperator
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 570, in <module>
    class BaseOperator(AbstractOperator, metaclass=BaseOperatorMeta):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1349, in BaseOperator
    @apply_lineage
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/lineage/__init__.py", line 73, in apply_lineage
    _backend = get_backend()
               ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/lineage/__init__.py", line 42, in get_backend
    clazz = conf.getimport("lineage", "backend", fallback=None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/configuration.py", line 1222, in getimport
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "backend" key in "lineage" section. Current value: "airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend".
```

**To Reproduce**

Install the packages in the official Airflow Docker image and try to start Airflow using the DAG Processor with the variable set.

**Expected behavior**
I was able to use my Airflow to run the OpenMetadata DAGs.

**Version:**
 - OS: Airflow Docker Image 2.10.2 with Dag Processor
 - Python version: 3.11
 - OpenMetadata version: 1.5.7
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.5.7.0 and openmetadata-managed-apis==1.5.7.0

**Comment by sushi30** [comment]
Can you share which version of pydantic is installed in this machine?

**Comment by alexsanderp** [comment]
pydantic==2.5.3

**Comment by sushi30** [comment]
This issue with pydantic was fixed in 2.7.0: https://github.com/pydantic/pydantic/commit/3d1355f1683c345350891e562ff26ffaab948ebf

To reproduce:

```shell
pip install 'pydantic>=2.7.0,<2.8.0' && python -c 'from pydantic.main import IncEx' # succeeds
pip install 'pydantic<2.7.0' && python -c 'from pydantic.main import IncEx' # fails
```

Needs to be updated in setup.py: https://github.com/open-metadata/OpenMetadata/blob/b93390bb8ab94a3567a15dd85546061eff051c65/ingestion/setup.py#L36

Thanks for raising the issue.

**Comment by alexsanderp** [comment]
It was resolved by updating Pydantic \o
I think you need to adjust the requirements to not allow Pydantic versions lower than 2.7.0.
Can I close the issue or does it need to remain open for this fix?

**Comment by sushi30** [comment]
we can keep it open until we make the change in setup.py
