### ISSUE TITLE
✘ Container execute_migrate_all         service "execute-migrate-all" didn't complete successfully: exit 1 

### ISSUE THREAD

**Issue by liguoyuan** [open-metadata/OpenMetadata#19056]
**Affected module**
execute_migrate_all

**Describe the bug**
 Container execute_migrate_all         service "execute-migrate-all" didn't complete successfully: exit 1 

**To Reproduce**
[larry1@rk95 openmetadata]$ docker-compose up -d
WARN[0000] /home/larry/openmetadata/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 6/6
 ✔ Network openmetadata_app_net          Created                                                                                                             0.1s
 ✔ Container openmetadata_elasticsearch  Healthy                                                                                                            47.9s
 ✔ Container openmetadata_mysql          Healthy                                                                                                            47.9s
 ✘ Container execute_migrate_all         service "execute-migrate-all" didn't complete successfully: exit 1                                                 48.4s
 ✔ Container openmetadata_server         Created                                                                                                             0.0s
 ✔ Container openmetadata_ingestion      Created                                                                                                             0.0s
service "execute-migrate-all" didn't complete successfully: exit 1

[larry1@rk95 openmetadata]$ docker logs execute_migrate_all
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.openmetadata.service.util.OpenMetadataOperations.<clinit>(OpenMetadataOperations.java:78)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

**Expected behavior**
Eliminate errors and ensure normal operation.

**Version:**
 - OS: rocky Linux 9.5
 - Python version: 
 - OpenMetadata version: 1.6.1
 - OpenMetadata Ingestion package version:  images：docker.getcollate.io/openmetadata/ingestion:1.6.1

**Additional context**

**Comment by sergey-gr** [comment]
Also experiencing: "service "execute-migrate-all" didn't complete successfully: exit 1"

when 

```sh
docker-compose up -d
```
 output:
```sh
[+] Running 3/3
 ✔ Container openmetadata_postgresql     Healthy                                                                                                                                                       1.1s 
 ✔ Container openmetadata_elasticsearch  Healthy                                                                                                                                                       1.1s 
 ✘ Container execute_migrate_all         service "execute-migrate-all" didn't complete successfully: exit 1                                                                                            2.6s 
service "execute-migrate-all" didn't complete successfully: exit 1
````

Logs:

```sh
docker logs execute_migrate_all
```

Output:

```sh
   |||||||
 ||||   ||||      ____
||||     ||||    / __ \
||||     ||||   | |  | | _ __    ___  _ __
|||||   |||||   | |  | || '_ \  / _ \| '_ \
|||||||||||||   | |__| || |_) ||  __/| | | |
|||||||||||||    \____/ | .__/  \___||_| |_|
||| ||||| |||    __  __ | |    _              _         _
|||  |||  |||   |  \/  ||_|   | |            | |       | |
|||   |   |||   | \  / |  ___ | |_  __ _   __| |  __ _ | |_  __ _
|||       |||   | |\/| | / _ \| __|/ _` | / _` | / _` || __|/ _` |
||| || || |||   | |  | ||  __/| |_| (_| || (_| || (_| || |_| (_| |
||| ||||| |||   |_|  |_| \___| \__|\__,_| \__,_| \__,_| \__|\__,_|
 |||||||||||
   |||||||
Migrating the OpenMetadata Schema.
picocli.CommandLine$ExecutionException: Error while calling command (public java.lang.Integer org.openmetadata.service.util.OpenMetadataOperations.migrate(boolean)): java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.wrapAndThrow(java.lang.Throwable, java.lang.Object, java.lang.String, com.fasterxml.jackson.databind.DeserializationContext)'
	at picocli.CommandLine.executeUserObject(CommandLine.java:2082)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.openmetadata.service.util.OpenMetadataOperations.main(OpenMetadataOperations.java:1157)
Caused by: java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.wrapAndThrow(java.lang.Throwable, java.lang.Object, java.lang.String, com.fasterxml.jackson.databind.DeserializationContext)'
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:161)
	at com.fasterxml.jackson.module.blackbird.deser.SettableObjectProperty.deserializeAndSet(SettableObjectProperty.java:44)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:273)
	at com.fasterxml.jackson.module.blackbird.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4881)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3035)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:148)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:94)
	at org.openmetadata.service.util.OpenMetadataOperations.parseConfig(OpenMetadataOperations.java:982)
	at org.openmetadata.service.util.OpenMetadataOperations.migrate(OpenMetadataOperations.java:495)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2070)
	... 8 more
```

how to fix?

**Comment by MohammedAlraedah** [comment]
did you find solution ? or the cause of this error

**Comment by harshach** [comment]
can't reproducablae

**Comment by HopeFan** [comment]
Hi, I experienced the same issue. I ran the Docker setup with Postgres following the official documentation, created some sources, then shut it down. However, when I attempted to bring it back up, I encountered the same error.
