### ISSUE TITLE
Kafka SSL - UI uploading Certs and keys

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#19063]
``` warnings.warn(
[2024-11-19 07:47:26] INFO {metadata.OMetaAPI:server_mixin:74} - OpenMetadata client running with Server version [1.5.9] and Client version [1.5.9.0]
%4|1732002446.513|CONFWARN|rdkafka#producer-1| [thrd:app]: Configuration property `sasl.mechanism` set to `SCRAM-SHA-256` but `security.protocol` is not configured for SASL: recommend setting `security.protocol` to SASL_SSL or SASL_PLAINTEXT
[2024-11-19 07:47:26] INFO {metadata.Metadata:test_connections:203} - Running GetTopics...
[2024-11-19 07:47:36] ERROR {metadata.Metadata:test_connections:214} - GetTopics-Failed to fetch topics due to: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}. Please validate credentials and check if you are using correct security protocol
[2024-11-19 07:47:36] INFO {metadata.Metadata:test_connections:228} - Test connection results:
[2024-11-19 07:47:36] INFO {metadata.Metadata:test_connections:229} - lastUpdatedAt=None status=&lt;StatusType.Running: 'Running'&gt; steps=[TestConnectionStepResult(name='GetTopics', mandatory=True, passed=False, message='Failed to fetch topics, please validate the credentials', errorLog='Failed to fetch topics due to: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}. Please validate credentials and check if you are using correct security protocol')]
Traceback (most recent call last):
File "/ingestion/collate/main.py", line 127, in &lt;module&gt;
main()
File "/ingestion/collate/main.py", line 119, in main
workflow = workflow_class.create(workflow_config)
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/ingestion.py", line 110, in create
return cls(config)
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/ingestion.py", line 86, in __init__
super().__init__(
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/base.py", line 110, in __init__
self.post_init()
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/ingestion.py", line 105, in post_init
self.set_steps()
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/metadata.py", line 31, in set_steps
self.source = self._get_source()
File "/usr/local/lib/python3.10/site-packages/metadata/workflow/metadata.py", line 54, in _get_source

---
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
A clear and concise description of what you expected to happen.

**Version:**
 - OS: [e.g. iOS]
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
Add any other context about the problem here.

**Comment by ayush-shah** [comment]
Network issue - whitelisting it works, if it gets reproduced again, we can open it.
