### ISSUE TITLE
Sample Topics are failing.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#1996]
[2022-01-03, 05:00:29 UTC] {standard_task_runner.py:88} ERROR - Failed to execute job 14 for task ingest_using_docker
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1509, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/docker/operators/docker.py", line 390, in execute
    return self._run_image()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/docker/operators/docker.py", line 277, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/docker/operators/docker.py", line 324, in _run_image_with_mounts
    raise AirflowException('docker container failed: ' + repr(result) + f"lines {res_lines}")
airflow.exceptions.AirflowException: docker container failed: {'Error': None, 'StatusCode': 1}lines Failed to ingest topic customer_events
Numeric value (322122382273) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 970] (through reference chain: org.openmetadata.catalog.api.data.CreateTopic["retentionSize"])
Failed to ingest topic product_events
Numeric value (322122382273) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 877] (through reference chain: org.openmetadata.catalog.api.data.CreateTopic["retentionSize"])
Failed to ingest topic shop_updates
Numeric value (322122382273) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 839] (through reference chain: org.openmetadata.catalog.api.data.CreateTopic["retentionSize"])
Failed to ingest topic shop_products
Numeric value (3222122382273) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1067] (through reference chain: org.openmetadata.catalog.api.data.CreateTopic["retentionSize"])
Failed to ingest topic orders
Numeric value (3222122382273) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1015] (through reference chain: org.openmetadata.catalog.api.data.CreateTopic["retentionSize"])
Failed to ingest topic sales
Numeric value (3222122382273) out of range of int (-2147483648 - 2147483647)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 941] (through reference chain: org.openmetadata.catalog.api.data.CreateTopic["retentionSize"])
Traceback (most recent call last):
  File "/ingestion/main.py", line 21, in <module>
    main()
  File "/ingestion/main.py", line 15, in main
    workflow.raise_from_status()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 185, in raise_from_status

**Comment by ayush-shah** [comment]
@harshach did we change the retension size limit?

**Comment by ayush-shah** [comment]
Issue Fixed with #2005. 

> @harshach did we change the retension size limit? shows this error numeric value (3222122382273) out of range of int (-2147483648 - 2147483647)
The Datatype changed from numeric to int
