### ISSUE TITLE
bootstrap_storage.sh migrate-all errors

### ISSUE THREAD

**Issue by lihan** [open-metadata/OpenMetadata#2122]
Version 0.7.0
Helm dependency used
```
dependencies:
- name: openmetadata-dependencies
  repository: https://helm.open-metadata.org/
  version: 0.0.3
- name: openmetadata
  repository: https://helm.open-metadata.org/
  version: 0.0.3
```
Observed the following error message after running `bootstrap_storage.sh migrate-all`

```"migrate" option successful
Using Configuration file: ./bootstrap/../conf/openmetadata.yaml
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --es-migrate
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:561)
        at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:383)
        at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:334)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:540)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:712)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:679)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:660)
        at org.openmetadata.catalog.util.TablesInitializer.main(TablesInitializer.java:83)
```

**Comment by harshach** [comment]
Fixed and released 0.7.1 https://github.com/open-metadata/OpenMetadata/releases/tag/0.7.1-release
