### ISSUE TITLE
Getting : ValueError: could not convert string to float: 'None'

### ISSUE THREAD

**Issue by satyavarma** [open-metadata/OpenMetadata#2153]
when I'm trying to run the ingestion for redshift services, Getting the below error in airflow dags but the dags are marked as success.

`.....
[2022-01-11, 11:21:44 UTC] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.9/site-packages/airflow/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-11, 11:21:44 UTC] {logging_mixin.py:109} WARNING - Message: 'airflow service entity {}'
Arguments: (PipelineService(id=Uuid(__root__=UUID('7d3e3d20-1253-4f04-90d1-e54718c859ff')), name='local_airflow_3', serviceType=<PipelineServiceType.Airflow: 'Airflow'>, description=None, displayName=None, version=EntityVersion(__root__=0.1), updatedAt=DateTime(__root__=datetime.datetime(2021, 12, 30, 5, 1, 41, 366000, tzinfo=datetime.timezone.utc)), updatedBy='anonymous', pipelineUrl=AnyUrl('http://localhost:8080', scheme='http', host='localhost', host_type='int_domain', port='8080'), ingestionSchedule=None, href=Href(__root__=AnyUrl('http://localhost:8585/api/v1/services/pipelineServices/7d3e3d20-1253-4f04-90d1-e54718c859ff', scheme='http', host='localhost', host_type='int_domain', port='8585', path='/api/v1/services/pipelineServices/7d333333333-4f04-90d1-e54718c859ff')), changeDescription=None),)
[2022-01-11, 11:21:44 UTC] {openmetadata.py:159} INFO - {'_inlets': '[]', 'task_id': "'redshift_dataplatform'", 'label': "'redshift_dataplatform'", '_downstream_task_ids': '[]', 'start_date': '1641772800.0', '_outlets': '[]', '_task_type': "'PythonOperator'", '_task_module': "'airflow.operators.python'", 'execution_timeout': 'None', 'end_date': 'None', 'sla': 'None', 'wait_for_downstream': 'False', 'email': 'None', 'trigger_rule': "'all_success'", 'depends_on_past': 'False'}
[2022-01-11, 11:21:44 UTC] {openmetadata.py:160} INFO - {'fileloc': "'/ingestion/examples/airflow/dags/redshift_dataplatform.py'", 'timezone': "'UTC'", '_default_view': "'tree'", 'catchup': 'True', '_access_control': 'None', 'is_paused_upon_creation': 'None', 'tags': 'None', 'start_date': 'None'}
[2022-01-11, 11:21:44 UTC] {openmetadata.py:297} ERROR - Traceback (most recent call last):
  File "/ingestion/src/airflow_provider_openmetadata/lineage/openmetadata.py", line 293, in send_lineage
  File "/ingestion/src/airflow_provider_openmetadata/lineage/openmetadata.py", line 162, in parse_lineage_to_openmetadata
ValueError: could not convert string to float: 'None'

[2022-01-11, 11:21:44 UTC] {openmetadata.py:298} ERROR - could not convert string to float: 'None'
[2022-01-11, 11:21:44 UTC] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=redshift_dataplatform, task_id=redshift_dataplatform, execution_date=20220111T112129, start_date=20220111T112131, end_date=20220111T112144
[2022-01-11, 11:21:44 UTC] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11, 11:21:44 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check`

**Comment by harshach** [comment]
@pmbrull the above issue can happen if the airflow dag doesn't have start_date as its optional config. Can you check if the new code you wrote handles this scenario
