### ISSUE TITLE
Docker ingestion not working

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#2262]
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/openmetadata/examples/")
[2022-01-18, 10:17:24 UTC] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=sample_data, task_id=ingest_using_docker, execution_date=20220117T101639, start_date=20220118T101724, end_date=20220118T101724
[2022-01-18, 10:17:24 UTC] {standard_task_runner.py:88} ERROR - Failed to execute job 10 for task ingest_using_docker
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create

**Comment by pmbrull** [comment]
To simplify the sample data workflow I'll revert the `DockerOperator` changes on the example DAG and just use the usual `workflow` approach.

I have it pending to work on the DockerOperator docs for the ingestions so I can have some examples there, sorry for the noise!

**Comment by pmbrull** [comment]
@akash-jain-10 what was the command again that produces this error?
