### ISSUE TITLE
Elasticsearch.py throws an error

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2276]
Traceback (most recent call last):
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/metadata/cmd.py", line 76, in ingest
    workflow.execute()
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 163, in execute
    self.sink.write_record(processed_record)
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/metadata/ingestion/sink/elasticsearch.py", line 181, in write_record
    table_doc = self._create_table_es_doc(record)
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/metadata/ingestion/sink/elasticsearch.py", line 230, in _create_table_es_doc
    timestamp = epoch_ms(table.updatedAt.__root__)
  File "/Users/akashjain/Documents/github/open-metadata/OpenMetadata/venv/lib/python3.9/site-packages/metadata/ingestion/sink/elasticsearch.py", line 59, in epoch_ms
    return int(dt.timestamp() * 1000)

**Comment by ayush-shah** [comment]
Fixed in #2278
