### ISSUE TITLE
boto3 not found for dev package openmetadata-ingestion on test.pypi

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#2379]
I created a fresh virtual environment and installed the dev package using the following command

```
pip install --extra-index-url https://test.pypi.org/simple/ openmetadata-ingestion==0.8.0.dev1
```

after installation on execution of ```metadata --help``` or any other operation with metadata command throws module not found error for boto3 

```
% metadata --help
Traceback (most recent call last):
  File "/Users/mayursingal/Desktop/ulixius/OpenMetadata/venv/bin/metadata", line 5, in <module>
    from metadata.cmd import metadata
  File "/Users/mayursingal/Desktop/ulixius/OpenMetadata/venv/lib/python3.8/site-packages/metadata/cmd.py", line 22, in <module>
    from metadata.cli.backup import run_backup
  File "/Users/mayursingal/Desktop/ulixius/OpenMetadata/venv/lib/python3.8/site-packages/metadata/cli/backup.py", line 21, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

**Comment by pmbrull** [comment]
Thanks, @ulixius9 for reporting this. We'll move the import inside the specific command so that it is not trying to be called by default.
Meanwhile, you can retry to install with the `openmetadata-ingestion[backup]` plugin
