### ISSUE TITLE
Blank UI when clicking a new Pipeline

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#2578]
**Affected module**
UI

**Describe the bug**
After ingesting the sample data, if we create a new `Pipeline` using the API from an existing Pipeline Service, the pipeline gets listed under the service, but if we click on it, the page turns blank.

**To Reproduce**

We can run:

```python
from metadata.ingestion.ometa.ometa_api import OpenMetadata
from metadata.ingestion.ometa.openmetadata_rest import MetadataServerConfig
from metadata.generated.schema.entity.services.pipelineService import (
    PipelineService,
    PipelineServiceType,
)
from metadata.generated.schema.api.data.createPipeline import CreatePipelineRequest
from metadata.generated.schema.type.entityReference import EntityReference

server_config = MetadataServerConfig(api_endpoint="http://localhost:8585/api")
metadata = OpenMetadata(server_config)

service = metadata.get_by_name(entity=PipelineService, fqdn="local_airflow_3")

create = CreatePipelineRequest(
            name="test",
            service=EntityReference(id=service.id, type="pipelineService"),
        )

metadata.create_or_update(create)
```

![image](https://user-images.githubusercontent.com/35870520/152197844-e0df62c0-8be3-4633-8878-3f5468f940ae.png)

![image](https://user-images.githubusercontent.com/35870520/152197769-2f6b0a93-e66b-4ca6-8c55-61d738903465.png)

**Expected behavior**
We should be able to see the new pipeline

**Version:**
 - Python version: 3.9.6
 - OpenMetadata version: main branch
 - OpenMetadata Ingestion package version: main branch

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
@pmbrull, It would be easy to debug this issue if you can provide the console error.

**Comment by pmbrull** [comment]
Hi @Sachin-chaurasiya, those are the server logs when trying to access the pipeline:
```
172.16.239.1 - - [07/Feb/2022:08:58:17 +0000] "GET /pipeline/test-service-pipeline.test HTTP/1.1" 404 2239 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 10
172.16.239.1 - - [07/Feb/2022:08:58:17 +0000] "GET /openmetadata.bundle.js?5ba7af3b76ec22adbde9 HTTP/1.1" 304 0 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 46
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/config/auth HTTP/1.1" 200 86 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 2
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /logo.svg HTTP/1.1" 304 0 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 3
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/version HTTP/1.1" 200 108 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 6
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /favicon.png?5ba7af3b76ec22adbde9 HTTP/1.1" 304 0 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 1
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /pipeline/manifest.json HTTP/1.1" 404 2239 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 3
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/tags HTTP/1.1" 200 2225 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 44
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/users?fields=profile,teams,roles&limit=100000 HTTP/1.1" 200 32 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 60
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/teams?limit=1000000 HTTP/1.1" 200 32 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 62
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/roles?limit=1000000 HTTP/1.1" 200 912 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 94
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/pipelines/name/test-service-pipeline.test?fields=followers,tags,owner,tasks&include=all HTTP/1.1" 200 536 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 97
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/tags/PII HTTP/1.1" 200 1552 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 49
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/tags/PersonalData HTTP/1.1" 200 1361 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 64
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/tags/Tier HTTP/1.1" 200 3404 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 55
172.16.239.1 - - [07/Feb/2022:08:58:18 +0000] "GET /api/v1/tags/User HTTP/1.1" 200 9794 "http://localhost:8585/pipeline/test-service-pipeline.test" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 150
```
Thanks

**Comment by Sachin-chaurasiya** [comment]
Hello @pmbrull, I was asking for browser console logs.

**Comment by pmbrull** [comment]
#FrontendKnowledge 😅  There you go

```
GET http://localhost:8585/pipeline/test-service-pipeline.test 404 (Not Found)
mobx.esm.js:3467 [mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
t.get_ @ mobx.esm.js:3467
get @ mobx.esm.js:3247
(anonymous) @ Appbar.tsx:132
(anonymous) @ Appbar.tsx:175
(anonymous) @ index.module.js:206
(anonymous) @ index.module.js:184
Fe @ mobx.esm.js:1380
t.track @ mobx.esm.js:1918
Te @ index.module.js:182
c @ index.module.js:206
Ko @ react-dom.production.min.js:153
Ra @ react-dom.production.min.js:175
za @ react-dom.production.min.js:175
ws @ react-dom.production.min.js:268
fl @ react-dom.production.min.js:246
dl @ react-dom.production.min.js:246
rl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
Vi @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
il @ react-dom.production.min.js:240
lt @ mobx.esm.js:2056
ut @ mobx.esm.js:2025
it @ mobx.esm.js:1670
ye @ mobx.esm.js:697
me @ mobx.esm.js:641
updateAuthState @ mobx.esm.js:620
(anonymous) @ AuthProvider.tsx:235
Promise.then (async)
(anonymous) @ AuthProvider.tsx:208
as @ react-dom.production.min.js:211
wl @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
bl @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
R @ scheduler.production.min.js:17
x.port1.onmessage @ scheduler.production.min.js:14
mobx.esm.js:3467 [mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
t.get_ @ mobx.esm.js:3467
get @ mobx.esm.js:3247
(anonymous) @ Appbar.tsx:132
(anonymous) @ Appbar.tsx:175
(anonymous) @ index.module.js:206
(anonymous) @ index.module.js:184
Fe @ mobx.esm.js:1380
t.track @ mobx.esm.js:1918
Te @ index.module.js:182
c @ index.module.js:206
Ko @ react-dom.production.min.js:153
Ra @ react-dom.production.min.js:175
za @ react-dom.production.min.js:175
ws @ react-dom.production.min.js:268
fl @ react-dom.production.min.js:246
dl @ react-dom.production.min.js:246
rl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
Vi @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
Js @ react-dom.production.min.js:230
ya @ react-dom.production.min.js:163
(anonymous) @ Appbar.tsx:221
Promise.then (async)
(anonymous) @ Appbar.tsx:220
as @ react-dom.production.min.js:211
wl @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
bl @ react-dom.production.min.js:257
rl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
Vi @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
Js @ react-dom.production.min.js:230
ya @ react-dom.production.min.js:163
(anonymous) @ AuthProvider.tsx:236
Promise.then (async)
(anonymous) @ AuthProvider.tsx:208
as @ react-dom.production.min.js:211
wl @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
bl @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
R @ scheduler.production.min.js:17
x.port1.onmessage @ scheduler.production.min.js:14
manifest.json:1 GET http://localhost:8585/pipeline/manifest.json 404 (Not Found)
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
mobx.esm.js:3467 [mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
t.get_ @ mobx.esm.js:3467
get @ mobx.esm.js:3247
(anonymous) @ Appbar.tsx:132
(anonymous) @ Appbar.tsx:175
(anonymous) @ index.module.js:206
(anonymous) @ index.module.js:184
Fe @ mobx.esm.js:1380
t.track @ mobx.esm.js:1918
Te @ index.module.js:182
c @ index.module.js:206
Ko @ react-dom.production.min.js:153
Ra @ react-dom.production.min.js:175
za @ react-dom.production.min.js:175
ws @ react-dom.production.min.js:268
fl @ react-dom.production.min.js:246
dl @ react-dom.production.min.js:246
rl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
Vi @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
il @ react-dom.production.min.js:240
lt @ mobx.esm.js:2056
ut @ mobx.esm.js:2025
it @ mobx.esm.js:1670
ye @ mobx.esm.js:697
me @ mobx.esm.js:641
updateUsers @ mobx.esm.js:620
(anonymous) @ UsedDataUtils.ts:24
Promise.then (async)
$l @ UsedDataUtils.ts:23
(anonymous) @ AuthProvider.tsx:241
Promise.finally (async)
(anonymous) @ AuthProvider.tsx:239
as @ react-dom.production.min.js:211
wl @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
bl @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
R @ scheduler.production.min.js:17
x.port1.onmessage @ scheduler.production.min.js:14
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'map')
    at KR (PipelineDetails.component.tsx:336:32)
    at Ko (react-dom.production.min.js:153:146)
    at ws (react-dom.production.min.js:261:496)
    at fl (react-dom.production.min.js:246:265)
    at dl (react-dom.production.min.js:246:194)
    at rl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Qi (react-dom.production.min.js:122:325)
    at Vi (react-dom.production.min.js:123:61)
ns @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
ho @ react-dom.production.min.js:131
ss @ react-dom.production.min.js:212
yl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
gl @ react-dom.production.min.js:248
rl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
Vi @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
Js @ react-dom.production.min.js:230
ya @ react-dom.production.min.js:163
(anonymous) @ PipelineDetailsPage.component.tsx:230
Promise.finally (async)
(anonymous) @ PipelineDetailsPage.component.tsx:230
(anonymous) @ PipelineDetailsPage.component.tsx:377
as @ react-dom.production.min.js:211
wl @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Qi @ react-dom.production.min.js:122
bl @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
R @ scheduler.production.min.js:17
x.port1.onmessage @ scheduler.production.min.js:14
PipelineDetails.component.tsx:336 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at KR (PipelineDetails.component.tsx:336:32)
    at Ko (react-dom.production.min.js:153:146)
    at ws (react-dom.production.min.js:261:496)
    at fl (react-dom.production.min.js:246:265)
    at dl (react-dom.production.min.js:246:194)
    at rl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Qi (react-dom.production.min.js:122:325)
    at Vi (react-dom.production.min.js:123:61)
```

**Comment by Sachin-chaurasiya** [comment]
@pmbrull , If you noticed we are getting `404 Not Found` for the entity. 
`GET http://localhost:8585/pipeline/test-service-pipeline.test 404 (Not Found)`.

**Comment by pmbrull** [comment]
I think that the issue is that the URL should be `http GET http://localhost:8585/api/v1/pipelines/name/test-service-pipeline.test`

**Comment by pmbrull** [comment]
Thanks @Sachin-chaurasiya for your time! I opened https://github.com/open-metadata/OpenMetadata/issues/2657 to make sure frontend validates the tasks list of a pipeline before mapping over it.

Thanks!
