### ISSUE TITLE
Fix broken UserResourceTest

### ISSUE THREAD

**Issue by mithmatt** [open-metadata/OpenMetadata#2647]
**Affected module**
Tests

**Describe the bug**
Commit bfcd97ed0bae1770deb992c6e4ec518b1ea0b663 was reported to create a regression with failing unit tests

**To Reproduce**

Run mvn test

```
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   UserResourceTest.patch_userAttributes_as_admin_200_ok:418->EntityResourceTest.patchEntityAndCheck:1436->EntityResourceTest.patchEntity:1286 » NullPointer
[INFO]
[ERROR] Tests run: 793, Failures: 0, Errors: 1, Skipped: 0
```

**Expected behavior**
Tests should pass

cc: @amiorin @harshach

**Comment by mithmatt** [comment]
Something is odd with this test

```
INFO  [2022-02-07 06:54:38,268] org.openmetadata.catalog.jdbi3.WebhookRepository: Webhook healthy:started:1 received response OK
INFO  [2022-02-07 06:54:38,281] org.openmetadata.catalog.exception.CatalogGenericExceptionMapper: exception 
! javax.json.JsonException: '{"type":"role","name":"role_1_patch_userAttributes_as_admin_200_ok(TestInfo)","id":"8b42aa55-40bf-4ebf-86f6-965e4abc039d"}' contains no value for name 'href'
! at org.apache.johnzon.core.JsonPointerImpl.getValue(JsonPointerImpl.java:338)
! at org.apache.johnzon.core.JsonPointerImpl.validateJsonPointer(JsonPointerImpl.java:513)
! at org.apache.johnzon.core.JsonPointerImpl.validateRemove(JsonPointerImpl.java:320)
! at org.apache.johnzon.core.JsonPointerImpl.remove(JsonPointerImpl.java:282)
! at org.apache.johnzon.core.JsonPointerImpl.remove(JsonPointerImpl.java:266)
! at org.apache.johnzon.core.JsonPatchImpl.apply(JsonPatchImpl.java:71)
```


```
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
! at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [2022-02-07 06:54:38,282] org.openmetadata.catalog.resources.teams.UserResource: Got exception: [JsonException] / message ['{"type":"role","name":"role_1_patch_userAttributes_as_admin_200_ok(TestInfo)","id":"8b42aa55-40bf-4ebf-86f6-965e4abc039d"}' contains no value for name 'href'] / related resource location: [org.openmetadata.catalog.resources.teams.UserResource.patch](UserResource.java:402)
! javax.json.JsonException: '{"type":"role","name":"role_1_patch_userAttributes_as_admin_200_ok(TestInfo)","id":"8b42aa55-40bf-4ebf-86f6-965e4abc039d"}' contains no value for name 'href'
! at org.apache.johnzon.core.JsonPointerImpl.getValue(JsonPointerImpl.java:338)
! at org.apache.johnzon.core.JsonPointerImpl.validateJsonPointer(JsonPointerImpl.java:513)
! at org.apache.johnzon.core.JsonPointerImpl.validateRemove(JsonPointerImpl.java:320)
! at org.apache.johnzon.core.JsonPointerImpl.remove(JsonPointerImpl.java:282)
! at org.apache.johnzon.core.JsonPointerImpl.remove(JsonPointerImpl.java:266)
```

**Comment by mithmatt** [comment]
```
contains no value for name 'href'
```

This looks similar to #2528 (bug on Teams PATCH API).

**Comment by mithmatt** [comment]
Throws an error in JsonUtils#applyPatch

![image](https://user-images.githubusercontent.com/5906984/152742339-1f005aa0-9c52-4bf8-9094-4ef383d2c14b.png)

cc: @sureshms  in case these issues are related and helps with debugging #2528

**Comment by sureshms** [comment]
@mithmatt, I have been running this test for several hours without any failure after some related code was fixed in another issue. Closing this for now. We can reopen this, if the issue happens again.
