### ISSUE TITLE
Vertica UUID fields are removed from table structure after ingestion

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2713]
**Affected module**
Ingestion Framework

**Describe the bug**
Vertica ingestion with UUID field not fails, but UUID fields are removed from metadata

```
Traceback (most recent call last):
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 89, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'GenericTypeCompiler' object has no attribute 'visit_UUID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/metadata/ingestion/source/sql_source.py", line 501, in _get_columns
    col_type = ColumnTypeParser.get_column_type(column["type"])
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/metadata/utils/column_type_parser.py", line 150, in get_column_type
    if str(column_type) == sql_type:
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 623, in __str__
    return str(self.compile())
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 606, in compile
    return dialect.type_compiler.process(self)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    util.raise_(
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x1057166d0> can't render element of type <class 'metadata.ingestion.source.vertica.UUID'> (Background on this error at: http://sqlalche.me/e/13/l7de)
[2022-02-10 21:39:45,800] ERROR    {metadata.ingestion.source.sql_source:603} - Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x1057166d0> can't render element of type <class 'metadata.ingestion.source.vertica.UUID'> (Background on this error at: http://sqlalche.me/e/13/l7de) : {'name': 'user_uid', 'type': UUID(), 'nullable': False, 'default': '', 'autoincrement': False, 'comment': None, 'primary_key': True}
```

DDL
```
-- auto-generated definition
create table ml_prophets_prediction
(
    user_uid                   uuid not null,
    fact_date                  date not null,
    toxic_prediction_prob      numeric(37, 15),
    profitable_prediction_prob numeric(37, 15),
    updated_at                 timestamp,
    deleted_at                 timestamp,
    etl_created_at             timestamp,
    etl_updated_at             timestamp,
    etl_crc                    int,
    partner_uid                varchar(64),
    constraint ml_prophets_prediction_pk
        primary key (fact_date, user_uid)
);
```

![image](https://user-images.githubusercontent.com/2264016/153475896-a9a69760-c1b2-4957-9d74-0a0f3b6746e8.png)

**To Reproduce**

Create table with DDL and run ingestion process

**Expected behavior**
All fields must be ingested

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@igor-kramer we fixed in another PR btw

**Comment by harshach** [comment]
@igor-kramer can you make sure you are running server as well?
