### ISSUE TITLE
Clickhouse datatypes are not recognized

### ISSUE THREAD

**Issue by igor-kramer** [open-metadata/OpenMetadata#2715]
**Affected module**
Ingestion Framework?

**Describe the bug**
I'm trying to ingest metadata from Clickhouse

```
[2022-02-10 22:42:42,147] ERROR    {metadata.ingestion.source.sql_source:61} - Table Description Error :
[2022-02-10 22:42:42,147] WARNING  {metadata.ingestion.source.sql_source:460} - Cannot obtain constraints - NotImplementedError
/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/clickhouse_sqlalchemy/drivers/base.py:1035: SAWarning: Did not recognize type 'DateTime64(9)' of column 'created'
  warn("Did not recognize type '%s' of column '%s'" %
/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/clickhouse_sqlalchemy/drivers/base.py:1035: SAWarning: Did not recognize type 'DateTime64(9)' of column 'updated'
  warn("Did not recognize type '%s' of column '%s'" %
[2022-02-10 22:42:42,238] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: account
[2022-02-10 22:42:42,242] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Nullable(<class 'clickhouse_sqlalchemy.types.common.UInt8'>) mapped to VARCHAR: enable
[2022-02-10 22:42:42,244] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt8() mapped to VARCHAR: is_trial
[2022-02-10 22:42:42,244] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt8() mapped to VARCHAR: read_only
[2022-02-10 22:42:42,251] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Nullable(<class 'clickhouse_sqlalchemy.types.common.String'>) mapped to VARCHAR: category
[2022-02-10 22:42:42,253] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Nullable(<class 'clickhouse_sqlalchemy.types.common.String'>) mapped to VARCHAR: pm_trader_uuid
Traceback (most recent call last):
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/metadata/ingestion/source/sql_source.py", line 501, in _get_columns
    col_type = ColumnTypeParser.get_column_type(column["type"])
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/metadata/utils/column_type_parser.py", line 150, in get_column_type
    if str(column_type) == sql_type:
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 623, in __str__
    return str(self.compile())
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/clickhouse_sqlalchemy/types/common.py", line 9, in compile
    return super(ClickHouseTypeEngine, self).compile(
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 606, in compile
    return dialect.type_compiler.process(self)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 701, in visit_nullable
    return 'Nullable(%s)' % self.process(nested_type, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3478, in visit_null
    raise exc.CompileError(
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?
[2022-02-10 22:42:42,262] ERROR    {metadata.ingestion.source.sql_source:597} - Can't generate DDL for NullType(); did you forget to specify a type on this Column? : {'name': 'created', 'type': Nullable(<class 'sqlalchemy.sql.sqltypes.NullType'>), 'nullable': True, 'default': 'parseDateTime64BestEffort(source_created, 9)'}
Traceback (most recent call last):
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/metadata/ingestion/source/sql_source.py", line 501, in _get_columns
    col_type = ColumnTypeParser.get_column_type(column["type"])
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/metadata/utils/column_type_parser.py", line 150, in get_column_type
    if str(column_type) == sql_type:
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 623, in __str__
    return str(self.compile())
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/clickhouse_sqlalchemy/types/common.py", line 9, in compile
    return super(ClickHouseTypeEngine, self).compile(
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 606, in compile
    return dialect.type_compiler.process(self)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 701, in visit_nullable
    return 'Nullable(%s)' % self.process(nested_type, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/igorkram/datacatalog/env-om-dev/lib/python3.9/site-packages/sqlalchemy/sql/compiler.py", line 3478, in visit_null
    raise exc.CompileError(
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?
[2022-02-10 22:42:42,263] ERROR    {metadata.ingestion.source.sql_source:597} - Can't generate DDL for NullType(); did you forget to specify a type on this Column? : {'name': 'updated', 'type': Nullable(<class 'sqlalchemy.sql.sqltypes.NullType'>), 'nullable': True, 'default': 'parseDateTime64BestEffort(source_updated, 9)'}
[2022-02-10 22:42:42,365] INFO     {metadata.ingestion.sink.metadata_rest:201} - Successfully ingested table b2b.account_change_data
[2022-02-10 22:42:42,365] INFO     {metadata.ingestion.source.sql_source_common:33} - Table Scanned: clickhouse-test.account_change_data
[2022-02-10 22:42:42,365] ERROR    {metadata.ingestion.source.sql_source:61} - Table Description Error :
[2022-02-10 22:42:42,365] WARNING  {metadata.ingestion.source.sql_source:460} - Cannot obtain constraints - NotImplementedError
[2022-02-10 22:42:42,448] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: id
[2022-02-10 22:42:42,450] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: account
[2022-02-10 22:42:42,456] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt8() mapped to VARCHAR: is_trial
[2022-02-10 22:42:42,458] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: created
[2022-02-10 22:42:42,458] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: original_updated
[2022-02-10 22:42:42,458] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: source
[2022-02-10 22:42:42,460] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: kafka_partition
[2022-02-10 22:42:42,524] INFO     {metadata.ingestion.sink.metadata_rest:201} - Successfully ingested table b2b.account_data
[2022-02-10 22:42:42,524] INFO     {metadata.ingestion.source.sql_source_common:33} - Table Scanned: clickhouse-test.account_data
[2022-02-10 22:42:42,525] ERROR    {metadata.ingestion.source.sql_source:61} - Table Description Error :
[2022-02-10 22:42:42,525] WARNING  {metadata.ingestion.source.sql_source:460} - Cannot obtain constraints - NotImplementedError
[2022-02-10 22:42:42,607] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: id
[2022-02-10 22:42:42,609] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: account
[2022-02-10 22:42:42,614] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt8() mapped to VARCHAR: is_trial
[2022-02-10 22:42:42,616] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: created
[2022-02-10 22:42:42,616] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: original_updated
[2022-02-10 22:42:42,617] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: source
[2022-02-10 22:42:42,618] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: kafka_partition
[2022-02-10 22:42:42,742] INFO     {metadata.ingestion.sink.metadata_rest:201} - Successfully ingested table b2b.account_data_v2
[2022-02-10 22:42:42,742] INFO     {metadata.ingestion.source.sql_source_common:33} - Table Scanned: clickhouse-test.account_data_v2
[2022-02-10 22:42:42,742] ERROR    {metadata.ingestion.source.sql_source:61} - Table Description Error :
[2022-02-10 22:42:42,742] WARNING  {metadata.ingestion.source.sql_source:460} - Cannot obtain constraints - NotImplementedError
[2022-02-10 22:42:42,817] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: id
[2022-02-10 22:42:42,820] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: account
[2022-02-10 22:42:42,821] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: risk_level
[2022-02-10 22:42:42,822] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: created
[2022-02-10 22:42:42,823] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: kafka_partition
[2022-02-10 22:42:42,884] INFO     {metadata.ingestion.sink.metadata_rest:201} - Successfully ingested table b2b.account_risk_level_history
[2022-02-10 22:42:42,884] INFO     {metadata.ingestion.source.sql_source_common:33} - Table Scanned: clickhouse-test.account_risk_level_history
[2022-02-10 22:42:42,884] ERROR    {metadata.ingestion.source.sql_source:61} - Table Description Error :
[2022-02-10 22:42:42,884] WARNING  {metadata.ingestion.source.sql_source:460} - Cannot obtain constraints - NotImplementedError
[2022-02-10 22:42:42,958] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: id
[2022-02-10 22:42:42,959] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: account
[2022-02-10 22:42:42,959] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: risk_level
[2022-02-10 22:42:42,960] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: created
[2022-02-10 22:42:42,962] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: kafka_partition
[2022-02-10 22:42:43,021] INFO     {metadata.ingestion.sink.metadata_rest:201} - Successfully ingested table b2b.account_risk_level_history_v2
[2022-02-10 22:42:43,022] INFO     {metadata.ingestion.source.sql_source_common:33} - Table Scanned: clickhouse-test.account_risk_level_history_v2
[2022-02-10 22:42:43,107] ERROR    {metadata.ingestion.source.sql_source:61} - Table Description Error :
[2022-02-10 22:42:43,107] WARNING  {metadata.ingestion.source.sql_source:460} - Cannot obtain constraints - NotImplementedError
[2022-02-10 22:42:43,190] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: id
[2022-02-10 22:42:43,191] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: account
[2022-02-10 22:42:43,194] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt8() mapped to VARCHAR: is_trial
[2022-02-10 22:42:43,195] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: created
[2022-02-10 22:42:43,196] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: original_updated
[2022-02-10 22:42:43,196] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: source
[2022-02-10 22:42:43,197] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: kafka_partition
[2022-02-10 22:42:43,259] INFO     {metadata.ingestion.sink.metadata_rest:201} - Successfully ingested table b2b.account_data_mv
[2022-02-10 22:42:43,260] ERROR    {metadata.ingestion.source.sql_source:61} - Table Description Error :
[2022-02-10 22:42:43,260] WARNING  {metadata.ingestion.source.sql_source:460} - Cannot obtain constraints - NotImplementedError
[2022-02-10 22:42:43,336] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: id
[2022-02-10 22:42:43,339] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: account
[2022-02-10 22:42:43,340] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: risk_level
[2022-02-10 22:42:43,341] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type UInt64() mapped to VARCHAR: created
[2022-02-10 22:42:43,342] WARNING  {metadata.ingestion.source.sql_source:520} - Unknown type Int32() mapped to VARCHAR: kafka_partition
```
**To Reproduce**
Start Clickhouse ingestion process

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 88afb17ee8ee19004cb985c7353171fb2fbaf05c
 - OpenMetadata Ingestion package version: 88afb17ee8ee19004cb985c7353171fb2fbaf05c

**Additional context**

**Comment by harshach** [comment]
@ulixius9 can you take a look .We should add mapping all click house types https://clickhouse.com/docs/en/sql-reference/data-types/ all of the uInt types should be mapped to Integer and add the original type to dataTypeDisplay field
