### ISSUE TITLE
Ingestion fails due to CreateGlossaryRequest

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#2791]
**Affected module**
Ingestion Framework

**Describe the bug**
Getting following error while ingestion.
```
Traceback (most recent call last):
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/cmd.py", line 72, in ingest
    workflow = Workflow.create(workflow_config)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 150, in create
    return cls(config)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 68, in __init__
    self.source: Source = source_class.create(
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/source/sample_usage.py", line 52, in create
    return cls(config, metadata_config, ctx)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/source/sample_usage.py", line 44, in __init__
    self.service = get_database_service_or_create(
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/utils/helpers.py", line 60, in get_database_service_or_create
    service = metadata.get_by_name(entity=DatabaseService, fqdn=config.service_name)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 376, in get_by_name
    return self._get(entity=entity, path=f"name/{fqdn}", fields=fields)
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 401, in _get
    resp = self.client.get(f"{self.get_suffix(entity)}/{path}{fields_str}")
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 174, in get_suffix
    entity, get_args(Union[Glossary, self.get_create_entity_type(Glossary)])
  File "/Users/sachinchaurasiya/Desktop/OpenMetadata/ingestion/env/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 319, in get_create_entity_type
    create_class = getattr(
AttributeError: module 'metadata.generated.schema.api.data.createGlossary' has no attribute 'CreateGlossaryRequest'
```

**Comment by ayush-shah** [comment]
Creating a mixin for Glossary.
cc: @harshach
