### ISSUE TITLE
Backend - Deprecated Test Package - wix-embedded-mysql

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2919]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
Running `mvn clean install` or `mvn clean package` on local M1 Mac causes the following error:
  
   
      [INFO] Running org.openmetadata.catalog.resources.topics.TopicResourceTest
      16:12:30.560 [main] INFO com.wix.mysql.EmbeddedMysql - Preparing EmbeddedMysql version 'Version 8.0.17'...
      Download Version 8.0.17:OS_X:B32 START
      16:12:31.370 [main] ERROR de.flapdoodle.embed.process.runtime.Starter - no message
      java.io.IOException: Could not open inputStream for https://dev.mysql.com/get/Downloads//MySQL-8.0/mysql-8.0.17-macos10.14-x86.tar.gz
              at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
              at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
              at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
              at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
              at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
              at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
              at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:41)
              at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:169)
              at org.openmetadata.catalog.resources.EmbeddedMySqlSupport.beforeAll(EmbeddedMySqlSupport.java:45)
              at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
              at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
              at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
              at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
              at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
              at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
              at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
              at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
              at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
              at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
              at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
              at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
              at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
              at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
              at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
              at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
              at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
              at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
              at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
              at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
              at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
              at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
              at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
              at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
              at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
              at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
              at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
              at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
              at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
              at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
              at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
              at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
              at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
      Caused by: java.io.FileNotFoundException: https://dev.mysql.com/get/Downloads//MySQL-8.0/mysql-8.0.17-macos10.14-x86.tar.gz
              at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
              at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
              at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
              at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)
              ... 50 common frames omitted
      [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.815 s <<< FAILURE! - in org.openmetadata.catalog.resources.topics.TopicResourceTest
      [ERROR] org.openmetadata.catalog.resources.topics.TopicResourceTest  Time elapsed: 0.815 s  <<< ERROR!
      de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for https://dev.mysql.com/get/Downloads//MySQL-8.0/mysql-8.0.17-macos10.14-x86.tar.gz
      Caused by: java.io.IOException: Could not open inputStream for https://dev.mysql.com/get/Downloads//MySQL-8.0/mysql-8.0.17-macos10.14-x86.tar.gz
      Caused by: java.io.FileNotFoundException: https://dev.mysql.com/get/Downloads//MySQL-8.0/mysql-8.0.17-macos10.14-x86.tar.gz
      

    [ERROR] Errors: 
    [ERROR]   ChartResourceTest ? Distribution java.io.IOException: Could not open inputStre...
    [ERROR]   ConfigResourceTest ? Distribution java.io.IOException: Could not open inputStr...
    [ERROR]   DashboardResourceTest ? Distribution java.io.IOException: Could not open input...
    [ERROR]   DatabaseResourceTest ? Distribution java.io.IOException: Could not open inputS...

**To Reproduce**
Run: `mvn clean install` on MacBook Air (M1, 2020)

**Additional context**
As per https://github.com/wix/wix-embedded-mysql, the package is deprecated.
They have suggested an alternative as https://www.testcontainers.org/
cc: @amiorin @harshach

**Comment by pmbrull** [comment]
I could overcome this by installing an Intel JVM (Correto 11) + Rosetta2 to mimic an intel installation.

I also had other issues with the UI pom, where I need to tweak the versions. I believe there's a python dependency giving trouble on M1 as well.

**Comment by ayush-shah** [comment]
Yes, there are few Python dependencies which aren't supported on M1, we need to use Rosetta in some, and additional libraries + Rosetta in some.

For the above issue, should we switch to the alternative as the wix-embedded-mysql package is deprecated as per their repo ref: https://github.com/wix/wix-embedded-mysql?
cc: @sureshms @harshach @amiorin
