### ISSUE TITLE
Getting "Entity type role not found" error during secure startup

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3039]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
Hitting the following exception during secure startup:
```
org.openmetadata.catalog.exception.EntityNotFoundException: Entity type role not found
	at org.openmetadata.catalog.exception.EntityNotFoundException.byMessage(EntityNotFoundException.java:42)
	at org.openmetadata.catalog.Entity.getEntityReferenceById(Entity.java:131)
	at org.openmetadata.catalog.util.EntityUtil.populateEntityReferences(EntityUtil.java:241)
	at org.openmetadata.catalog.jdbi3.UserRepository.getRoles(UserRepository.java:200)
	at org.openmetadata.catalog.jdbi3.UserRepository.setFields(UserRepository.java:138)
	at org.openmetadata.catalog.jdbi3.UserRepository.setFields(UserRepository.java:43)
	at org.openmetadata.catalog.jdbi3.EntityRepository.createOrUpdate(EntityRepository.java:389)
	at org.openmetadata.catalog.jdbi3.EntityRepository.createOrUpdate(EntityRepository.java:374)
	at org.openmetadata.catalog.security.DefaultAuthorizer.addOrUpdateUser(DefaultAuthorizer.java:251)
	at org.openmetadata.catalog.security.DefaultAuthorizer.mayBeAddAdminUsers(DefaultAuthorizer.java:87)
	at org.openmetadata.catalog.security.DefaultAuthorizer.init(DefaultAuthorizer.java:63)
	at org.openmetadata.catalog.CatalogApplication.registerAuthorizer(CatalogApplication.java:184)
	at org.openmetadata.catalog.CatalogApplication.run(CatalogApplication.java:103)
	at org.openmetadata.catalog.CatalogApplication.run(CatalogApplication.java:69)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at org.openmetadata.catalog.CatalogApplication.main(CatalogApplication.java:239)
```

**To Reproduce**
Restart CatalogApplicationServer 

**Expected behavior**
The server starts without any errors.

**Version:**
 - OS: Mac
 - Python version: N/A
 - OpenMetadata version: Latest Main
 - OpenMetadata Ingestion package version: N/A

**Additional context**
 I suspect that the DefaultAuthorizer tries to lookup roles of admin users before the role entity can register [here](https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java#L112)
 Note: I was able to successfully start the server for the first time when I refreshed the database. But, subsequent starts fail with this error.

**Comment by mithmatt** [comment]
@vivekratnavel  This is possibly getting fixed with this #3049
