### ISSUE TITLE
Superset Ingestion fails with get_access_token error

### ISSUE THREAD

**Issue by juliarvalenti** [open-metadata/OpenMetadata#3162]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Framework

**Describe the bug**
When ingesting a superset instance using OpenMetadata ingestion CLI, it fails with the following error: 

```
Traceback (most recent call last):
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/metadata/cmd.py", line 73, in ingest
    workflow = Workflow.create(workflow_config)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 150, in create
    return cls(config)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 68, in __init__
    self.source: Source = source_class.create(
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/metadata/ingestion/source/superset.py", line 126, in create
    return cls(config, metadata_config, ctx)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/metadata/ingestion/source/superset.py", line 110, in __init__
    self.client = SupersetAPIClient(self.config)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/metadata/ingestion/ometa/superset_rest.py", line 76, in __init__
    self._auth_provider = SupersetAuthenticationProvider.create(config)
  File "/home/ubuntu/Jenkins/deploy_to_UMPdemo/openmetadata/OpenMetadata/docker/metadata/venv/lib/python3.9/site-packages/metadata/ingestion/ometa/superset_rest.py", line 49, in create
    return cls(config)
TypeError: Can't instantiate abstract class SupersetAuthenticationProvider with abstract method get_access_token 
```

Pinning the superset ingestion package to v0.8.8 has fixed this issue temporarily for me.

**To Reproduce**
1. Start with a fresh OpenMetadata and Superset instance. 
2. PIP install the ingestion CLI.  
3. Run `metadata ingest -c <CONFIG>`

**Expected behavior**
Ingestion should succeed.

**Version:**
 - OS: [e.g. iOS] iOS
 - Python version: 3.9.5
 - OpenMetadata version: [e.g. 0.8] 0.8.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]  0.8.15

**Comment by ayush-shah** [comment]
it is fixed in the upcoming release and is same as #3066 & #3156.
@juliarvalenti Let me know if you want the fix in the 0.8 release or the upcoming 0.9 release

**Comment by juliarvalenti** [comment]
Either way should be fine.  We can remove the pinned package version whenever the fix is in.

**Comment by harshach** [comment]
@ayush-shah lets backport this to 0.8 as well post our release
