### ISSUE TITLE
Sample Data Ingestion fails for columnTestType

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#3281]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**
Sample Data receives this error while ingesting the column tests.
      
      Traceback (most recent call last):
        File "/home/ayush/.local/lib/python3.8/site-packages/metadata/ingestion/sink/metadata_rest.py", line 504, in write_table_tests
          self.metadata.add_column_test(table=table, col_test=record.column_test)
        File "/home/ayush/.local/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/table_mixin.py", line 179, in add_column_test
          return self._add_tests(table=table, test=col_test, path="columnTest")
        File "/home/ayush/.local/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/table_mixin.py", line 153, in _add_tests
          resp = self.client.put(
        File "/home/ayush/.local/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 247, in put
          return self._request("PUT", path, data)
        File "/home/ayush/.local/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 171, in _request
          return self._one_request(method, url, opts, retry)
        File "/home/ayush/.local/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 201, in _one_request
          raise APIError(error, http_error) from http_error
      metadata.ingestion.ometa.client.APIError: Unrecognized field "columnTestType" (class org.openmetadata.catalog.tests.ColumnTestCase), not marked as ignorable (2 known properties: "config", "testType"])
       at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 151] (through reference chain: org.openmetadata.catalog.tests.ColumnTest["testCase"]->org.openmetadata.catalog.tests.ColumnTestCase["columnTestType"])
      [2022-03-08 21:20:00,714] ERROR    {metadata.ingestion.sink.metadata_rest:512} - Unrecognized field "columnTestType" (class org.openmetadata.catalog.tests.ColumnTestCase), not marked as ignorable (2 known properties: "config", "testType"])
       at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 151] (through reference chain: org.openmetadata.catalog.tests.ColumnTest["testCase"]->org.openmetadata.catalog.tests.ColumnTestCase["columnTestType"])

**To Reproduce**
Run Sample Data pipeline
Screenshots or steps to reproduce

cc: @harshach

**Comment by harshach** [comment]
@ayush-shah this is not reproducible if the make generate works as expected
