### ISSUE TITLE
REST Usage workflow

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#4271]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.9/site-packages/openmetadata/workflows/ingestion/common.py", line 50, in metadata_ingestion_workflow
    config = json.loads(workflow_config.json(encoder=show_secrets_encoder))
AttributeError: 'NoneType' object has no attribute 'json'
```

**Comment by pmbrull** [comment]
fixed by https://github.com/open-metadata/OpenMetadata/pull/4279
