### ISSUE TITLE
UI: My Data and Following data is not updated in the homepage

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#4341]
https://user-images.githubusercontent.com/1051198/164537313-793451ba-2d93-4a68-bac0-182cbce6fc9c.mov

cc @harshach

**Comment by harshach** [comment]
@akash-jain-10 this is working fine when I run it locally. Only on sandbox it doesn't work lets look at the logs

**Comment by harshach** [comment]
seeing errors
```ERROR [21:15:08.808] [ForkJoinPool-1-worker-59] o.o.c.e.AuditEventHandler - Failed to capture audit log for v1/tables/d4692e77-a374-4abb-bfd9-f7f912576fac/followers and method PUT due to e
ntityType is marked non-null but is null 
ERROR [21:15:08.809] [Thread-2] o.o.c.e.AbstractEventPublisher - Failed to publish event org.openmetadata.catalog.type.ChangeEvent@4d1e32b4[eventType=entityUpdated,entityType=table,entityI
d=d4692e77-a374-4abb-bfd9-f7f912576fac,entityFullyQualifiedName=sample_data.ecommerce_db.shopify.raw_product_catalog,previousVersion=0.1,currentVersion=0.1,userName=anonymous,timestamp=165
0575708808,changeDescription=org.openmetadata.catalog.type.ChangeDescription@497ccbea[fieldsAdded=[org.openmetadata.catalog.type.FieldChange@65a0b016[name=followers,oldValue=<null>,newValu
e=[org.openmetadata.catalog.type.EntityReference@172fd654[id=5518afcd-f8ef-44c8-9305-e8ed21a4b3c5,type=user,name=aaron_johnson0,fullyQualifiedName=aaron_johnson0,description=<null>,display
Name=Aaron Johnson,deleted=false,href=<null>]]]],fieldsUpdated=[],fieldsDeleted=[],previousVersion=0.1],entity=<null>] 
ERROR [21:15:08.815] [ForkJoinPool-1-worker-23] o.o.c.e.ChangeEventHandler - Failed to capture change event for method PUT due to  
java.lang.NullPointerException: entityType is marked non-null but is null
	at org.openmetadata.catalog.Entity.getEntityRepository(Entity.java:242)
	at org.openmetadata.catalog.Entity.getEntityInterface(Entity.java:221)
	at org.openmetadata.catalog.events.ChangeEventHandler.getThreads(ChangeEventHandler.java:196)
	at org.openmetadata.catalog.events.ChangeEventHandler.process(ChangeEventHandler.java:79)
	at org.openmetadata.catalog.events.EventFilter.lambda$filter$0(EventFilter.java:70)
	at org.openmetadata.catalog.util.ParallelStreamUtil.lambda$runAsync$0(ParallelStreamUtil.java:74)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)```
