### ISSUE TITLE
Snowflake Profiler running into sql errors

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#4486]
**Affected module**
Ingestion

**Describe the bug**
[2022-04-25 18:11:40,338] {logging_mixin.py:109} INFO - (snowflake.connector.errors.ProgrammingError) 000603 (XX000): 01a3d923-0000-5073-0000-88c1000885a6: SQL execution internal error:
Processing aborted due to error 300010:391167117; incident 5388518.
[SQL: WITH only_once AS 
(SELECT count("DATABASE_NAME") AS count_1 
FROM "INFORMATION_SCHEMA"."REPLICATION_DATABASES" GROUP BY "DATABASE_NAME" 
HAVING count("DATABASE_NAME") = %(count_2)s)
 SELECT count(*) AS "uniqueCount" 
FROM only_once
 LIMIT %(param_1)s]
[parameters: {'count_2': 1, 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2022-04-25 18:11:40,339] {logging_mixin.py:109} INFO - Traceback (most recent call last):
  File "/opt/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/opt/airflow/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/airflow/venv/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 789, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/opt/airflow/venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 273, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/opt/airflow/venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/opt/airflow/venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 207, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000603 (XX000): 01a3d923-0000-5073-0000-88c1000885a6: SQL execution internal error:
Processing aborted due to error 300010:391167117; incident 5388518.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment]
@pmbrull @TeddyCr not sure if this is still an issue.

**Comment by pmbrull** [comment]
INFORMATION_SCHEMA tables are usually tricky and there's no value in profiling them. Let's close this. Profiler has been fixed for the rest of snowflake issues
