### ISSUE TITLE
The Python checkstyle failed.

### ISSUE THREAD

**Issue by MilanBariya** [open-metadata/OpenMetadata#4726]
**Affected module**
Python checkstyle failed by workflow.

**Describe the bug**

```
source env/bin/activate
  make generate
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:3).9.12/x6[4](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.12/x64/lib
Running Datamodel Code Generator
Make sure to first run the install_dev recipe
datamodel-codegen --input catalog-rest-service/src/main/resources/json --input-file-type jsonschema --output ingestion/src/metadata/generated --set-default-enum-member
/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py:397: UserWarning: format of 'utc-millisec' not understood for 'integer' - using default
  warn(
/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py:397: UserWarning: format of 'timezone' not understood for 'string' - using default
  warn(
Traceback (most recent call last):
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/http.py", line 4, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/__main__.py", line 49[5](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:5), in main
    generate(
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/__init__.py", line 353, in generate
    results = parser.parse()
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/base.py", line 42[6](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:6), in parse
    self.parse_raw()
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 11[7](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:7)7, in parse_raw
    self._parse_file(self.raw_obj, obj_name, path_parts)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1255, in _parse_file
    self.parse_raw_obj(key, model, path)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1122, in parse_raw_obj
    self.parse_obj(name, JsonSchemaObject.parse_obj(raw), path)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1142, in parse_obj
    self.parse_ref(obj, path)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 10[8](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:8)4, in parse_ref
    self.parse_ref(value, path)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.[9](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:9)/site-packages/datamodel_code_generator/parser/jsonschema.py", line [10](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:10)81, in parse_ref
    self.parse_ref(item, path)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1064, in parse_ref
    self.resolve_ref(obj.ref)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1054, in resolve_ref
    self._get_ref_body(relative_path),
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1005, in _get_ref_body
    return self._get_ref_body_from_url(resolved_ref)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1010, in _get_ref_body_from_url
    return self.remote_object_cache.get_or_put(
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/__init__.py", line 26, in get_or_put
    value = self[key] = default_factory(key)
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 10[11](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:11), in <lambda>
    ref, default_factory=lambda key: load_yaml(self._get_text_from_url(key))
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/parser/base.py", line [39](https://github.com/open-metadata/OpenMetadata/runs/6275852671?check_suite_focus=true#step:6:39)8, in _get_text_from_url
    from datamodel_code_generator.http import get_body
  File "/home/runner/work/OpenMetadata/OpenMetadata/env/lib/python3.9/site-packages/datamodel_code_generator/http.py", line 6, in <module>
    raise Exception(
Exception: Please run $pip install datamodel-code-generator[http] to resolve URL Reference

make: *** [Makefile:63: generate] Error 1
Error: Process completed with exit code 2.

```

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
cc @pmbrull @ayush-shah

**Comment by pmbrull** [comment]
hi @MilanBariya , in which branch is this failing? Did you modify the JSON Schemas?

Just created a branch from `main` and I could generate the sources correctly. I've seen this error before though when having errors in linking JSON Schema definitions among files.

Thanks

**Comment by pmbrull** [comment]
Hi @MilanBariya, I left a comment in the PR.

Let us know if you need further help with that. But this is not a general issue in the code but something related to a change, so I'll close the issue.
