### ISSUE TITLE
Profiler - Snowflake doesn't work

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#4895]
When running standalone profiler via UI / Ingestion CLI

          [2022-05-11 14:16:29,172] {taskinstance.py:1463} ERROR - Task failed with exception
          Traceback (most recent call last):
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
              self.dialect.do_execute(
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
              cursor.execute(statement, parameters)
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 794, in execute
              Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 273, in errorhandler_wrapper
              handed_over = Error.hand_to_other_handler(
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
              cursor.errorhandler(connection, cursor, error_class, error_value)
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 207, in default_errorhandler
              raise error_class(
          snowflake.connector.errors.ProgrammingError: 090105 (22000): 01a43238-0000-0550-0000-157900113cf2: Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
          
          The above exception was the direct cause of the following exception:
          
          Traceback (most recent call last):
            File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
              self._prepare_and_execute_task_with_callbacks(context, task)
            File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
              result = self._execute_task(context, task_copy)
            File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
              result = task_copy.execute(context=context)
            File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
              return_value = self.execute_callable()
            File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
              return self.python_callable(*self.op_args, **self.op_kwargs)
            File "/usr/local/lib/python3.9/site-packages/openmetadata/workflows/ingestion/common.py", line 76, in profiler_workflow
              workflow.execute()
            File "/usr/local/lib/python3.9/site-packages/metadata/orm_profiler/api/workflow.py", line 182, in execute
              profile_and_tests: ProfilerResponse = self.processor.process(entity)
            File "/usr/local/lib/python3.9/site-packages/metadata/orm_profiler/processor/orm_profiler.py", line 480, in process
              entity_profile = self.profile_entity(orm_table, record)
            File "/usr/local/lib/python3.9/site-packages/metadata/orm_profiler/processor/orm_profiler.py", line 179, in profile_entity
              profiler.execute()
            File "/usr/local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/core.py", line 341, in execute
              self.run_table_metrics()
            File "/usr/local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/core.py", line 252, in run_table_metrics
              row = self.runner.select_first_from_table(
            File "/usr/local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/runner.py", line 54, in select_first_from_table
              return self._build_query(*entities, **kwargs).select_from(self._table).first()
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2819, in first
              return self.limit(1)._iter().first()
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
              result = self.session.execute(
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
              result = conn._execute_20(statement, params or {}, execution_options)
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
              return meth(self, args_10style, kwargs_10style, execution_options)
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
              return connection._execute_clauseelement(
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
              ret = self._execute_context(
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
              self._handle_dbapi_exception(
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
              util.raise_(
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
              raise exception
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
              self.dialect.do_execute(
            File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
              cursor.execute(statement, parameters)
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 794, in execute
              Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 273, in errorhandler_wrapper
              handed_over = Error.hand_to_other_handler(
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
              cursor.errorhandler(connection, cursor, error_class, error_value)
            File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 207, in default_errorhandler
              raise error_class(
          sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 090105 (22000): 01a43238-0000-0550-0000-157900113cf2: Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
          [SQL: SELECT count(*) AS "rowCount", %(param_1)s AS "columnCount" 
          FROM "TPCDS_SF100TCL"."CALL_CENTER"
           LIMIT %(param_2)s]
          [parameters: {'param_1': 31, 'param_2': 1}]
          (Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by pmbrull** [comment]
happening when snowflake connection does not have the database informed
