### ISSUE TITLE
DataProfiler fails for empty tables in clickhouse

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#4935]
**Affected module**
Ingestion Framework

**Describe the bug**
when enabling the data profiler and ingesting the clickhouse connector with empty tables -  getting following error.
```
[2022-05-13 16:48:36] INFO     {OMetaAPI:sql_source:91} - Table Scanned: local_clickhouse.default.default.session_log1
[2022-05-13 16:48:36] ERROR    {Ingestion:metadata_rest:254} - Failed to ingest table session_log1 in database default
[2022-05-13 16:48:36] ERROR    {Ingestion:metadata_rest:261} - Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 478] (through reference chain: org.openmetadata.catalog.type.TableProfile["columnProfile"]->java.util.ArrayList[0])
```

The Full error stack 
```
[2022-05-13 17:18:21] INFO     {OMetaAPI:sql_source:91} - Table Scanned: local_clickhouse.default.default.session_log1
Traceback (most recent call last):
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 201, in _one_request
    resp.raise_for_status()
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8585/api/v1/tables/05c702a0-861f-4b61-a3d1-99ec3498637a/tableProfile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/cmd.py", line 72, in ingest
    run_ingest(config_path=config)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/cli/ingest.py", line 47, in run_ingest
    workflow.execute()
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 161, in execute
    self.sink.write_record(processed_record)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/sink/metadata_rest.py", line 113, in write_record
    self.write_tables(record)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/sink/metadata_rest.py", line 219, in write_tables
    self.metadata.ingest_table_profile_data(
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/table_mixin.py", line 83, in ingest_table_profile_data
    resp = self.client.put(
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 255, in put
    return self._request("PUT", path, data)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 178, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 209, in _one_request
    raise APIError(error, http_error) from http_error
metadata.ingestion.ometa.client.APIError: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 478] (through reference chain: org.openmetadata.catalog.type.TableProfile["columnProfile"]->java.util.ArrayList[0])
```

The tables gets ingested only the profiler fails.

**To Reproduce**
Ingest clickhouse with some empty tables

**Comment by harshach** [comment]
@ulixius9 @TeddyCr are we going to handle this in this release . If not lets move it 0.12.0 release cc @pmbrull

**Comment by TeddyCr** [comment]
@harshach I should have bandwidth to work on a fix before Friday. @pmbrull @ulixius9 do you see anything with higher priority for 0.11.0?

**Comment by pmbrull** [comment]
@TeddyCr if you have the time let's call it done this release! thanks
