### ISSUE TITLE
Fix usage workflow

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5417]
**Affected module**
Ingestion

**Describe the bug**
Sample usage not working

```
>           raise validation_error
E           pydantic.error_wrappers.ValidationError: 1 validation error for ConfigModel
E           filter
E             extra fields not permitted (type=value_error.extra)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1308, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/ingestion/examples/airflow/dags/airflow_sample_usage.py", line 78, in metadata_ingestion_workflow
    workflow = Workflow.create(workflow_config)
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 158, in create
    return cls(config)
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 94, in __init__
    self.processor: Processor = processor_class.create(
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/processor/query_parser.py", line 64, in create
    config = ConfigModel.parse_obj(config_dict)
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 578, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ConfigModel
filter
  extra fields not permitted (type=value_error.extra)
```
**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ulixius9** [comment]
Closing this issue as not reproducible
