### ISSUE TITLE
"No module named pandas"

### ISSUE THREAD

**Issue by Sebov1c** [open-metadata/OpenMetadata#573]
Scheduler throws "ModuleNotFoundError: No module named 'pandas'":

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/simplescheduler/corescheduler/core/base.py", line 106, in run_scheduler_job
    result = job_class.run_job(job_id, execution_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplescheduler/corescheduler/job.py", line 94, in run_job
    return job.run(*args, **kwargs)
  File "/openmetadata-ingestion/ingestion_scheduler/jobs.py", line 40, in run
    self.workflow = Workflow.create(config_data)
  File "/usr/local/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 125, in create
    return cls(config)
  File "/usr/local/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 66, in __init__
    source_class = self.get('metadata.ingestion.source.{}.{}Source'.format(
  File "/usr/local/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 119, in get
    MyClass = getattr(importlib.import_module(module_name), class_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/metadata/ingestion/source/sample_data.py", line 17, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Steps to reproduce: 

```sh
git clone https://github.com/open-metadata/OpenMetadata
cd OpenMetadata/docker/metadata
docker-compose up
# Once OpenMetadata UI is accessible, Go to Scheduler UI - http://localhost:7777, to invoke the pipelines to ingest data. 
```

**Comment by harshach** [comment]
Thanks for filing the issue @Sebov1c we are looking into this.

**Comment by harshach** [comment]
@Sebov1c we fixed the issue. Please purge your locally cached docker images and pull them again. Thanks.
