### ISSUE TITLE
Metabase ingestion fails when the chart/dashboard title contains the character `/`

### ISSUE THREAD

**Issue by psg2** [open-metadata/OpenMetadata#6166]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

Ingestion Framework

**Describe the bug**

While trying to run the metabase connector I can see from the logs that a given chart is properly ingested to OpenMetadata, but soon after the PUT request the DAG task tries to issue a following GET to the same chart and fails because it doesn't encode the `/` character as `%2F`.

Slack thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1658169865125849

<details>
<summary>Execution log</summary>

[2022-07-18 18:38:14,882] {server_mixin.py:86} DEBUG - Validating client and server versions
[2022-07-18 18:38:14,883] {client.py:176} DEBUG - URL http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/version, method GET
[2022-07-18 18:38:14,883] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-07-18 18:38:15,142] {server_mixin.py:86} DEBUG - Validating client and server versions
[2022-07-18 18:38:15,143] {client.py:176} DEBUG - URL http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/version, method GET
[2022-07-18 18:38:15,143] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-07-18 18:38:15,322] {workflow.py:81} DEBUG - Source type:metabase,<class 'metadata.ingestion.source.dashboard.metabase.MetabaseSource'> configured
[2022-07-18 18:38:15,322] {workflow.py:83} DEBUG - Source type:metabase,<class 'metadata.ingestion.source.dashboard.metabase.MetabaseSource'>  prepared
[2022-07-18 18:38:15,420] {server_mixin.py:86} DEBUG - Validating client and server versions
[2022-07-18 18:38:15,420] {client.py:176} DEBUG - URL http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/version, method GET
[2022-07-18 18:38:15,420] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-07-18 18:38:15,432] {workflow.py:123} DEBUG - Sink type:metadata-rest,<class 'metadata.ingestion.sink.metadata_rest.MetadataRestSink'> configured
[2022-07-18 18:38:15,432] {topology_runner.py:59} DEBUG - Processing node producer='get_services' stages=[NodeStage(type_=<class 'metadata.generated.schema.entity.services.dashboardService.DashboardService'>, processor='yield_dashboard_service', context='dashboard_service', ack_sink=True, nullable=False, cache_all=False, clear_cache=False, consumer=None), NodeStage(type_=<class 'metadata.ingestion.models.ometa_tag_category.OMetaTagAndCategory'>, processor='yield_tag', context='tags', ack_sink=False, nullable=True, cache_all=False, clear_cache=False, consumer=None)] children=['dashboard'] post_process=None
[2022-07-18 18:38:15,432] {topology_runner.py:70} DEBUG - Processing stage type_=<class 'metadata.generated.schema.entity.services.dashboardService.DashboardService'> processor='yield_dashboard_service' context='dashboard_service' ack_sink=True nullable=False cache_all=False clear_cache=False consumer=None
[2022-07-18 18:38:15,435] {client.py:176} DEBUG - URL http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/services/dashboardServices, method PUT
[2022-07-18 18:38:15,435] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'data': '{"name": "pilot_metabase", "displayName": null, "description": null, "serviceType": "Metabase", "connection": {"config": {"type": "Metabase", "username": "metasheets@clicampo.com.br", "password": "2kTbDcFRJuODia", "hostPort": "[http://core-shared-main-metabase.metabase.svc.cluster.local:80](http://core-shared-main-metabase.metabase.svc.cluster.local/)", "supportsMetadataExtraction": true}}, "owner": null}'}
[2022-07-18 18:38:15,466] {metadata_rest.py:162} INFO - Successfully ingested CreateDashboardServiceRequest [pilot_metabase]
[2022-07-18 18:38:15,467] {client.py:176} DEBUG - URL http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/services/dashboardServices/name/pilot_metabase?fields=*, method GET
[2022-07-18 18:38:15,467] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-07-18 18:38:15,499] {topology_runner.py:185} DEBUG - dashboard_service=DashboardService(id=Uuid(__root__=UUID('33e6e7de-15fe-4b1d-b2d6-01107d9e20da')), name=EntityName(__root__='pilot_metabase'), fullyQualifiedName=FullyQualifiedEntityName(__root__='pilot_metabase'), displayName=None, serviceType=<DashboardServiceType.Metabase: 'Metabase'>, description=None, connection=DashboardConnection(config=MetabaseConnection(type=<MetabaseType.Metabase: 'Metabase'>, username='metasheets@clicampo.com.br', password=SecretStr('**********'), hostPort=AnyUrl('[http://core-shared-main-metabase.metabase.svc.cluster.local:80](http://core-shared-main-metabase.metabase.svc.cluster.local/)', scheme='http', host='core-shared-main-metabase.metabase.svc.cluster.local', tld='local', host_type='domain', port='80'), supportsMetadataExtraction=SupportsMetadataExtraction(__root__=True))), pipelines=EntityReferenceList(__root__=[EntityReference(id=Uuid(__root__=UUID('47615df6-2100-4c7a-b685-0f02ba397d96')), type='ingestionPipeline', name='pilot_metabase_metadata', fullyQualifiedName='pilot_metabase.pilot_metabase_metadata', description=None, displayName='pilot_metabase_metadata', deleted=False, href=None)]), owner=EntityReference(id=Uuid(__root__=UUID('146a4268-d727-4ed7-9e65-ec4fe10414ec')), type='user', name='anonymous', fullyQualifiedName='anonymous', description=None, displayName=None, deleted=False, href=Href(__root__=AnyUrl('http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/users/146a4268-d727-4ed7-9e65-ec4fe10414ec', scheme='http', host='openmetadata.open-metadata.svc.cluster.local', tld='local', host_type='domain', port='8585', path='/api/v1/users/146a4268-d727-4ed7-9e65-ec4fe10414ec'))), version=EntityVersion(__root__=0.2), updatedAt=Timestamp(__root__=1658169181085), updatedBy='anonymous', href=Href(__root__=AnyUrl('http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/services/dashboardServices/33e6e7de-15fe-4b1d-b2d6-01107d9e20da', scheme='http', host='openmetadata.open-metadata.svc.cluster.local', tld='local', host_type='domain', port='8585', path='/api/v1/services/dashboardServices/33e6e7de-15fe-4b1d-b2d6-01107d9e20da')), changeDescription=ChangeDescription(fieldsAdded=[], fieldsUpdated=[], fieldsDeleted=[FieldChange(name=FieldName(__root__='description'), oldValue='', newValue=None)], previousVersion=EntityVersion(__root__=0.1)), deleted=False) tags=None charts=[] owner=None dashboard=None lineage=None usage=None
[2022-07-18 18:38:15,500] {topology_runner.py:70} DEBUG - Processing stage type_=<class 'metadata.ingestion.models.ometa_tag_category.OMetaTagAndCategory'> processor='yield_tag' context='tags' ack_sink=False nullable=True cache_all=False clear_cache=False consumer=None
[2022-07-18 18:38:15,500] {topology_runner.py:59} DEBUG - Processing node producer='get_dashboard' stages=[NodeStage(type_=<class 'metadata.generated.schema.entity.data.chart.Chart'>, processor='yield_dashboard_chart', context='charts', ack_sink=True, nullable=True, cache_all=True, clear_cache=True, consumer=['dashboard_service']), NodeStage(type_=<class 'metadata.generated.schema.api.teams.createUser.CreateUserRequest'>, processor='yield_owner', context='owner', ack_sink=True, nullable=True, cache_all=False, clear_cache=False, consumer=None), NodeStage(type_=<class 'metadata.generated.schema.entity.data.dashboard.Dashboard'>, processor='yield_dashboard', context='dashboard', ack_sink=True, nullable=False, cache_all=False, clear_cache=False, consumer=['dashboard_service']), NodeStage(type_=<class 'metadata.generated.schema.api.lineage.addLineage.AddLineageRequest'>, processor='yield_dashboard_lineage', context='lineage', ack_sink=False, nullable=True, cache_all=False, clear_cache=False, consumer=['dashboard_service']), NodeStage(type_=<class 'metadata.generated.schema.type.usageRequest.UsageRequest'>, processor='yield_dashboard_usage', context='usage', ack_sink=False, nullable=True, cache_all=False, clear_cache=False, consumer=['dashboard_service'])] children=None post_process=None
[2022-07-18 18:38:15,574] {topology_runner.py:70} DEBUG - Processing stage type_=<class 'metadata.generated.schema.entity.data.chart.Chart'> processor='yield_dashboard_chart' context='charts' ack_sink=True nullable=True cache_all=True clear_cache=True consumer=['dashboard_service']
[2022-07-18 18:38:15,577] {client.py:176} DEBUG - URL http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/charts, method PUT
[2022-07-18 18:38:15,577] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'data': '{"name": "GMV, Volume e AVG Price - Couve Manteiga - Promo 06/07", "displayName": "GMV, Volume e AVG Price - Couve Manteiga - Promo 06/07", "description": null, "chartType": "Line", "chartUrl": "/question/976-gmv--volume-e-avg-price---couve-manteiga---promo-06-07", "tables": null, "tags": null, "owner": null, "service": {"id": "33e6e7de-15fe-4b1d-b2d6-01107d9e20da", "type": "dashboardService", "name": null, "fullyQualifiedName": null, "description": null, "displayName": null, "deleted": null, "href": null}}'}
[2022-07-18 18:38:15,614] {metadata_rest.py:354} INFO - Successfully ingested chart GMV, Volume e AVG Price - Couve Manteiga - Promo 06/07
[2022-07-18 18:38:15,615] {client.py:176} DEBUG - URL http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/charts/name/pilot_metabase.GMV, Volume e AVG Price - Couve Manteiga - Promo 06/07?fields=*, method GET
[2022-07-18 18:38:15,615] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-07-18 18:38:15,627] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata/workflows/ingestion/common.py", line 113, in metadata_ingestion_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 161, in execute
    for record in self.source.next_record():
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 104, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 89, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 77, in process_nodes
    yield from self.sink_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 172, in sink_request
    entity = self.metadata.get_by_name(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 461, in get_by_name
    return self._get(entity=entity, path=f"name/{model_str(fqn)}", fields=fields)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 486, in _get
    resp = self.client.get(f"{self.get_suffix(entity)}/{path}{fields_str}")
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 228, in get
    return self._request("GET", path, data)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 178, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 200, in _one_request
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://openmetadata.open-metadata.svc.cluster.local:8585/api/v1/charts/name/pilot_metabase.GMV,%20Volume%20e%20AVG%20Price%20-%20Couve%20Manteiga%20-%20Promo%2006/07?fields=*

</details>

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
I expect that the ingestion runs without any error and ingests all the charts and dashboards that might contain a character `/` in their titles.

**Version:**
 - Python version: 3.9.9
 - OpenMetadata version: [e.g. 0.8] 0.11.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 0.11.1.0

**Additional context**

**Comment by psg2** [comment]
Fixed by: #6034 (https://github.com/open-metadata/OpenMetadata/pull/6034/files#diff-22e569a56888ff22f40648ce7663d1f987fb90a6cd2b300fc222d7f12b3efce4R464)

Waiting release
