### ISSUE TITLE
Ingestion failed error 500

### ISSUE THREAD

**Issue by jlanka8** [open-metadata/OpenMetadata#6540]
**Affected module**
backend or Ingestion Framework

**Describe the bug**
Ingestion Hive failed error 500

**To Reproduce**
```
[2022-08-03 10:03:59,773] {common_db_source.py:184} WARNING - Table Description Error :
[2022-08-03 10:03:59,846] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata/workflows/ingestion/common.py", line 114, in metadata_ingestion_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 171, in execute
    self.sink.write_record(processed_record)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/sink/metadata_rest.py", line 150, in write_record
    self.write_create_request(record)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/sink/metadata_rest.py", line 159, in write_create_request
    created = self.metadata.create_or_update(entity_request)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 445, in create_or_update
    resp = self.client.put(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 254, in put
    return self._request("PUT", path, data)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 178, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 200, in _one_request
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://open-metadata:8585/api/v1/tables
[2022-08-03 10:03:59,852] {taskinstance.py:1506} INFO - Marking task as UP_FOR_RETRY. dag_id=HIVE_DMP__metadata, task_id=ingestion_task, execution_date=20220802T161344, start_date=20220803T004706, end_date=20220803T070359
```
**Table and description:**
**fm_ra_platform_dds.dds_fct_cmd_fms_pre_post_gprs_traffic**

```
scala> sql("show partitions fm_ra_platform_dds.dds_fct_cmd_fms_pre_post_gprs_traffic").show(10,false)
Hive Session ID = 86b608b1-a217-4b6d-af5a-4fcafa83ef83
+--------------------------------------+
|partition                             |
+--------------------------------------+
|msk_date=2022-07-03/part_date=20220702|
|msk_date=2022-07-03/part_date=20220703|
|msk_date=2022-07-03/part_date=20220704|
|msk_date=2022-07-04/part_date=20220703|
|msk_date=2022-07-04/part_date=20220704|
|msk_date=2022-07-04/part_date=20220705|
|msk_date=2022-07-05/part_date=20220704|
|msk_date=2022-07-05/part_date=20220705|
|msk_date=2022-07-05/part_date=20220706|
|msk_date=2022-07-06/part_date=20220705|
+--------------------------------------+
only showing top 10 rows
            describe    fm_ra_platform_dds.dds_fct_cmd_fms_pre_post_gprs_traffic").show(false)
+-----------------------+---------+-------+
|col_name               |data_type|comment|
+-----------------------+---------+-------+
|town                   |string   |null   |
|imsi                   |string   |null   |
|apn                    |string   |null   |
|originalcallednumber   |string   |null   |
|orignetworkcode        |string   |null   |
|duration               |int      |null   |
|dialleddigits          |string   |null   |
|scrfilename            |string   |null   |
|msisdn                 |string   |null   |
|chargeamountpps        |float    |null   |
|balancepps             |float    |null   |
|sttime                 |string   |null   |
|ggsn_time_shift        |bigint   |null   |
|u_start_time           |string   |null   |
|hour                   |int      |null   |
|zona                   |string   |null   |
|msk_date               |date     |null   |
|part_date              |string   |null   |
|# Partition Information|         |       |
|# col_name             |data_type|comment|
+-----------------------+---------+-------+
```

**Expected behavior**
Ingestion finished successfully

**Version:**
 - OS: k8s, CentOS 7
 - Python version:
 - OpenMetadata version: 0.11.3

**Additional context**
I checked all server's logs, but unfortunately there was not a single error message.

**Comment by pmbrull** [comment]
Thanks for opening the issue @jlanka8

@ulixius9 here we need to ensure that the workflow does not stop even when we get an error to a specific table. This is specially painful for long-running processes
