### ISSUE TITLE
Airflow pipeline metadata ingestion AttributeError("can't set attribute")

### ISSUE THREAD

**Issue by stepanof** [open-metadata/OpenMetadata#6680]
**Affected module**
built-in Airflow

**Describe the bug**
I have created ingestion for Airflow pipeline
![image](https://user-images.githubusercontent.com/68236577/183879181-7b3086c8-9672-4088-b195-d74389aa0e31.png)
So created dag 'Airflow_metadata' falls because of errors, here is log:
*** Reading local file: /airflow/logs/Airflow_metadata/ingestion_task/2022-08-10T10:14:28+00:00/1.log
[2022-08-10 10:14:30,508] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py:627 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,514] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/dag.py:1056 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,518] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: Airflow_metadata.ingestion_task 2022-08-10T10:14:28+00:00 [queued]>
[2022-08-10 10:14:30,532] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: Airflow_metadata.ingestion_task 2022-08-10T10:14:28+00:00 [queued]>
[2022-08-10 10:14:30,532] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2022-08-10 10:14:30,532] {taskinstance.py:1096} INFO - Starting attempt 1 of 4
[2022-08-10 10:14:30,532] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2022-08-10 10:14:30,535] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py:1105 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,542] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py:1106 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,551] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): ingestion_task> on 2022-08-10T10:14:28+00:00
[2022-08-10 10:14:30,559] {standard_task_runner.py:52} INFO - Started process 644304 to run task
[2022-08-10 10:14:30,565] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_metadata', 'ingestion_task', '2022-08-10T10:14:28+00:00', '--job-id', '52', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Airflow_metadata.py', '--cfg-path', '/tmp/tmp1yxty3mw', '--error-file', '/tmp/tmptuoujn01']
[2022-08-10 10:14:30,566] {standard_task_runner.py:77} INFO - Job 52: Subtask ingestion_task
[2022-08-10 10:14:30,596] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py:629 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,611] {logging_mixin.py:109} INFO - Running <TaskInstance: Airflow_metadata.ingestion_task 2022-08-10T10:14:28+00:00 [running]> on host 73bfe7522f1a
[2022-08-10 10:14:30,619] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py:1158 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,637] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py:685 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,645] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/renderedtifields.py:125 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,657] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/renderedtifields.py:176 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2022-08-10 10:14:30,660] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/renderedtifields.py:173 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-08-10 10:14:30,664] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Airflow_metadata
AIRFLOW_CTX_TASK_ID=ingestion_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-10T10:14:28+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-10T10:14:28+00:00
[2022-08-10 10:14:31,951] {airflow.py:359} ERROR - AttributeError("can't set attribute")
........................................the same many times................................................
[2022-08-10 10:14:32,158] {airflow.py:359} ERROR - AttributeError("can't set attribute")
[2022-08-10 10:14:32,165] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.9/site-packages/openmetadata/workflows/ingestion/common.py", line 115, in metadata_ingestion_workflow
    workflow.raise_from_status()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 189, in raise_from_status
    raise WorkflowExecutionError(
metadata.config.common.WorkflowExecutionError: ('Source reported errors', AirflowSourceStatus(success=[], failures=[{'dag_name': 'AttributeError("can\'t set attribute")'}, {'dag_name_2': 'AttributeError("can\'t set attribute")'},........blablabla.............. '}], warnings=[], filtered=[], pipelines_scanned=[]))
[2022-08-10 10:14:32,168] {taskinstance.py:1506} INFO - Marking task as UP_FOR_RETRY. dag_id=Airflow_metadata, task_id=ingestion_task, execution_date=20220810T101428, start_date=20220810T101430, end_date=20220810T101432
..................................

**Expected behavior**
I expect ingestion without errors :)

**Version:**
 - OS: ubuntu
 - Python version: Python 3.9.5
 - OpenMetadata version: 0.11.3
 - openmetadata-airflow-managed-apis @ file:///openmetadata-airflow-apis
openmetadata-ingestion @ file:///ingestion
- Airflow version - 2.3.3

**Comment by stepanof** [comment]
Log with debug strings:
```
[2022-08-17 12:04:10,508] {server_mixin.py:86} DEBUG - Validating client and server versions
[2022-08-17 12:04:10,509] {client.py:176} DEBUG - URL http://localhost:8585/api/v1/version, method GET
[2022-08-17 12:04:10,509] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-08-17 12:04:10,519] {client.py:176} DEBUG - URL http://localhost:8585/api/v1/services/pipelineServices/name/local_airflow, method GET
[2022-08-17 12:04:10,519] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-08-17 12:04:10,526] {workflow.py:81} DEBUG - Source type:airflow,<class 'metadata.ingestion.source.pipeline.airflow.AirflowSource'> configured
[2022-08-17 12:04:10,526] {workflow.py:83} DEBUG - Source type:airflow,<class 'metadata.ingestion.source.pipeline.airflow.AirflowSource'>  prepared
[2022-08-17 12:04:10,750] {server_mixin.py:86} DEBUG - Validating client and server versions
[2022-08-17 12:04:10,750] {client.py:176} DEBUG - URL http://localhost:8585/api/v1/version, method GET
[2022-08-17 12:04:10,750] {client.py:177} DEBUG - Data {'headers': {'Content-type': 'application/json', 'Authorization': '***'}, 'allow_redirects': False, 'params': None}
[2022-08-17 12:04:10,758] {workflow.py:123} DEBUG - Sink type:metadata-rest,<class 'metadata.ingestion.sink.metadata_rest.MetadataRestSink'> configured
[2022-08-17 12:04:11,610] {airflow.py:359} ERROR - AttributeError("can't set attribute")
[2022-08-17 12:04:11,611] {airflow.py:360} DEBUG - Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 341, in next_record
    yield from self.fetch_pipeline(serialized_dag)
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 220, in fetch_pipeline
    dag: SerializedDAG = serialized_dag.dag
  File "/usr/local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 175, in dag
    dag = SerializedDAG.from_dict(self.data)  # type: Any
  File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 790, in from_dict
    return cls.deserialize_dag(serialized_obj['dag'])
  File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 715, in deserialize_dag
    v = {task["task_id"]: SerializedBaseOperator.deserialize_operator(task) for task in v}
  File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 715, in <dictcomp>
    v = {task["task_id"]: SerializedBaseOperator.deserialize_operator(task) for task in v}
  File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 508, in deserialize_operator
    setattr(op, k, v)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 733, in __setattr__
    super().__setattr__(key, value)
AttributeError: can't set attribute

[2022-08-17 12:04:11,611] {airflow.py:361} DEBUG - <traceback object at 0x7fad2474b840>
[2022-08-17 12:04:11,612] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.9/site-packages/openmetadata/workflows/ingestion/common.py", line 115, in metadata_ingestion_workflow
    workflow.raise_from_status()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 189, in raise_from_status
    raise WorkflowExecutionError(
metadata.config.common.WorkflowExecutionError: ('Source reported errors', AirflowSourceStatus(success=[], failures=[{'airflow_log_cleanup': 'AttributeError("can\'t set attribute")'}], warnings=[], filtered=[], pipelines_scanned=[]))
```

**Comment by stepanof** [comment]
The same error while using airflow 2.1.4

**Comment by caupetit-itf** [comment]
same here with openmetadata 0.11.5 triyng to ingest with postgres method an airflow 2.3.3

**Comment by harshach** [comment]
@pmbrull can you take a look

**Comment by AlekseiDE** [comment]
@nahuelverdugo
