### ISSUE TITLE
Docker compose file not able to parse private key string

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#6819]
**Describe the bug**
        
         at [Source: (ByteArrayInputStream); line: 191, column: 1712]
        
                at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:278)
                at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:97)
                at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:137)
                at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
                at io.dropwizard.cli.Cli.run(Cli.java:78)
                at io.dropwizard.Application.run(Application.java:94)
                at org.openmetadata.catalog.CatalogApplication.main(CatalogApplication.java:308)
        Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
         in 'reader', line 189, column 7:
                  clientId: "0oaxxxxxxxxxxx5d7"
                  ^
        expected <block end>, but found '}'
         in 'reader', line 191, column 1712:
             ... QqUWuyQOi12N2izyEOakwxxxxxxxxxxx"'}
                                                 ^
**To Reproduce**
Tried passing OM_AUTH_AIRFLOW_OKTA_PRIVATE_KEY as 
docker/local-metadata/docker-compose.yaml
    
${OM_AUTH_AIRFLOW_OKTA_PRIVATE_KEY:-'{"p":"...."}'}

${OM_AUTH_AIRFLOW_OKTA_PRIVATE_KEY:-{"p":"...."}}

the above both the ways fail

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by ayush-shah** [comment]
Closing this issue
the keys should be wrapped in double quotes, having all the quotes inside that to be escaped.
paste the same in an env file

docker compose --env-file=<path-to-file> up 

Format:


      OM_AUTH_AIRFLOW_OKTA_PRIVATE_KEY="{\"p\":\"w-HYhd69ntWOzsFsJFEJy2O5VEio43TeE48TH2QY8y6K8DMJRdcMWdcEph-q_l4X3JpUHR5su6dUiWwQHpbS6Jcjr3rxSGyNTqfSSnQs2eDN7bR1BaebcftThySf6Ivj3nyeR-bM5FIG_bXCDkhG18a5GN8mOgxAvhzKBIMcmaU\",\"kty\":\"RSA\",\"q\":\"tKN3IHNCK9q-KkAsmms1Yq3bQJxanqA70w3il8MwQIEkcQQ0UnGaCMjmMh3I1IBozQTuOUq3IEj_AZF7tbj_vSWV_VrdFLPJ7soa_XmlWpbe1ttH3vb9DjU5qgOJq9-CZmBnmrbDqadvhDlO9nE3v9v0TcJObteCpDpUCAtWyFs\",\"d\":\"Pew0i_uWuWUWLLL5ec1N3z48WPwyjanxvBVjGxhvmfH7vZiIx2NnWlvYfzRqPwXrTkebkAgjedGWcrj8u1Zpz6443CltoeRY7zUGL8e2Q8os-4aUk4vw5PxoRzBRTWoIVKiQStEgEHgMHvsVB44cs84CNwcyIWXOIWVS97OlITbmwQ3jA2KScFgQ8Vuyl0Rko6PxvVRlXM_UZmOklERWTkJFTOcnbAfkFLJey--k00W1Iv2D11POJQpnqoM8yB-oIcsX-CkFfP63iJK25eip9ruB8hVPKSNsOufZpXPXesN6el_eKYSASHFIYZj_b18QLeDpqc7KekpQ3p7jfZ53KQ\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"test\",\"qi\":\"upP4LtatvZDkB2F_84afN-4BTJ6Zi1zpFWm-E1vB-NHaIbVNz51W8yZQSHf7nhZWKV89dEWy6iBVCGHxALad8iLDdeaWiqUhIkil1zHJ1ojD5iojCflm0PidFgKf6jR24AUpUBVh5szXW4i2sX5IhxuZN_05S20ZwdujiewAVi0\",\"dp\":\"lfqfcWipYSr8q_vXFDtkN3GEni7_-SArRWh_6MIYhGH3iZBaIjpUv5jte1C1-QsMVCFqE92OvWOSS6IM-Y7br7DBZwPIKH7M9xNx5QXsrWn94moQS6MYVv5q5we41DH_6AMcocrqyEqyBaIcEhlu_JmwcYWyXDGzhJzAZRIKXO0\",\"alg\":\"RS256\",\"dq\":\"ea5_ydE6avZAEZAHO8IqRR3eSwjIFoDTq9l3oUmv0FPuK19sq3ixDWffgTUFGvihIDJJEzjcYRgrB3BsCD7lrxGJlxBFSvPNfFiSk9sE4yAsXkl6gZyZXJ_IB1m4vJmkarhYMiUZashKW6SLJ4Gez1QontTcJthvvZc5Ee4peG8\",\"n\":\"ijfgMc3sh7yLsdo7COQ6G8ei8YoznZVuN73v-oU7r2o4sAXGeJYGw4-wTLNhhIWzZWtSR01BVNq2AQ8NlBFyt6QSMPf8QydomTpryrnJMA31C9hqmabO12OpOXjyOvPRODgxn5jcgE987UF9JmrYcOIM3GUdvvAZ3wURpcfW0ZgyW7EljREvSdAKOKm88FxEES81Y3VijCTfCcYgaLaEgiIQ95hzPzODQ-RIlnFhWukez-0C7uMf0u41JFYfYJNx_B-bgzyUBYgQBXSR4XQkio5ECgQaiIYva1PMoP7JPHA1-E7TIkHGt7D8E_XHylXYI3MlGsbJdMAf5o1mp6GFpw\"}"
