### ISSUE TITLE
Airflow metadata extraction of never ran DAGs

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7003]
```
[2022-08-29, 06:07:27 UTC] {metadata_rest.py:170} INFO - Successfully ingested CreatePipelineRequest [snow_metadata_hQWsEXKJ]
[2022-08-29, 06:07:27 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/ingestion/examples/airflow/dags/airflow_metadata_extraction.py", line 69, in metadata_ingestion_workflow
    workflow.execute()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 175, in execute
    for record in self.source.next_record():
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 112, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 96, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 80, in process_nodes
    for entity_request in stage_fn(element) or []:
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 192, in yield_pipeline_status
    tasks = self.get_task_instances(
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 176, in get_task_instances
    return [
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 177, in <listcomp>
    OMTaskInstance(
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for OMTaskInstance
state
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by pmbrull** [comment]
cannot replicate it. Could have been an issue with my local setup
