### ISSUE TITLE
Openmetadata unable to get SSL certificate

### ISSUE THREAD

**Issue by kartikeu** [open-metadata/OpenMetadata#7165]
**Affected module**
Ingestion framework

**Describe the bug**
Openmetadata is not able to find the SSL certificate when trying to transfer metadata from GCP Composer to the openmetadata server.

**To Reproduce**
We set up the openmetadata server on GKE with authentication and a certificate, our autheticated openmetadata server is working, we are able to log in and look at the home page
We now need to send data from our Composer cluster to the server. For this purpose, we are following [this](https://docs.open-metadata.org/openmetadata/connectors/pipeline/airflow/gcs)
I have pasted the config string that we are using below, the key in the service account credentials is the one we had for the certificate with which we authenticated our server ( We added that key to the service account)
```
config = f"""
source:
  type: airflow
  serviceName: airflow_gcs_composer
  serviceConnection:
    config:
      type: Airflow
      hostPort: http://localhost:8080/
      numberOfStatus: 10
      connection:
        type: Backend
  sourceConfig:
    config:
      type: PipelineMetadata
sink:
  type: metadata-rest
  config: {{}}
workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: https://openmetadata.olvin.com/
    authProvider: google
    securityConfig:
      secretKey: '{credentials}'
"""
```
However, in Airflow in Composer on running the above DAG, we are getting this error traceback:
```
[2022-09-02 12:05:12,829] {taskinstance.py:1465} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/python3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/python3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/python3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openmetadata.olvin.com', port=443): Max retries exceeded with url: //v1/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1166, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1310, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/gcs/dags/openMetadata/dag.py", line 94, in metadata_ingestion_workflow
    workflow = Workflow.create(workflow_config)
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 158, in create
    return cls(config)
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/api/workflow.py", line 78, in __init__
    self.source: Source = source_class.create(
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 128, in create
    return cls(config, metadata_config)
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 108, in __init__
    self.metadata = OpenMetadata(self.metadata_config)
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/ometa/ometa_api.py", line 179, in __init__
    self.validate_versions()
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/server_mixin.py", line 88, in validate_versions
    server_version = self.get_server_version()
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/server_mixin.py", line 70, in get_server_version
    raw_version = self.client.get("/version")["version"]
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 228, in get
    return self._request("GET", path, data)
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 178, in _request
    return self._one_request(method, url, opts, retry)
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/ometa/client.py", line 198, in _one_request
    resp = self._session.request(method, url, **opts)
  File "/opt/python3.8/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='openmetadata.olvin.com', port=443): Max retries exceeded with url: //v1/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
```

**Expected behavior**
Expected behavior is for the DAG to send the Composer metadata to the openmetadata server.

**Version:**
 -Composer image version: composer-1.19.5-airflow-2.1.4
 - Python version: 3.8
 - OpenMetadata Ingestion package version: openmetadata-ingestion==0.11.1
 - Openmetadata-dependencies were deployed through this yaml:
```
 # Default values for deps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
​
# MQSQL configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/bitnami/mysql
mysql:
  enabled: true
  fullnameOverride: "mysql"
  image:
    pullPolicy: "Always"
  auth:
    rootPassword: password    # provided by CI/CD
  primary:
    service:
      nodePort: 3306
  initdbScripts:
    init_openmetadata_db_scripts.sql: |
      CREATE DATABASE openmetadata_db;
      CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
      GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
      commit;
    init_airflow_db_scripts.sql: |
      CREATE DATABASE airflow_db;
      CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';
      GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT OPTION;
      commit;
​
# ElasticSearch configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/elastic/elasticsearch
elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  fullnameOverride: "elasticsearch"
  imagePullPolicy: "Always"
  esJavaOpts: "-Xmx128m -Xms128m"
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=20s"
  resources:
    requests:
      cpu: "100m"
      memory: "256M"
    limits:
      cpu: "1000m"
      memory: "1024M"
    
# Airflow configurations for helm dependency
# you can find more details about this here https://github.com/airflow-helm/charts
airflow:
  enabled: false
  airflow:
    image:
      repository: openmetadata/airflow
      tag: 0.11.3
      pullPolicy: "IfNotPresent"
    executor: "KubernetesExecutor"
    config:
      # This is required for OpenMetadata UI to fetch status of DAGs
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      # OpenMetadata Airflow Lineage Backend Configurations
      AIRFLOW__LINEAGE__BACKEND: airflow_provider_openmetadata.lineage.openmetadata.OpenMetadataLineageBackend
      AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME: airflow_helm
      AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT: http://openmetadata.default.svc.cluster.local:8585/api
      AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE: no-auth
      # OpenMetadata Airflow Apis Plugin DAGs Configuration
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_RUNNER_TEMPLATE: "/opt/airflow/dag_templates/dag_runner.j2"
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: "/opt/airflow/dags"
    users:
    - username: admin
      password: admin
      role: Admin
      email: spiderman@superhero.org
      firstName: Peter
      lastName: Parker
  web:
    readinessProbe:
      enabled: true
      initialDelaySeconds: 360
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
    livenessProbe:
      enabled: true
      initialDelaySeconds: 360
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
  postgresql:
    enabled: false
  workers:
    enabled: false
  flower:
    enabled: false
  redis:
    enabled: false
  externalDatabase:
    type: mysql
    host: mysql.default.svc.cluster.local
    port: 3306
    database: airflow_db
    user: airflow_user
    passwordSecret: airflow-mysql-secrets
    passwordSecretKey: airflow-mysql-password
  serviceAccount:
    create: true
    name: "airflow"
  dags:
    persistence:
      enabled: true
      # NOTE: "" means cluster-default
      storageClass: ""
      size: 1Gi
      accessMode: ReadWriteMany
  logs:
    persistence:
      enabled: true
      # empty string means cluster-default
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
```
 - Openmetadata was deployed through this yaml:
```
 # Default values for OpenMetadata.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
​
# Overrides the openmetadata config file with the help of Environment Variables
# Below are defaults as per openmetadata-dependencies Helm Chart Values
global:
  # Values can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
  logLevel: INFO
  openmetadata:
    host: openmetadata
    port: 8585
    adminPort: 8586
  elasticsearch:
    host: elasticsearch
    port: 9200
    scheme: http
    connectionTimeoutSecs: 5
    socketTimeoutSecs: 60
    batchSize: 10
    trustStore:
      enabled: false
      path: ""
      password:
        secretRef: "elasticsearch-truststore-secrets"
        secretKey: "openmetadata-elasticsearch-truststore-password"
    auth:
      enabled: false
      username: "elasticsearch"
      password:
        secretRef: elasticsearch-secrets
        secretKey: openmetadata-elasticsearch-password
  database:
    host: mysql
    port: 3306
    driverClass: com.mysql.cj.jdbc.Driver
    dbScheme: mysql
    dbUseSSL: false
    databaseName: openmetadata_db
    auth:
      username: openmetadata_user
      password:
        secretRef: mysql-secrets
        secretKey: openmetadata-mysql-password
  airflow:
    enabled: false
    # endpoint url for airflow
    host: https://yb6f3ad9ec97e359ep-tp.appspot.com/
    auth:
      username: admin
      password:
        secretRef: airflow-secrets
        secretKey: openmetadata-airflow-password
    openmetadata:
      # possible values are "no-auth", "azure", "google", "okta", "auth0", "custom-oidc", "openmetadata"
      authProvider: "google"
      # this will be the api endpoint url of OpenMetadata Server
      serverHostApiUrl: "http://openmetadata.default.svc.cluster.local:8585/api"
      authConfig:
        azure:
          clientSecret:
            secretRef: azure-client-secret
            secretKey: azure-client-secret
          authority: ""
          scopes: []
          clientId: ""
        google:
          # absolute path of secret file on airflow instance
          secretKeyPath: ""
          audience: "https://www.googleapis.com/oauth2/v4/token"
        okta:
          clientId: ""
          orgUrl: ""
          privateKey:
            secretRef: okta-client-private-key-secret
            secretKey: okta-client-private-key-secret
          email: ""
          scopes: []
        auth0:
          clientId: ""
          secretKey:
            secretRef: auth0-client-key-secret
            secretKey: auth0-client-key-secret
          domain: ""
        customOidc:
          clientId: ""
          secretKey:
            secretRef: custom-oidc-key-secret
            secretKey: custom-oidc-key-secret
          tokenEndpoint: ""
        openMetadata:
          jwtToken:
            secretRef: openmetadata-jwt-secret
            secretKey: openmetadata-jwt-secret
​
​
  # Example Google SSO Auth Config
  authorizer:
    className: "org.openmetadata.catalog.security.DefaultAuthorizer"
    containerRequestFilter: "org.openmetadata.catalog.security.JwtFilter"
    initialAdmins:
    - "admin"
    botPrincipal:
    - "ingestion-bot"
    principalDomain: "open-metadata.org"
  authentication:
    provider: "google"
    publicKeys:
    - "https://www.googleapis.com/oauth2/v3/certs"
    authority: "https://accounts.google.com"
    clientId: "350075951141-oosp8klppspjt546676f7prnp0c500h2.apps.googleusercontent.com"
    callbackUrl: "https://openmetadata.olvin.com/callback"
​
​
image:
  repository: openmetadata/server
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: "Always"
​
sidecars: []
# - name: "busybox"
#   image: "busybox:1.34.1"
#   imagePullPolicy: "Always"
#   command: ["ls"]
#   args: ["-latr", "/usr/share"]
#   env:
#   - name: DEMO
#     value: "DEMO"
#   volumeMounts:
#   - name: extras
#     mountPath: /usr/share/extras
#     readOnly: true
​
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "openmetadata"
​
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 100
​
service:
  type: ClusterIP
  port: 8585
  adminPort: 8586
  annotations: {}
​
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: open-metadata.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: tls-open-metadata.local
    #   hosts:
    #     - open-metadata.local
​
extraEnvs: []
# - name: MY_ENVIRONMENT_VAR
#   value: the_value_goes_here
​
extraVolumes: []
# - name: extras
#   emptyDir: {}
​
extraVolumeMounts: []
# - name: extras
#   mountPath: /usr/share/extras
#   readOnly: true
​
extraInitContainers: []
​
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
​
nodeSelector: {}
​
tolerations: []
​
affinity: {}
​
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5
​
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5
```

**Comment by pmbrull** [comment]
Thanks for opening such a detailed ticket. Slack thread for reference: https://openmetadata.slack.com/archives/C02B6955S4S/p1661853928592899

**Comment by pmbrull** [comment]
thanks, I am able to reproduce this. fixing it now
