### ISSUE TITLE
Pipeline Status from GCS Composer 2.2.5 backend

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7210]
Running the Airflow metadata ingestion from GCS Composer 2.2.5 gives us errors when picking up the status data:

```
[2022-09-04, 15:34:32 UTC] {topology_runner.py:216} DEBUG - pipeline_service=PipelineService(id=Uuid(__root__=UUID('09d7d6d9-99f4-4bf1-bba1-09f05aedf50d')), name=EntityName(__root__='airflow_gcs_composer'), fullyQualifiedName=FullyQualifiedEntityName(__root__='airflow_gcs_composer'), serviceType=<PipelineServiceType.Airflow: 'Airflow'>, description=None, displayName=None, version=EntityVersion(__root__=0.1), updatedAt=Timestamp(__root__=1662301781763), updatedBy='ingestion-bot', pipelines=EntityReferenceList(__root__=[]), connection=PipelineConnection(config=AirflowConnection(type=<AirflowType.Airflow: 'Airflow'>, hostPort=AnyUrl('http://localhost:8080/', scheme='http', host='localhost', host_type='int_domain', port='8080'), numberOfStatus=10, connection=BackendConnection(type=<BackendType.Backend: 'Backend'>), supportsMetadataExtraction=SupportsMetadataExtraction(__root__=True))), owner=None, href=Href(__root__=AnyUrl('http://sandbox-beta.open-metadata.org/api/v1/services/pipelineServices/09d7d6d9-99f4-4bf1-bba1-09f05aedf50d', scheme='http', host='sandbox-beta.open-metadata.org', tld='org', host_type='domain', path='/api/v1/services/pipelineServices/09d7d6d9-99f4-4bf1-bba1-09f05aedf50d')), changeDescription=None, deleted=False) pipeline=Pipeline(id=Uuid(__root__=UUID('020b8652-928c-403f-a73b-eb0978573b7f')), name=EntityName(__root__='airflow_monitoring'), displayName=None, fullyQualifiedName=FullyQualifiedEntityName(__root__='airflow_gcs_composer.airflow_monitoring'), description=Markdown(__root__='liveness monitoring dag'), version=EntityVersion(__root__=0.1), updatedAt=Timestamp(__root__=1662303361888), updatedBy='ingestion-bot', pipelineUrl='/tree?dag_id=airflow_monitoring', concurrency=100, pipelineLocation='/home/airflow/gcs/dags/airflow_monitoring.py', startDate=None, tasks=[Task(name='echo', displayName=None, fullyQualifiedName=None, description=None, taskUrl='/taskinstance/list/?flt1_dag_id_equals=airflow_monitoring&_flt_3_task_id=echo', downstreamTasks=[], taskType='BashOperator', taskSQL=None, startDate='2022-09-04T00:00:00+00:00', endDate=None, tags=None)], pipelineStatus=None, followers=EntityReferenceList(__root__=[]), tags=[], href=Href(__root__=AnyUrl('http://sandbox-beta.open-metadata.org/api/v1/pipelines/020b8652-928c-403f-a73b-eb0978573b7f', scheme='http', host='sandbox-beta.open-metadata.org', tld='org', host_type='domain', path='/api/v1/pipelines/020b8652-928c-403f-a73b-eb0978573b7f')), owner=None, service=EntityReference(id=Uuid(__root__=UUID('09d7d6d9-99f4-4bf1-bba1-09f05aedf50d')), type='pipelineService', name='airflow_gcs_composer', fullyQualifiedName='airflow_gcs_composer', description=None, displayName=None, deleted=False, href=Href(__root__=AnyUrl('http://sandbox-beta.open-metadata.org/api/v1/services/pipelineServices/09d7d6d9-99f4-4bf1-bba1-09f05aedf50d', scheme='http', host='sandbox-beta.open-metadata.org', tld='org', host_type='domain', path='/api/v1/services/pipelineServices/09d7d6d9-99f4-4bf1-bba1-09f05aedf50d'))), serviceType=<PipelineServiceType.Airflow: 'Airflow'>, changeDescription=None, deleted=False, extension=None) pipeline_status=None lineage=None
[2022-09-04, 15:34:32 UTC] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.ingestion.models.pipeline_status.OMetaPipelineStatus'> processor='yield_pipeline_status' context='pipeline_status' ack_sink=False nullable=True must_return=False cache_all=False clear_cache=False overwrite=True consumer=['pipeline_service']
[2022-09-04, 15:34:32 UTC] {airflow.py:137} DEBUG - DAG id airflow_monitoring has the following runs: [(60, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 15, 32, 47, 600336, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 32, 36, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 32, 48, 667992, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 32, 52, 600929, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T15:32:36+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 15, 32, 36, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 32, 36, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 32, 52, 594913, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (58, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 15, 26, 32, 756646, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 26, 21, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 26, 33, 444094, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 26, 39, 740890, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T15:26:21+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 15, 26, 21, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 26, 21, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 26, 39, 649801, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (57, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 15, 20, 29, 523637, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 20, 18, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 20, 30, 540963, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 20, 40, 71583, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T15:20:18+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 15, 20, 18, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 20, 18, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 20, 40, 65058, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (56, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 15, 14, 23, 253552, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 14, 11, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 14, 23, 859549, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 14, 27, 811986, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T15:14:11+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 15, 14, 11, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 14, 11, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 14, 27, 806315, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (55, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 15, 8, 14, 990901, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 8, 2, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 8, 15, 546961, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 8, 19, 502002, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T15:08:02+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 15, 8, 2, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 8, 2, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 8, 19, 494361, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (52, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 15, 2, 1, 908762, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 1, 47, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 2, 2, 542482, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 2, 6, 379064, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T15:01:47+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 15, 1, 47, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 1, 47, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 15, 2, 6, 372062, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (51, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 14, 55, 50, 745994, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 55, 29, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 55, 52, 158420, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 55, 58, 269220, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T14:55:29+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 14, 55, 29, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 55, 29, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 55, 58, 262176, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (49, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 14, 49, 36, 156544, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 49, 18, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 49, 37, 59589, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 49, 41, 649415, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T14:49:18+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 14, 49, 18, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 49, 18, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 49, 41, 562714, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (48, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 14, 43, 28, 555239, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 43, 13, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 43, 30, 355465, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 43, 35, 351480, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T14:43:13+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 14, 43, 13, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 43, 13, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 43, 35, 255305, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb'), (47, 'airflow_monitoring', datetime.datetime(2022, 9, 4, 14, 37, 20, 859547, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 37, 8, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 37, 21, 460007, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 37, 26, 162208, tzinfo=Timezone('UTC')), 'success', 'manual__2022-09-04T14:37:08+00:00', None, True, 'manual', {}, datetime.datetime(2022, 9, 4, 14, 37, 8, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 37, 8, tzinfo=Timezone('UTC')), datetime.datetime(2022, 9, 4, 14, 37, 26, 155420, tzinfo=Timezone('UTC')), '66341181b79d241e89ab8b4adb10ebbb')]
[2022-09-04, 15:34:32 UTC] {airflow.py:224} DEBUG - Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 192, in yield_pipeline_status
    dag_run_list = self.get_pipeline_status(pipeline_details.dag_id)
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 139, in get_pipeline_status
    dag_run_dict = [dict(elem) for elem in dag_run_list]
  File "/opt/python3.8/lib/python3.8/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 139, in <listcomp>
    dag_run_dict = [dict(elem) for elem in dag_run_list]
TypeError: tuple indices must be integers or slices, not str
```

**Comment by pmbrull** [comment]
Composer 2.2.5 also requires us to not install sqlalchemy in the base requirements

**Comment by TeddyCr** [comment]
Need to complete #7453

**Comment by harshach** [comment]
@MilanBariya any update on this

**Comment by MilanBariya** [comment]
@harshach Not started yet on this issue.
Thanks!

**Comment by pmbrull** [comment]
this is not reproducible, so we're closing it out. Nothing to fix. Thanks
