### ISSUE TITLE
Pipeline Status ingestion against Airflow 2.1.4

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#7228]
Running the metadata ingestion of Airflow from the UI uses Airflow 2.3.3.

The data model from the `TaskInstance` has changed over what was in 2.1.4. Airflow 2.3.3 uses the `run_id` internally when preparing a `TaskInstance`, which does not exist in 2.1.4.

```
Traceback (most recent call last):
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/airflow.py", line 171, in get_task_instances
    self.session.query(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2759, in all
    return self._iter().all()
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/pmbrull/projects/OpenMetadata/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'task_instance.run_id' in 'field list'")
[SQL: /* {"app": "OpenMetadata", "version": "0.12.0.dev0"} */
SELECT task_instance.task_id AS task_instance_task_id, task_instance.state AS task_instance_state, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.run_id AS task_instance_run_id 
FROM task_instance 
WHERE task_instance.dag_id = %(dag_id_1)s AND task_instance.run_id = %(run_id_1)s]
[parameters: {'dag_id_1': 'sample_lineage', 'run_id_1': 'scheduled__2022-09-04T05:34:34.583661+00:00'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Airflow ingestion for 2.1.4 works, but status is not being ingested.

We need to handle statuses as well in there

**Comment by harshach** [comment]
@pmbrull are we planning on supporting it?
