### ISSUE TITLE
Databricks issue with the `default` database

### ISSUE THREAD

**Issue by reneoctavio** [open-metadata/OpenMetadata#7668]
**Affected module**
Impacts the Ingestion Framework.

**Describe the bug**
1. It tries to get a None user from ES
2. Error in trying to describe columns
3. Error in parsing DBT files

Logs
1.
```
[2022-09-21 15:21:44,519] {client.py:535} INFO - /* {"app": "OpenMetadata", "version": "0.12.0.0"} */
SELECT 42
[2022-09-21 15:21:45,580] {dbt_source.py:69} INFO - Parsing Data Models
[2022-09-21 15:21:45,677] {elasticsearch.py:58} WARNING - ES Query was empty
[2022-09-21 15:21:45,683] {ometa_api.py:547} WARNING - GET User for name/None.Error 404 - user instance for None not found
[2022-09-21 15:21:45,683] {ometa_api.py:575} WARNING - Cannot find the Entity None
```

2.
```
[2022-09-21 15:22:14,873] {metadata_rest.py:165} INFO - Successfully ingested CreateDatabaseSchemaRequest [_intermediate]
[2022-09-21 15:22:14,902] {client.py:535} INFO - /* {"app": "OpenMetadata", "version": "0.12.0.0"} */
SHOW TABLES IN `_intermediate`
[2022-09-21 15:22:15,735] {client.py:535} INFO - /* {"app": "OpenMetadata", "version": "0.12.0.0"} */
DESCRIBE _intermediate.gi_dynamics_int_filter_atac_people
[2022-09-21 15:22:16,471] {client.py:535} INFO - /* {"app": "OpenMetadata", "version": "0.12.0.0"} */
DESCRIBE default.gi_dynamics_int_filter_atac_people dependents
[2022-09-21 15:22:16,688] {common_db_source.py:333} WARNING - Unexpected exception to yield table [gi_dynamics_int_filter_atac_people]: (databricks.sql.exc.OperationalError) Query execution failed. State: ERROR_STATE; Error code: 0; SQLSTATE: None; Error message: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: Table or view not found: default.gi_dynamics_int_filter_atac_people; line 2 pos 9
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:49)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$execute$1(SparkExecuteStatementOperation.scala:443)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.UCSDriver$Manager$Handle.runWith(UCSDriver.scala:272)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:356)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:269)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:139)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:49)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:54)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:247)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:232)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.AnalysisException: Table or view not found: default.gi_dynamics_int_filter_atac_people; line 2 pos 9
	at org.apache.spark.sql.AnalysisException.copy(AnalysisException.scala:115)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$execute$1(SparkExecuteStatementOperation.scala:437)
	... 19 more

[SQL: /* {"app": "OpenMetadata", "version": "0.12.0.0"} */
```

3.
```
[2022-09-21 16:20:50,006] {dbt_source.py:191} INFO - Processing DBT lineage
[2022-09-21 16:20:50,011] {ometa_api.py:547} WARNING - GET Table for name/databricks-trinus.hive_metastore.protheus.sra010.Error 404 - table instance for databricks-trinus.hive_metastore.protheus.sra010 not found
[2022-09-21 16:20:50,015] {ometa_api.py:547} WARNING - GET Table for name/databricks-trinus.hive_metastore.staging_protheus.stg_protheus_employees.Error 404 - table instance for databricks-trinus.hive_metastore.staging_protheus.stg_protheus_employees not found
```

**To Reproduce**

- Create a table inside a schema inside a catalog in Databricks.
- Create a connection to Databricks
- Add a Metadata Ingestion
- Start ingestion

**Expected behavior**
- It correctly selects the catalog.schema.table for the tables instead of using a catalog/database called `default`

**Version:**
 - OS: Ubuntu 20.04
 - OpenMetadata version: 0.12
 - Used the [Docker Quick install tutorial](https://docs.open-metadata.org/quick-start/local-deployment)

**Additional context**

I think the culprit is the lack of selecting a catalog or giving the option to go over all catalogs. It instead creates a `default` catalog, whilst I used `hive_metastore` in our dbt config as the catalog.
About the `DESCRIBE` command for the columns, it seems to be selecting a database/catalog.table instead of a database/catalog.schema.table.

**Comment by harshach** [comment]
Thanks for filling the issue @reneoctavio . We fixed the dbt owner issue
@ulixius9 the table not found issue also fixed right?

**Comment by pmbrull** [comment]
@ulixius9 could you please check the comment above? Thanks!

**Comment by ulixius9** [comment]
Hey! This needs to be validated, will be taking a look into this!

**Comment by Zurbste** [comment]
Hi all! We have the same problem with the ingestion service as described above (OSS version 0.12.2.4). Apparently there is no option to specify an explicit Catalog, so the 'default' Catalog is always queried.  

Is there an update for this issue?

**Comment by pmbrull** [comment]
Hi @Zurbste, the issue is currently in progress. You can follow it here. We'll merge it soon. Thanks
