### ISSUE TITLE
Unable to build Snowflake lineage because of mismatch in table name casing

### ISSUE THREAD

**Issue by fredriv** [open-metadata/OpenMetadata#7690]
**Affected module**
Ingestion Framework

**Describe the bug**
I am unable to build Snowflake lineage because Open Metadata fails to find the tables in the metadata previously ingested due to mismatch in casing of table names.

The SQL queries being analyzed as part of the lineage ingestion contain table names in lower case, e.g. `f_orders`. However, when ingesting metadata from Snowflake, the database, schema and table names are UPPER CASE, e.g. `F_ORDERS`.

Example table fully qualified name in the Open Metadata database: 
```
openmetadata_db=# select fullyqualifiedname from table_entity where fullyqualifiedname = 'Warehouse.ANALYTICS.ANALYTICS.F_ORDERS' ;
           fullyqualifiedname
----------------------------------------
 Warehouse.ANALYTICS.ANALYTICS.F_ORDERS
(1 row)
```

When running the Snowflake lineage ingestion, it tries to look up the table using the FQN `Warehouse.ANALYTICS.ANALYTICS.f_orders` instead which fails.

**To Reproduce**

Ingest lineage from Snowflake with lower case table names in the `create table` queries.

**Expected behavior**
I expect Open Metadata to be able to ingest the lineage regardless of whether the table names in the SQL queries are lower or upper case.

**Version:**
 - OS: MacOS
 - Python version: 3.9.9
 - OpenMetadata version: 0.12
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[snowflake]==0.12.0.2`

**Additional context**
Excerpt from the debug log:
```
[2022-09-23 12:17:52] DEBUG    {OMetaAPI:client:177} - URL http://localhost:8585/api/v1/tables/name/Warehouse.ANALYTICS.ANALYTICS.f_orders, method GET
[2022-09-23 12:17:52] DEBUG    {OMetaAPI:client:178} - Data {'headers': {'Content-type': 'application/json', 'Authorization': 'Bearer no_token'}, 'allow_redirects': False, 'params': None}
[2022-09-23 12:17:53] DEBUG    {OMetaAPI:ometa_api:546} - Traceback (most recent call last):
  File "/Users/fredriv/oda/de-hackathon/env/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 201, in _one_request
    resp.raise_for_status()
  File "/Users/fredriv/oda/de-hackathon/env/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8585/api/v1/tables/name/Warehouse.ANALYTICS.ANALYTICS.f_orders

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fredriv/oda/de-hackathon/env/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 539, in _get
    resp = self.client.get(f"{self.get_suffix(entity)}/{path}{fields_str}")
  File "/Users/fredriv/oda/de-hackathon/env/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 232, in get
    return self._request("GET", path, data)
  File "/Users/fredriv/oda/de-hackathon/env/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 179, in _request
    return self._one_request(method, url, opts, retry)
  File "/Users/fredriv/oda/de-hackathon/env/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 209, in _one_request
    raise APIError(error, http_error) from http_error
metadata.ingestion.ometa.client.APIError: table instance for Warehouse.ANALYTICS.ANALYTICS.f_orders not found

[2022-09-23 12:17:53] WARNING  {OMetaAPI:ometa_api:547} - GET Table for name/Warehouse.ANALYTICS.ANALYTICS.f_orders.Error 404 - table instance for Warehouse.ANALYTICS.ANALYTICS.f_orders not found
```

**Comment by fredriv** [comment]
This seems very similar to the previously reported issue related to table name casing during Fivetran pipeline ingestion: https://github.com/open-metadata/OpenMetadata/issues/7635

**Comment by pmbrull** [comment]
related to https://github.com/open-metadata/OpenMetadata/issues/7635

**Comment by nahuelverdugo** [comment]
I confirmed with the user that this is happening using PostgreSQL as DB for the OM server.
