### ISSUE TITLE
Dagster Connector Improvement

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#7934]
- [x] We need to explore the dagster cloud and how to authenticate with the api
- [x] We need to generate lineage between the assets and jobs as displayed in Dagster UI
- [ ] #8468

support thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1664877683642579

**Comment by geoHeil** [comment]
I volunteer to alpha test this functionality - please ping me when it is ready.

**Comment by geoHeil** [comment]
Also: https://dagster.io/community please reach out to the awesome dagster community with regards to dagster cloud. They usually are super supportive.

**Comment by geoHeil** [comment]
potentially https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-datahub can serve as an example

**Comment by geoHeil** [comment]
@sryza FYI - perhaps dagster`s OSS team can help here as well.

**Comment by geoHeil** [comment]
also see https://openmetadata.slack.com/archives/C02B6955S4S/p1666015082437819

**Comment by geoHeil** [comment]
https://github.com/open-metadata/OpenMetadata/issues/8188

**Comment by geoHeil** [comment]
I think the dagster pipeline is not super stable. In fact it is failing for:

```
[2022-10-19 23:21:09] DEBUG    {Ingestion:topology_runner:234} - pipeline_service=PipelineService(id=Uuid(__root__=UUID('<<uuid>>')), name=EntityName(__root__='dagster_source_prod'), fullyQualifiedName=FullyQualifiedEntityName(__root__='dagster_source_prod'), serviceType=<PipelineServiceType.Dagster: 'Dagster'>, description=None, displayName=None, version=EntityVersion(__root__=0.2), updatedAt=Timestamp(__root__=1666214368640), updatedBy='admin', pipelines=EntityReferenceList(__root__=[]), connection=PipelineConnection(config=DagsterConnection(type=<DagsterType.Dagster: 'Dagster'>, hostPort=AnyUrl('http://localhost:3000', scheme='http', host='localhost', host_type='int_domain', port='3000'), numberOfStatus=10, supportsMetadataExtraction=SupportsMetadataExtraction(__root__=True))), owner=None, href=Href(__root__=AnyUrl('http://localhost:8585/api/v1/services/pipelineServices/<<uuid>>', scheme='http', host='localhost', host_type='int_domain', port='8585', path='/api/v1/services/pipelineServices/<<uuid>>')), changeDescription=ChangeDescription(fieldsAdded=[], fieldsUpdated=[FieldChange(name=FieldName(__root__='connection'), oldValue='{"config":{"type":"Dagster","hostPort":"http://dagit:3000","numberOfStatus":10}}', newValue='{"config":{"type":"Dagster","numberOfStatus":10,"supportsMetadataExtraction":true,"hostPort":"http://localhost:3000"}}')], fieldsDeleted=[], previousVersion=EntityVersion(__root__=0.1)), deleted=False) pipeline=Pipeline(id=Uuid(__root__=UUID('<<uuid2>>')), name=EntityName(__root__='run_dbt_a95c8_7cb18'), displayName=None, fullyQualifiedName=FullyQualifiedEntityName(__root__='dagster_source_prod.run_dbt_a95c8_7cb18'), description=Markdown(__root__='run_dbt_a95c8_7cb18'), version=EntityVersion(__root__=0.9), updatedAt=Timestamp(__root__=1666214469262), updatedBy='ingestion-bot', pipelineUrl=None, concurrency=None, pipelineLocation=None, startDate=None, tasks=[Task(name='__ASSET_JOB_0', displayName=None, fullyQualifiedName=None, description=None, taskUrl=None, downstreamTasks=None, taskType=None, taskSQL=None, startDate=None, endDate=None, tags=None), Task(name='job_name', displayName=None, fullyQualifiedName=None, description=None, taskUrl=None, downstreamTasks=None, taskType=None, taskSQL=None, startDate=None, endDate=None, tags=None)], pipelineStatus=PipelineStatus(timestamp=Timestamp(__root__=1665181289), executionStatus=<StatusType.Failed: 'Failed'>, taskStatus=[TaskStatus(name='job_name', executionStatus=<StatusType.Failed: 'Failed'>, startTime=Timestamp(__root__=1665181090), endTime=Timestamp(__root__=1665181289), logLink=AnyUrl('http://localhost:3000/instance/runs/ce321978-edd4-4a04-9b73-f3f7b895bef4', scheme='http', host='localhost', host_type='int_domain', port='3000', path='/instance/runs/ce321978-edd4-4a04-9b73-f3f7b895bef4'))]), followers=EntityReferenceList(__root__=[]), tags=[], href=Href(__root__=AnyUrl('http://localhost:8585/api/v1/pipelines/<<uuid2>>', scheme='http', host='localhost', host_type='int_domain', port='8585', path='/api/v1/pipelines/<<uuid2>>')), owner=None, service=EntityReference(id=Uuid(__root__=UUID('<<uuid>>')), type='pipelineService', name='dagster_source_prod', fullyQualifiedName='dagster_source_prod', description=None, displayName=None, deleted=False, href=Href(__root__=AnyUrl('http://localhost:8585/api/v1/services/pipelineServices/<<uuid>>', scheme='http', host='localhost', host_type='int_domain', port='8585', path='/api/v1/services/pipelineServices/<<uuid>>'))), serviceType=<PipelineServiceType.Dagster: 'Dagster'>, changeDescription=ChangeDescription(fieldsAdded=[FieldChange(name=FieldName(__root__='tasks'), oldValue=None, newValue='[{"name":"job_name"}]')], fieldsUpdated=[], fieldsDeleted=[FieldChange(name=FieldName(__root__='tasks'), oldValue='[{"name":"do_osm_update"}]', newValue=None)], previousVersion=EntityVersion(__root__=0.8)), deleted=False, extension=None) pipeline_status=OMetaPipelineStatus(pipeline_fqn='dagster_source_prod.run_dbt_a95c8_7cb18', pipeline_status=PipelineStatus(timestamp=Timestamp(__root__=1665180330), executionStatus=<StatusType.Failed: 'Failed'>, taskStatus=[TaskStatus(name='job_name', executionStatus=<StatusType.Failed: 'Failed'>, startTime=Timestamp(__root__=1665180161), endTime=Timestamp(__root__=1665180330), logLink=AnyUrl('http://localhost:3000/instance/runs/3585d5c7-5d5b-4d09-b848-3cbaca400bbb', scheme='http', host='localhost', host_type='int_domain', port='3000', path='/instance/runs/3585d5c7-5d5b-4d09-b848-3cbaca400bbb'))])) lineage=None
Traceback (most recent call last):
  File "/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/lib/python3.10/site-packages/metadata/cmd.py", line 78, in ingest
    run_ingest(config_path=config)
  File "/lib/python3.10/site-packages/metadata/cli/ingest.py", line 45, in run_ingest
    workflow.execute()
  File "/lib/python3.10/site-packages/metadata/ingestion/api/workflow.py", line 178, in execute
    for record in self.source.next_record():
  File "/lib/python3.10/site-packages/metadata/ingestion/api/topology_runner.py", line 134, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/lib/python3.10/site-packages/metadata/ingestion/api/topology_runner.py", line 100, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/lib/python3.10/site-packages/metadata/ingestion/api/topology_runner.py", line 81, in process_nodes
    for entity_request in stage_fn(element) or []:
  File "/lib/python3.10/site-packages/metadata/ingestion/source/pipeline/dagster.py", line 129, in yield_pipeline_status
    startTime=round(run["stats"]["startTime"]),
TypeError: type NoneType doesn't define __round__ method
```
