### ISSUE TITLE
Profiler ingestion failing on MSSQL 

### ISSUE THREAD

**Issue by sfirke** [open-metadata/OpenMetadata#8404]
**Affected module**
Ingestion

**Describe the bug**
Profile data is populating to the UI but the job always shows as failed.  I screenshared with @harshach at office hours today.

**To Reproduce**
Here's where the log shows the failure, this is followed by a long list of warnings that occurred along the way:

```
10-27 14:06:36,429] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 177, in profiler_workflow
    workflow.raise_from_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/api/workflow.py", line 493, in raise_from_status
    raise WorkflowExecutionError("Processor reported errors", self.status)
metadata.config.common.WorkflowExecutionError: ('Processor reported errors', ProcessorStatus(records=['` ...
```
**Expected behavior**
Profiler ingestion run succeeds.

**Version:**
 - OpenMetadata version: 0.12.2

**Comment by TeddyCr** [comment]
@sfirke are you still experiencing this issue with the latest release (0.13.x)?

**Comment by sfirke** [comment]
hi @TeddyCr - I need to upgrade to 0.13.x still, I was waiting for the stable version and see that's out now.  I'll get to that sometime in the coming month and post back here whether this persists.

**Comment by sfirke** [comment]
Hi @TeddyCr - I will close for now, then after I upgrade to 1.0.0+ I will re-open and ping you if this persists.
