### ISSUE TITLE
Investigate AzureSQL profiler error

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8408]
One of our user was facing an issue when running the profiler on AzureSQL. Error was inconsistent as he had been able to profiler part of the table at some point in time.

```
[2022-10-27, 18:03:31 UTC] {sqa_metrics_computation_registry.py:140} WARNING - Error trying to compute profile for VwComissao.DtEmissao: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '@P1'. (102) (SQLExecDirectW)")
```

**Comment by dr-snglr** [comment]
Hello @TeddyCr 

I got an error while trying to profiel an AzureSQL database as well. It's complaining about a [pyodbc.ProgrammingError](https://sqlalche.me/e/14/f405).

```
`2022-11-06 08:59:43,223] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
return_value = self.execute_callable()
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
return self.python_callable(*self.op_args, **self.op_kwargs)
File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 177, in profiler_workflow
workflow.raise_from_status()
File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/api/workflow.py", line 493, in raise_from_status
raise WorkflowExecutionError("Processor reported errors", self.status)
metadata.config.common.WorkflowExecutionError: ('Processor reported errors', ProcessorStatus(records=['azure.bbl-meta.dbo.test'], warnings=[], failures=[{'azure.bbl-meta.dbo.test': {'area': {'Window Metrics': {"(pyodbc.ProgrammingError) ('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')\n[SQL: SELECT TOP 1 percentile_cont(0.5) WITHIN GROUP (ORDER BY area ASC) OVER() AS median \nFROM dbo.test]\n[parameters: ('test',)]\n(Background on this error at: https://sqlalche.me/e/14/f405)"}}}}]))
[2022-11-06 08:59:43,230] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=azure_profiler_12wEVeBv, task_id=profiler_task, execution_date=20221105T000000, start_date=20221106T085942, end_date=20221106T085943
[2022-11-06 08:59:43,251] {standard_task_runner.py:92} ERROR - Failed to execute job 161 for task profiler_task (('Processor reported errors', ProcessorStatus(records=['azure.bbl-meta.dbo.test'], warnings=[], failures=[{'azure.bbl-meta.dbo.test': {'area': {'Window Metrics': {"(pyodbc.ProgrammingError) ('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')\n[SQL: SELECT TOP 1 percentile_cont(0.5) WITHIN GROUP (ORDER BY area ASC) OVER() AS median \nFROM dbo.test]\n[parameters: ('test',)]\n(Background on this error at: https://sqlalche.me/e/14/f405)"}}}}])); 14616)
[2022-11-06 08:59:43,267] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-06 08:59:43,288] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check`
```

**Comment by TeddyCr** [comment]
Thanks for sharing this @dr-snglr we’ll investigate as well
