### ISSUE TITLE
DBT - Issue while adding descriptions

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#8535]
**Affected module**
Ingestion

**Describe the bug**
Adding descriptions to the table/columns from DBT fails with below error

```
Traceback (most recent call last):
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 106, in process_nodes
    yield from self.check_context_and_handle(process)
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/api/topology_runner.py", line 124, in check_context_and_handle
    for entity_request in node_post_process():
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/source/database/dbt_source.py", line 278, in process_dbt_lineage_and_descriptions
    self.metadata.patch_column_description(
  File "/opt/airflow/venv/lib/python3.8/site-packages/metadata/ingestion/ometa/mixins/patch_mixin.py", line 157, in patch_column_description
    col_index, col = next(
TypeError: cannot unpack non-iterable NoneType object
```

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.12.2]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Comment by harshach** [comment]
@OnkarVO7 assuming this will be resolved as part of DBT refactoring?

**Comment by OnkarVO7** [comment]
Will check it once but it should be handled with the new DBT workflow @harshach
