### ISSUE TITLE
Ingestion for profiling is running flaky

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#8554]
Ingestion for profiling is running flaky, once it got past but in the second run it got failed

<img width="1673" alt="image (18)" src="https://user-images.githubusercontent.com/71748675/200273314-3a34d577-cb08-4940-8a03-a9b1b9d8b0a3.png">

```
[2022-11-07, 07:29:34 UTC] {ingestion_pipeline_mixin.py:48} DEBUG - Created Pipeline Status for pipeline Mysql-ct-test-821616.Mysql-ct-test-821616_profiler_LNImLCvi: {'eventType': 'entityUpdated', 'entityType': 'ingestionPipeline', 'entityId': '3e57d412-6a52-4eaf-837d-7ac6b5d245d0', 'entityFullyQualifiedName': 'Mysql-ct-test-821616.Mysql-ct-test-821616_profiler_LNImLCvi', 'previousVersion': 0.4, 'currentVersion': 0.4, 'userName': 'admin', 'timestamp': 1667806174611, 'changeDescription': {'fieldsAdded': [], 'fieldsUpdated': [{'name': 'testCaseResult', 'oldValue': {'runId': 'e80e7e95-d513-4c34-879b-c5b2b291a5e7', 'pipelineState': 'running', 'startDate': 1667806168353, 'timestamp': 1667806168353}, 'newValue': {'runId': 'e80e7e95-d513-4c34-879b-c5b2b291a5e7', 'pipelineState': 'failed', 'startDate': 1667806168353, 'timestamp': 1667806168353, 'endDate': 1667806174590}}], 'fieldsDeleted': [], 'previousVersion': 0.4}, 'entity': {'id': '3e57d412-6a52-4eaf-837d-7ac6b5d245d0', 'name': 'Mysql-ct-test-821616_profiler_LNImLCvi', 'displayName': 'Mysql-ct-test-821616_profiler_LNImLCvi', 'pipelineType': 'profiler', 'fullyQualifiedName': 'Mysql-ct-test-821616.Mysql-ct-test-821616_profiler_LNImLCvi', 'sourceConfig': {'config': {'type': 'Profiler', 'threadCount': 5, 'profileSample': 0.01, 'generateSampleData': True}}, 'openMetadataServerConnection': {'clusterName': 'openmetadata', 'type': 'OpenMetadata', 'hostPort': 'http://openmetadata-server:8585/api', 'authProvider': 'openmetadata', 'verifySSL': 'no-ssl', 'securityConfig': {'jwtToken': 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmdlc3Rpb24tYm90IiwiaXNCb3QiOnRydWUsImlzcyI6Im9wZW4tbWV0YWRhdGEub3JnIiwiaWF0IjoxNjY3ODAzMjcwLCJlbWFpbCI6ImluZ2VzdGlvbi1ib3RAb3Blbm1ldGFkYXRhLm9yZyJ9.niN6H_1W7oPhJqKfsDH1yd_b1XYL9NdDGw6kfq1NE0R1XFXk7ZG5w9ZMJfVLR1UlLg5FPfdXBuWulMCYAdTdPxwXB4nUidZojgYpNicDwF7KiZ9IaX_LRDhG9jDZfl3sKXjMVVCRNPTIos9a_2WclKwZGPOmWpjd08j5naR8hE295izghhnLdkjTT7LCPj4xoOV61V95JZH5tHggtx--7ucSl87kJgtzATLA-HL942CZMgYtm7mTVphDsWCUco20QZqbEY7tytDH9ukKwGcG5iSqXAOuqGfs2tULqn5cIYcdOK_ylyYfkRRtKA2Q-5Ck_7r4YODLnS8J9nU6ZoTMUA'}, 'secretsManagerProvider': 'noop', 'apiVersion': 'v1', 'includeTopics': True, 'includeTables': True, 'includeDashboards': True, 'includePipelines': True, 'includeMlModels': True, 'includeUsers': True, 'includeTeams': True, 'includeGlossaryTerms': True, 'includeTags': True, 'includePolicy': True, 'includeMessagingServices': True, 'enableVersionValidation': True, 'includeDatabaseServices': True, 'includePipelineServices': True, 'limitRecords': 1000, 'forceEntityOverwriting': False, 'supportsMetadataExtraction': True}, 'airflowConfig': {'pausePipeline': False, 'concurrency': 1, 'pipelineTimezone': 'UTC', 'retries': 3, 'retryDelay': 300, 'pipelineCatchup': False, 'scheduleInterval': '0 * * * *', 'maxActiveRuns': 1, 'workflowDefaultView': 'tree', 'workflowDefaultViewOrientation': 'LR'}, 'loggerLevel': 'DEBUG', 'deployed': True, 'enabled': True, 'href': 'http://openmetadata-server:8585/api/v1/services/ingestionPipelines/3e57d412-6a52-4eaf-837d-7ac6b5d245d0', 'version': 0.4, 'updatedAt': 1667806162450, 'updatedBy': 'admin', 'changeDescription': {'fieldsAdded': [], 'fieldsUpdated': [{'name': 'openMetadataServerConnection', 'oldValue': {'type': 'OpenMetadata', 'hostPort': 'http://openmetadata-server:8585/api', 'verifySSL': 'no-ssl', 'apiVersion': 'v1', 'clusterName': 'openmetadata', 'includeTags': True, 'authProvider': 'openmetadata', 'includeTeams': True, 'includeUsers': True, 'limitRecords': 1000, 'includePolicy': True, 'includeTables': True, 'includeTopics': True, 'securityConfig': {'jwtToken': 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmdlc3Rpb24tYm90IiwiaXNCb3QiOnRydWUsImlzcyI6Im9wZW4tbWV0YWRhdGEub3JnIiwiaWF0IjoxNjY3ODAzMjcwLCJlbWFpbCI6ImluZ2VzdGlvbi1ib3RAb3Blbm1ldGFkYXRhLm9yZyJ9.niN6H_1W7oPhJqKfsDH1yd_b1XYL9NdDGw6kfq1NE0R1XFXk7ZG5w9ZMJfVLR1UlLg5FPfdXBuWulMCYAdTdPxwXB4nUidZojgYpNicDwF7KiZ9IaX_LRDhG9jDZfl3sKXjMVVCRNPTIos9a_2WclKwZGPOmWpjd08j5naR8hE295izghhnLdkjTT7LCPj4xoOV61V95JZH5tHggtx--7ucSl87kJgtzATLA-HL942CZMgYtm7mTVphDsWCUco20QZqbEY7tytDH9ukKwGcG5iSqXAOuqGfs2tULqn5cIYcdOK_ylyYfkRRtKA2Q-5Ck_7r4YODLnS8J9nU6ZoTMUA'}, 'includeMlModels': True, 'includePipelines': True, 'includeDashboards': True, 'includeGlossaryTerms': True, 'forceEntityOverwriting': False, 'secretsManagerProvider': 'noop', 'enableVersionValidation': True, 'includeDatabaseServices': True, 'includePipelineServices': True, 'includeMessagingServices': True, 'supportsMetadataExtraction': True}, 'newValue': {'type': 'OpenMetadata', 'hostPort': 'http://openmetadata-server:8585/api', 'verifySSL': 'no-ssl', 'apiVersion': 'v1', 'clusterName': 'openmetadata', 'includeTags': True, 'authProvider': 'openmetadata', 'includeTeams': True, 'includeUsers': True, 'limitRecords': 1000, 'includePolicy': True, 'includeTables': True, 'includeTopics': True, 'securityConfig': {'jwtToken': 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmdlc3Rpb24tYm90IiwiaXNCb3QiOnRydWUsImlzcyI6Im9wZW4tbWV0YWRhdGEub3JnIiwiaWF0IjoxNjY3ODAzMjcwLCJlbWFpbCI6ImluZ2VzdGlvbi1ib3RAb3Blbm1ldGFkYXRhLm9yZyJ9.niN6H_1W7oPhJqKfsDH1yd_b1XYL9NdDGw6kfq1NE0R1XFXk7ZG5w9ZMJfVLR1UlLg5FPfdXBuWulMCYAdTdPxwXB4nUidZojgYpNicDwF7KiZ9IaX_LRDhG9jDZfl3sKXjMVVCRNPTIos9a_2WclKwZGPOmWpjd08j5naR8hE295izghhnLdkjTT7LCPj4xoOV61V95JZH5tHggtx--7ucSl87kJgtzATLA-HL942CZMgYtm7mTVphDsWCUco20QZqbEY7tytDH9ukKwGcG5iSqXAOuqGfs2tULqn5cIYcdOK_ylyYfkRRtKA2Q-5Ck_7r4YODLnS8J9nU6ZoTMUA'}, 'includeMlModels': True, 'includePipelines': True, 'includeDashboards': True, 'includeGlossaryTerms': True, 'forceEntityOverwriting': False, 'secretsManagerProvider': 'noop', 'enableVersionValidation': True, 'includeDatabaseServices': True, 'includePipelineServices': True, 'includeMessagingServices': True, 'supportsMetadataExtraction': True}}], 'fieldsDeleted': [], 'previousVersion': 0.3}, 'deleted': False}}
[2022-11-07, 07:29:34 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 193, in profiler_workflow
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 188, in profiler_workflow
    workflow.raise_from_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/api/workflow.py", line 501, in raise_from_status
    raise WorkflowExecutionError("Processor reported errors", self.status)
metadata.config.common.WorkflowExecutionError: ('Processor reported errors', ProcessorStatus(records=['Mysql-ct-test-821616.default.cypress_integrations_test_db.team_entity'], warnings=[], failures=[{'Mysql-ct-test-821616.default.cypress_integrations_test_db.team_entity': {'updatedBy': {'Static Metrics': {"pydantic 1.9.0 has no such extra feature 'email'"}}}}]))
[2022-11-07, 07:29:34 UTC] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Mysql-ct-test-821616_profiler_LNImLCvi, task_id=profiler_task, execution_date=20221107T072925, start_date=20221107T072928, end_date=20221107T072934
[2022-11-07, 07:29:34 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 28 for task profiler_task (('Processor reported errors', ProcessorStatus(records=['Mysql-ct-test-821616.default.cypress_integrations_test_db.team_entity'], warnings=[], failures=[{'Mysql-ct-test-821616.default.cypress_integrations_test_db.team_entity': {'updatedBy': {'Static Metrics': {"pydantic 1.9.0 has no such extra feature 'email'"}}}}])); 6728)
[2022-11-07, 07:29:34 UTC] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-07, 07:29:34 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by TeddyCr** [comment]
Seems to be related to this from initial research https://stackoverflow.com/questions/66125129/unknownextra-error-when-installing-via-setup-py-but-not-via-pip. I don't have time to dig deeper into it right now. I'll do that once I have more time.

**Comment by pmbrull** [comment]
taking a look
