### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by erdos2n** [open-metadata/OpenMetadata#8569]
**Affected module**
backend

**Describe the bug**
When configuring OpenMetaData for Airflow there seems to be dependency issues that prevent the deployment from running

**To Reproduce**
Run Airflow (2.4.2) and use the following `requirements.txt` file

```
openmetadata-ingestion
openmetadata-managed-apis
openmetadata-ingestion[airflow-container]
openmetadata-ingestion[airbyte]
openmetadata-ingestion[fivetran]
openmetadata-ingestion[snowflake]
openmetadata-ingestion[snowflake-usage]
openmetadata-airflow
```

**Expected behavior**
A clear and concise description of what you expected to happen. Libraries get installed and Airflow gets deployed

**Version:**
 - OS: [e.g. iOS] Debian 11 or Mac OS 12.6 (Using Docker Desktop to Deploy)
 - Python version: 3.8
 - OpenMetadata version: latest
 - OpenMetadata Ingestion package version:latest (unpinned)

**Additional context**
Here is the error message

```python
[2022-11-07 21:44:45,878] {plugins_manager.py:237} ERROR - Failed to import plugin openmetadata_managed_apis
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/plugins_manager.py", line 229, in load_entrypoint_plugins
    plugin_class = entry_point.load()
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/openmetadata_managed_apis/plugin.py", line 29, in <module>
    with cached_app().app_context():
  File "/usr/local/lib/python3.9/site-packages/airflow/www/app.py", line 167, in cached_app
    app = create_app(config=config, testing=testing)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/app.py", line 149, in create_app
    init_connection_form()
  File "/usr/local/lib/python3.9/site-packages/airflow/www/extensions/init_views.py", line 154, in init_connection_form
    lazy_add_provider_discovered_options_to_connection_form()
  File "/usr/local/lib/python3.9/site-packages/airflow/www/views.py", line 4036, in lazy_add_provider_discovered_options_to_connection_form
    choices=sorted(_get_connection_types(), key=itemgetter(1)),
  File "/usr/local/lib/python3.9/site-packages/airflow/www/views.py", line 4029, in _get_connection_types
    for connection_type, provider_info in providers_manager.hooks.items():
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 887, in hooks
    self.initialize_providers_hooks()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 300, in wrapped_function
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 386, in initialize_providers_hooks
    self.initialize_providers_list()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 300, in wrapped_function
    func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 363, in initialize_providers_list
    self._discover_all_providers_from_packages()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 439, in _discover_all_providers_from_packages
    raise Exception(
Exception: The package 'openmetadata-airflow' from setuptools and openmetadata-ingestion do not match. Please make sure they are aligned
```

**Comment by pmbrull** [comment]
hi @erdos2n thanks for reaching out, apologies for the delay missed the ticket.

I am not sure from where you took the package `openmetadata-airflow`, that is not something we are publishing AFAIK.

The `requirements.txt` could look like

```
openmetadata-managed-apis
openmetadata-ingestion[airbyte,fivetran,snowflake,snowflake-usage]
```

The `airflow-container` plugin is not needed, as you are already installing it on an existing airflow host. We only use it for testing.

**Comment by harshach** [comment]
@pmbrull can we close this?

**Comment by pmbrull** [comment]
hi @erdos2n I'll be closing the issue. Using the correct package names should get rid of it. If you have any other issues, do let us know. Thanks
