### ISSUE TITLE
Issue in MSSQL Lineage ingestion

### ISSUE THREAD

**Issue by eeshan-deshpande** [open-metadata/OpenMetadata#9246]
Lineage Ingestion for MSSQL failing.

Getting below Error.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/lineage/sql_lineage.py", line 383, in get_lineage_by_query
    raw_column_lineage = result.get_column_lineage()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/runner.py", line 22, in wrapper
    self._eval()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/runner.py", line 179, in _eval
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "/home/airflow/.local/lib/python3.9/site-packages/sqllineage/runner.py", line 179, in <listcomp>
    self._stmt_h

Have added the log which contains the query on which it is failing.

Version- Latest version 0.13.0
[Lineage error.txt](https://github.com/open-metadata/OpenMetadata/files/10205479/Lineage.error.txt)

**Comment by ulixius9** [comment]
After analysing the error logs we found that all the errors are related to parsing SQL procedures which would anyways won't be resulting into any sort of lineage with [this](https://github.com/open-metadata/OpenMetadata/pull/11457) pr we have already added filter to process only relevant queries resulting into lineage hence closing this ticket.
