### ISSUE TITLE
metadata restore cli errors with postgres 14.4

### ISSUE THREAD

**Issue by pjain-branch** [open-metadata/OpenMetadata#9276]
**Affected module**
Metadata restore cli

**Describe the bug**
I had used the metadata backup cli to take a backup of postgres(14.4) openmetadata db. Used the same sql file to restore but it fails with the following error:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "\"
LINE 2: ..._settings VALUES ('1','activityFeedFilterSetting',\"[{'filte...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/metadata/cmd.py", line 453, in restore
    schema,
  File "/usr/local/lib/python3.7/site-packages/metadata/cli/restore.py", line 74, in run_restore
    execute_sql_file(engine=engine, sql_file=sql_file)
  File "/usr/local/lib/python3.7/site-packages/metadata/cli/restore.py", line 37, in execute_sql_file
    conn.execute(clean_query)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1370, in execute
    future=False,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1676, in _exec_driver_sql
    distilled_parameters,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "\"
LINE 2: ..._settings VALUES ('1','activityFeedFilterSetting',\"[{'filte...
                                                             ^

[SQL: /* {"app": "OpenMetadata", "version": "0.12.3.0"} */
INSERT INTO openmetadata_settings VALUES ('1','activityFeedFilterSetting',\"[{'filters': [{'exclude': [], 'include': ['all'], 'eventType': 'entityCreated'}, {'exclude': ['usageSummary'], 'include': ['all'], 'eventType': 'entityUpdated'}, {'exclude': [], 'include': ['all'], 'eventType': 'entityDeleted'}, {'exclude': [], 'include': ['all'], 'eventType': 'entitySoftDeleted'}], 'entityType': 'all'}, {'filters': [{'exclude': [], 'include': ['all'], 'eventType': 'entityCreated'}, {'exclude': [], 'include': ['description', 'owner', 'tags', 'followers'], 'eventType': 'entityUpdated'}, {'exclude': [], 'include': ['all'], 'eventType': 'entityDeleted'}, {'exclude': [], 'include': ['all'], 'eventType': 'entitySoftDeleted'}], 'entityType': 'table'}, {'filters': [{'exclude': [], 'include': ['all'], 'eventType': 'entityCreated'}, {'exclude': [], 'include': ['description', 'owner', 'tags', 'followers'], 'eventType': 'entityUpdated'}, {'exclude': [], 'include': ['all'], 'eventType': 'entityDeleted'}, {'exclude': [], 'include': ['all'], 'eventType': 'entitySoftDeleted'}], 'entityType': 'dashboard'}, {'filters': [{'exclude': [], 'include': ['all'], 'eventType': 'entityCreated'}, {'exclude': [], 'include': ['description', 'owner', 'tags', 'followers'], 'eventType': 'entityUpdated'}, {'exclude': [], 'include': ['all'], 'eventType': 'entityDeleted'}, {'exclude': [], 'include': ['all'], 'eventType': 'entitySoftDeleted'}], 'entityType': 'pipeline'}, {'filters': [{'exclude': [], 'include': ['all'], 'eventType': 'entityCreated'}, {'exclude': [], 'include': ['description', 'owner', 'tags', 'followers'], 'eventType': 'entityUpdated'}, {'exclude': [], 'include': ['all'], 'eventType': 'entityDeleted'}, {'exclude': [], 'include': ['all'], 'eventType': 'entitySoftDeleted'}], 'entityType': 'mlmodel'}, {'filters': [{'exclude': [], 'include': ['all'], 'eventType': 'entityCreated'}, {'exclude': [], 'include': ['testCaseResultSuccess', 'testCaseResultFailed', 'testCaseResultAborted'], 'eventType': 'entityUpdated'}, {'exclude': [], 'include': ['all'], 'eventType': 'entityDeleted'}, {'exclude': [], 'include': ['all'], 'eventType': 'entitySoftDeleted'}], 'entityType': 'testCase'}]\");
]
```

For the column json in openmetadata_settings: i changed the keys and values to double quotes and surround them with a single quote and then it worked fine but the other columns that are of jsonb type are still failing. 

**To Reproduce**

1. Take backup of postgres 14.4 using metastore backup cli version 0.12.3
2. Use metadata restore cli to restore the openmetadata db and you should see the above error pop up.

**Expected behavior**
The restore should work with postgres 14.4

**Version:**
 - OS: 
 - Python version:
 - OpenMetadata version: 0.12.3
 - OpenMetadata Ingestion package version: openmetadata-ingestion[postgres,backup]==0.12.3.0

**Additional context**

**Comment by pmbrull** [comment]
we'll also validate https://openmetadata.slack.com/archives/C02B6955S4S/p1671043346723289

**Comment by pmbrull** [comment]
Thanks @pjain-branch, I can reproduce the issue you mention.

Re the MySQL issue mentioned in the comment above, that's not reproducible. Asked for more details on the thread.
