### ISSUE TITLE
Databricks Unity Catalog connector

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#9282]
to bring in metadata, including col-level lineage https://www.databricks.com/blog/2022/12/12/announcing-general-availability-data-lineage-unity-catalog.html?utm_source=bambu&utm_medium=social&utm_campaign=advocacy&blaid=3916832

**Comment by oynek** [comment]
I am currently evaluating Open Metadata for a larger customer/project that uses Databricks as a platform. We are using the Unity Catalog in the AWS Cloud and the metadata (type: `metadata`) is already being ingested successfully.

Unfortunately, the type `profiler` does not yet work as desired, because it terminates with the following error message:

`ServerOperationError(
databricks.sql.exc.ServerOperationError: Table or view not found: common.dim__addresses; line 3 pos 5`

Is it possible that this is related to the new three-level namespace of Unity Catalog? Obviously here the catalog (is called `prod`) is not prefixed, but only `common` (schema) and `dim__addresses` (table).

```
[2023-03-23 12:07:48,372] {sqa_profiler_interface.py:429} INFO - Computing metrics with 1.0 threads.
[2023-03-23 12:07:48,372] {sqa_profiler_interface.py:383} DEBUG - Running profiler for dim__addresses on thread <Thread(ThreadPoolExecutor-0_0, started 140370805487360)>
[2023-03-23 12:07:48,372] {system.py:65} INFO - System metrics not support for databricks. Skipping processing.
[2023-03-23 12:07:48,374] {sqa_profiler_interface.py:383} DEBUG - Running profiler for dim__addresses on thread <Thread(ThreadPoolExecutor-0_0, started 140370805487360)>
[2023-03-23 12:07:48,967] {sqa_profiler_interface.py:177} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/client.py", line 241, in execute
    execute_response = self.thrift_backend.execute_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 629, in execute_command
    return self._handle_execute_response(resp, cursor)
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 704, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 582, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(op_handle,
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 359, in _check_command_not_in_error_or_closed_state
    raise ServerOperationError(
databricks.sql.exc.ServerOperationError: Table or view not found: common.dim__addresses; line 3 pos 5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/interfaces/sqalchemy/sqa_profiler_interface.py", line 168, in _
    row = runner.select_first_from_sample(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/handle_partition.py", line 128, in handle_and_execute
    return func(_self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/orm_profiler/profiler/runner.py", line 80, in select_first_from_sample
    return self._select_from_sample(*entities, **kwargs).first()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/client.py", line 241, in execute
    execute_response = self.thrift_backend.execute_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 629, in execute_command
    return self._handle_execute_response(resp, cursor)
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 704, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 582, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(op_handle,
  File "/home/airflow/.local/lib/python3.9/site-packages/databricks/sql/thrift_backend.py", line 359, in _check_command_not_in_error_or_closed_state
    raise ServerOperationError(
sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) Table or view not found: common.dim__addresses; line 3 pos 5
[SQL: /* {"app": "OpenMetadata", "version": "0.13.2.8"} */
SELECT count(*) AS `rowCount`, %(param_1)s AS `columnCount`, %(param_2)s AS `columnNames` 
FROM `common`.`dim__addresses`
 LIMIT %(param_3)s]
[parameters: {'param_1': 4, 'param_2': 'dim__addresses__sk,country,city,zip', 'param_3': 1}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

**Comment by pmbrull** [comment]
We can review the [sdk](https://github.com/databricks/databricks-sdk-py) and see if it brings more/better info than our current SQLAlchemy approach. It might be easier to get all the info from there
