### ISSUE TITLE
Airflow dag not being created

### ISSUE THREAD

**Issue by Armadik** [open-metadata/OpenMetadata#9435]
**Affected module**
UI

**Describe the bug**
Airflow dag not being created

**To Reproduce**

I installed an application using Helm. Application and packages version 0.13.0     
When trying to create a dags, an error occurs:

```
[2022-12-20 15:25:06,185] {deploy.py:112} ERROR - Failed to import dag_file [/opt/airflow/dags/test_metadata_HGcN2EBl.py]: Failed to generate workflow [test_metadata_HGcN2EBl] verify config is correct: Could not get service from type pipelineService
[2022-12-20 15:25:06,185] {deploy.py:83} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/workflow_factory.py", line 74, in build_dag
    workflow = workflow_builder.build()
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/workflow_builder.py", line 50, in build
    dag = build_fn(self.airflow_pipeline)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/metadata.py", line 61, in build_metadata_dag
    workflow_config = build_metadata_workflow_config(ingestion_pipeline)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/metadata.py", line 45, in build_metadata_workflow_config
    source=build_source(ingestion_pipeline),
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 182, in build_source
    raise InvalidServiceException(f"Could not get service from type {service_type}")
openmetadata_managed_apis.workflows.ingestion.common.InvalidServiceException: Could not get service from type pipelineService

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/api/routes/deploy.py", line 68, in deploy_dag
    response = deployer.deploy()
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/operations/deploy.py", line 165, in deploy
    dag_py_file = self.store_and_validate_dag_file(dag_runner_config)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/operations/deploy.py", line 113, in store_and_validate_dag_file
    raise exc
```

I don't see any problem in json dag.
`...
		},
	"service": {
		"id": "f5a53f56-da12-48e8-8daf-4fc3666e9661",
		"type": "pipelineService",
		"name": "airflow_test",
		"fullyQualifiedName": "airflow_test",
		"description": "airflow_test",
		"displayName": null,
		"deleted": false,
		"href": null
	},
...`

**Expected behavior**

**Version:**
dockerhub
openmetadata/ingestion                            0.13.0            
openmetadata/server                               0.13.0          
   
**Additional context**

**Comment by pmbrull** [comment]
Hi @Armadik, this is failing when Airflow tries to GET the service from the OpenMetadata server.

Could you please validate if your ingestion-bot has proper permissions to run the call? You can get the token from `Settings > Bots > Ingestion bot` and then run a cURL request similar to

```bash
curl --location --request GET 'http://<server>:8585/api/v1/services/databaseServices/name/<service name>' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <token>'
```

**Comment by martsec** [comment]
I'm having the same error, and executing this gets me `{"code":403,"message":"Principal: CatalogPrincipal{name='ingestion-bot'} operations [ViewAll] not allowed"}`

**Comment by Armadik** [comment]
@pmbrull Thanks for the quick response. I noticed that the problem does not occur when using authentication provider: "basic". In my schema I am using custom-oidc integration with keycloak. It's not entirely clear to me what jwt I should and where to put it?

`{"code":403,"message":"Principal: CatalogPrincipal{name='ingestion-bot'} operations [ViewAll] not allowed"}`

**Comment by nahuelverdugo** [comment]
Hi @Armadik and @martsec, the bug will be fixed on `0.13.1` by this PR https://github.com/open-metadata/OpenMetadata/pull/9351. As a workaround, you can assign the `Ingestion bot role` to the bot if it is not in `{your_domain}/bots/ingestion-bot`.

**Comment by pmbrull** [comment]
@Armadik for other SSO providers, they are the ones generating the SSO for the auth. So to curl endpoints under keycloack, their docs should cover how to get that going.

In any case, I'd recommend sticking to JWT tokens for bots and adding the missing role as @nahuelverdugo pointed above.

Please, confirm if that is working for you and we'll close this issue as the bug has already been fixed.

Thanks

**Comment by Armadik** [comment]
Thank you very much, Adding the role solved my problem!
