### ISSUE TITLE
Databricks metadata ingestion job fails due not waiting engouth time to the cluster be ready

### ISSUE THREAD

**Issue by fredericocotrim** [open-metadata/OpenMetadata#9639]
**Affected module**
Ingestion Framework

**Describe the bug**
The Databricks metadata ingestion the job is failing due the time that the cluster takes to be running. 
The cluster is configured as autoscaling (scale based on demand) and terminate after 30 minutes of inactivity.
When the ingestion job runs, it already is starting the cluster when it is down. But it isn't waiting engouth time to the cluster be ready, so the job fails. If after some minutes the job is executed again it works because the cluster is ready due the last job that fails (but started the cluster).

**Expected behavior**
It's expected to be possible the job wait the cluster to be ready.  A way to be possible to increase the retry's number of connection or the interval between them.

**Version:**
 - OpenMetadata version: 0.13.1

**Additional context**
Slack - Support: https://openmetadata.slack.com/archives/C02B6955S4S/p1672918610738319

Logs:
```
Reading local file: /opt/airflow/logs/dag_id=dbw-stargate_metadata_m61TZKb9/run_id=scheduled__2023-01-04T04:00:00+00:00/task_id=ingestion_task/attempt=1.log
[2023-01-05, 01:00:16 -03] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dbw-stargate_metadata_m61TZKb9.ingestion_task scheduled__2023-01-04T04:00:00+00:00 [queued]>
[2023-01-05, 01:00:16 -03] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dbw-stargate_metadata_m61TZKb9.ingestion_task scheduled__2023-01-04T04:00:00+00:00 [queued]>
[2023-01-05, 01:00:16 -03] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-05, 01:00:16 -03] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-01-05, 01:00:16 -03] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-05, 01:00:16 -03] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): ingestion_task> on 2023-01-04 04:00:00+00:00
[2023-01-05, 01:00:16 -03] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2023-01-05, 01:00:16 -03] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbw-stargate_metadata_m61TZKb9', 'ingestion_task', 'scheduled__2023-01-04T04:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dbw-stargate_metadata_m61TZKb9.py', '--cfg-path', '/tmp/tmpagcek0yj', '--error-file', '/tmp/tmpqi7p3u4q']
[2023-01-05, 01:00:16 -03] {standard_task_runner.py:80} INFO - Job 16: Subtask ingestion_task
[2023-01-05, 01:00:17 -03] {task_command.py:371} INFO - Running <TaskInstance: dbw-stargate_metadata_m61TZKb9.ingestion_task scheduled__2023-01-04T04:00:00+00:00 [running]> on host dbwstargatemetadatam61tzkb9ing-8b24e69d65b9450f89d1f22666b5a781
[2023-01-05, 01:00:18 -03] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-01-05, 01:00:18 -03] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=frederico.cotrim
AIRFLOW_CTX_DAG_ID=dbw-stargate_metadata_m61TZKb9
AIRFLOW_CTX_TASK_ID=ingestion_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-04T04:00:00+00:00
[2023-01-05, 01:00:19 -03] {workflow.py:107} INFO - Service type:ServiceType.Database,databricks configured
[2023-01-05, 01:00:21 -03] {client.py:342} INFO - Retrying request after error in 30 seconds: Method: OpenSession; Session-id: None; Query-id: None; HTTP-code: 503; Error-message: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Terminated. Please retry your request after 30 seconds.; Original-exception: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Terminated. Please retry your request after 30 seconds.; Bounded-retry-delay: 30; Attempt: 1/30; Elapsed-seconds: 1.8379786014556885/900.0
[2023-01-05, 01:00:52 -03] {client.py:342} INFO - Retrying request after error in 30 seconds: Method: OpenSession; Session-id: None; Query-id: None; HTTP-code: 503; Error-message: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Pending. Please retry your request after 30 seconds.; Original-exception: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Pending. Please retry your request after 30 seconds.; Bounded-retry-delay: 30; Attempt: 2/30; Elapsed-seconds: 32.20433449745178/900.0
[2023-01-05, 01:01:22 -03] {client.py:342} INFO - Retrying request after error in 30 seconds: Method: OpenSession; Session-id: None; Query-id: None; HTTP-code: 503; Error-message: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Pending. Please retry your request after 30 seconds.; Original-exception: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Pending. Please retry your request after 30 seconds.; Bounded-retry-delay: 30; Attempt: 3/30; Elapsed-seconds: 62.61916422843933/900.0
[2023-01-05, 01:01:53 -03] {client.py:342} INFO - Retrying request after error in 30 seconds: Method: OpenSession; Session-id: None; Query-id: None; HTTP-code: 503; Error-message: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Pending. Please retry your request after 30 seconds.; Original-exception: TEMPORARILY_UNAVAILABLE: Cluster 0727-200305-twtz1cqw is temporarily unavailable. The current cluster state is Pending. Please retry your request after 30 seconds.; Bounded-retry-delay: 30; Attempt: 4/30; Elapsed-seconds: 92.9430284500122/900.0
[2023-01-05, 01:02:20 -03] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
```

```
metadata.utils.connections.SourceConnectionException: Unknown error connecting with Engine(databricks+connector://token:***@adb-000000000000000.0.azuredatabricks.net:443): [SIGNUM 14] Timer expired.
[2023-01-05, 01:02:20 -03] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=dbw-stargate_metadata_m61TZKb9, task_id=ingestion_task, execution_date=20230104T040000, start_date=20230105T040016, end_date=20230105T040220
[2023-01-05, 01:02:20 -03] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task ingestion_task (Unknown error connecting with Engine(databricks+connector://token:***@adb-661170928677222.2.azuredatabricks.net:443): [SIGNUM 14] Timer expired.; 109)
[2023-01-05, 01:02:20 -03] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-05, 01:02:20 -03] {logging_mixin.py:115} WARNING - --- Logging error ---
[2023-01-05, 01:02:20 -03] {logging_mixin.py:115} WARNING - Traceback (most recent call last):
[2023-01-05, 01:02:20 -03] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/logging/handlers.py", line 74, in emit
```

**Comment by pmbrull** [comment]
We can use https://docs.databricks.com/dev-tools/api/latest/clusters.html#start and https://docs.databricks.com/dev-tools/api/latest/clusters.html#get to listen to the status before starting the ingestion
