### ISSUE TITLE
Minio S3: AttributeError: 'AWSCredentials' object has no attribute 'awsSecretAccessKeyx'

### ISSUE THREAD

**Issue by sapcode** [open-metadata/OpenMetadata#9953]
**Affected module**
It is about the Ingestion Framework the Airflow python code expects AttributeError: 'AWSCredentials' object has no attribute 'awsSecretAccessKeyx'

**Describe the bug**
Using the datalake connector to read a PARQUET file from an S3 bucket an error happens. Here is the error part of the log:
[2023-01-27, 09:24:22 UTC] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.table.Table'> processor='yield_table' context='table' ack_sink=True nullable=False must_return=False cache_all=False clear_cache=False overwrite=True consumer=['database_service', 'database', 'database_schema']
[2023-01-27, 09:24:22 UTC] {datalake.py:527} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/datalake.py", line 524, in get_s3_files
    return read_parquet_from_s3(client_kwargs, key, bucket_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/s3_utils.py", line 93, in read_parquet_from_s3
    if client.awsAccessKeyId and client.awsSecretAccessKeyx:
AttributeError: 'AWSCredentials' object has no attribute 'awsSecretAccessKeyx'

**To Reproduce**
1 - We use Minio
We have a minio Datalake connection setup 
bucket: artifacts
region: eu-central-1
Some example parquet Files exists 
Connection settings:
![image](https://user-images.githubusercontent.com/10140758/215054783-279a4741-b226-48f4-a8f7-102fbf39961f.png)

Connect test seems to be ok:
![image](https://user-images.githubusercontent.com/10140758/215054869-d78fdbca-536c-4139-a21d-d817911434af.png)

**Expected behavior**
The parquet files should be all read

**Version:**
 - OS: managed by helm chart installer
 - Python version: 3.9 managed by helm chart installer
 - OpenMetadata version: openmetadata/server:0.13.1 managed by helm chart installer
 - OpenMetadata Ingestion package version: openmetadata/ingestion:0.13.1 managed by helm chart installer

**Additional context**

**Comment by sapcode** [comment]
Dear @pmbrull & @harshach,
thank you very much for picking this issue so fast !

We have tested the code fix in patching the line inside of the docker container "openmetadata/ingestion:0.13.1 and now it seems to go one step further but it breaks in reading the files with ListObjectsV2:

botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/database/datalake.py", line 524, in get_s3_files
return read_parquet_from_s3(client_kwargs, key, bucket_name)
File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/s3_utils.py", line 101, in read_parquet_from_s3
dataset = pq.ParquetDataset(bucket_uri, filesystem=s3_fs)
File "/home/airflow/.local/lib/python3.9/site-packages/pyarrow/parquet.py", line 1355, in init
self.metadata_path) = _make_manifest(
File "/home/airflow/.local/lib/python3.9/site-packages/pyarrow/parquet.py", line 1591, in _make_manifest
if _is_path_like(path_or_paths) and fs.isdir(path_or_paths):
File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 601, in isdir
return bool(self._lsdir(path))
File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 409, in _lsdir
raise translate_boto_error(e)
PermissionError: The AWS Access Key Id you provided does not exist in our records.

[2023-01-27, 18:17:20 UTC] {datalake.py:528} ERROR - Unexpected exception to get S3 file [connector-prototype/raw/20230119-110940.parquet] from bucket [artifacts]: The AWS Access Key Id you provided does not exist in our records.
[2023-01-27, 18:17:20 UTC] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.location.Location'> processor='yield_location' context='location' ack_sink=True nullable=True must_return=False cache_all=False clear_cache=False overwrite=True consumer=['storage_service']
[2023-01-27, 18:17:20 UTC] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.ingestion.source.database.database_service.TableLocationLink'> processor='yield_table_location_link' context=None ack_sink=False nullable=True must_return=False cache_all=False clear_cache=False overwrite=True consumer=None
[2023-01-27, 18:17:20 UTC] {topology_runner.py:78} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.table.Table'> processor='yield_table' context='table' ack_sink=True nullable=False must_return=False cache_all=False clear_cache=False overwrite=True consumer=['database_service', 'database', 'database_schema']
[2023-01-27, 18:17:20 UTC] {datalake.py:527} DEBUG - Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 394, in _lsdir
for i in it:
File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 255, in iter
response = self._make_request(current_kwargs)
File "/home/airflow/.local/lib/python3.9/site-packages/botocore/paginate.py", line 334, in _make_request
return self._method(**current_kwargs)
File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 388, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 708, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.`

Best regards

**Comment by harshach** [comment]
Thanks for the details @sapcode . We are on it and will update this ticket

**Comment by pmbrull** [comment]
Thanks for raising the issue. It will be part of the 0.13.2 release
